### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  id: CompatibleFramework
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  type: Class
  summary: "Beschrijft de versies van .NET Framework dat een toepassing kan worden uitgevoerd op."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;> </xref> klasse."
  syntax:
    content: public CompatibleFramework ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  id: Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Hiermee geeft u het profiel van de bijbehorende .NET Framework."
  remarks: "Een profiel is een subset van het volledige .NET Framework. Bijvoorbeeld, de [!INCLUDE[net_client_v35_long](~/add/includes/net-client-v35-long-md.md)] is een subset van de [!INCLUDE[net_v35SP1_long](~/add/includes/net-v35sp1-long-md.md)], en de [!INCLUDE[net_client_v40_long](~/add/includes/net-client-v40-long-md.md)] is een subset van de [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)]. Zie voor meer informatie [.NET Framework Client Profile](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string Profile { get; set; }
    return:
      type: System.String
      description: "Een <xref:System.String>-object met het profiel van.NET Framework.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Opgehaald of ingesteld van de ondersteunde runtime voor het kader."
  syntax:
    content: public string SupportedRuntime { get; set; }
    return:
      type: System.String
      description: "Een <xref:System.String>-object met een runtimeversie van de bijbehorende .NET Framework.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  id: Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Opgehaald of ingesteld van de versie van het framework."
  syntax:
    content: public string Version { get; set; }
    return:
      type: System.String
      description: "Een <xref:System.String>-object met de versie van een .NET Framework.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  id: XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Opgehaald of ingesteld van de XML-versie voor het kader."
  syntax:
    content: public string XmlProfile { get; set; }
    return:
      type: System.String
      description: "Een matrix van XML-elementen die staat voor het profiel van.NET Framework."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  id: XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Opgehaald of ingesteld van de runtime XML wordt ondersteund voor het kader."
  syntax:
    content: public string XmlSupportedRuntime { get; set; }
    return:
      type: System.String
      description: "Een matrix van XML-elementen die de runtimeversie van de bijbehorende .NET Framework vertegenwoordigt."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  id: XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Opgehaald of ingesteld van de versie van het framework."
  syntax:
    content: public string XmlVersion { get; set; }
    return:
      type: System.String
      description: "Een matrix van XML-elementen die de doelversie van .NET-Framework."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: CompatibleFramework
  nameWithType: CompatibleFramework.CompatibleFramework
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Version
  nameWithType: CompatibleFramework.Version
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
