### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  id: ShutdownEventHandler
  langs:
  - csharp
  name: ShutdownEventHandler
  nameWithType: ShutdownEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die wordt afgehandeld tijdens de <xref uid=&quot;langword_csharp_My.Application.Shutdown&quot; name=&quot;My.Application.Shutdown&quot; href=&quot;&quot;> </xref> gebeurtenis."
  remarks: "In Visual Basic kunt wilt u niet werken met deze gemachtigde expliciet. Zie voor meer informatie <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown>.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown>"
  example:
  - "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown?displayProperty=fullName>  \n  \n [Overview of the Visual Basic Application Model](~/add/includes/ajax-current-ext-md.md)"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void ShutdownEventHandler(object sender, EventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
