### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  id: AuthenticationMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  type: Enum
  summary: "Hiermee wordt aangegeven hoe een Visual Basic-toepassing verifieert de gebruiker voor de <xref uid=&quot;langword_csharp_My.User&quot; name=&quot;My.User&quot; href=&quot;&quot;> </xref> object."
  remarks: "U kunt de verificatiemodus voor een toepassing instellen door het doorgeven van een van deze opsomming waarden om de <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A>constructor.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A> Zie voor meer informatie [uitbreiden van de Visual Basic toepassingsmodel](~/add/includes/ajax-current-ext-md.md).       Een Visual Basic-toepassing die gebruikmaakt van het Model van de toepassing Visual Basic kunt u opgeven of het Windows-verificatie of aangepaste verificatie gebruikt. U kunt ook de verificatiemodus in Visual Studio Integrated Development Environment configureren. Zie voor meer informatie [pagina toepassing Project Designer (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  id: ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "De &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; constructor biedt de principal voor de hoofdthread van de toepassing niet initialiseren. De toepassing moet de principal voor de toepassing hoofdthread initialiseren."
  syntax:
    content: ApplicationDefined
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  id: Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "De &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; constructor initialiseert de principal voor de hoofdthread van de toepassing met de Windows-gebruikersgegevens van de huidige gebruiker."
  syntax:
    content: Windows
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
