### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ExpressionBuilder
  id: ExpressionBuilder
  children:
  - System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  - System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  - System.Web.Configuration.ExpressionBuilder.Properties
  - System.Web.Configuration.ExpressionBuilder.Type
  langs:
  - csharp
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder
  fullName: System.Web.Configuration.ExpressionBuilder
  type: Class
  summary: "Hiermee haalt een dynamische bron tijdens de compilatie."
  remarks: "ASP.NET evalueert expressies automatisch tijdens het parseren van de klasse ExpressionBuilder gebruiken pagina. De <xref:System.Web.Configuration.ExpressionBuilderCollection>verzameling, die bestaat uit de `expressionBuilders` elementen in de `compilation` sectie van de configuratie.</xref:System.Web.Configuration.ExpressionBuilderCollection> De ExpressionBuilder bevat specifieke waarden in de sleutel-waardeparen.       Een waarde wordt opgehaald door een expressie van het formulier, waaronder `<%$ ExpressionPrefix: ExpressionKey %>` binnen de pagina. De `ExpressionPrefix` toegewezen van het type van de expressie die moet worden opgehaald als een gemeenschappelijk opbouwfunctie type (dat wil zeggen, <xref:System.Web.Compilation.AppSettingsExpressionBuilder>) of een aangepaste expressie builder type.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> De `ExpressionKey` geeft de sleutel die wordt gebruikt om te verwijzen naar de geretourneerde waarde.       Als u kiest voor het implementeren van een gemeenschappelijk opbouwfunctie type, moet u de naam van de bijbehorende sectie in de configuratie van de opbouwfunctie toewijzen. Als u kiest voor het implementeren van een type aangepaste opbouwfunctie, moet u uw opbouwfunctie toewijzen aan uw aangepaste opbouwfunctie-klasse, die moet worden afgeleid van de klasse ExpressionBuilder."
  syntax:
    content: 'public sealed class ExpressionBuilder : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionBuilder(String,String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String,String)
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionBuilder(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.ExpressionBuilder&quot;> </xref> klasse."
  remarks: ''
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.ExpressionBuilder> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ExpressionBuilderCollection> class.  \n  \n [!code-cs[System.Web.Configuration.ExpressionBuilderCollection#2](~/add/codesnippet/csharp/e711f1b6-36ca-4643-bdf7-_1.cs)]\n [!code-vb[System.Web.Configuration.ExpressionBuilderCollection#2](~/add/codesnippet/visualbasic/e711f1b6-36ca-4643-bdf7-_1.vb)]"
  syntax:
    content: public ExpressionBuilder (string expressionPrefix, string theType);
    parameters:
    - id: expressionPrefix
      type: System.String
      description: "Een tekenreeks die aangeeft welk type van de expressie om op te halen."
    - id: theType
      type: System.String
      description: "Een tekenreeks die welk Expressietype aangeeft."
  overload: System.Web.Configuration.ExpressionBuilder.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  id: ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een tekenreeks die aangeeft welk type van de expressie om op te halen."
  remarks: "De ExpressionPrefix de expressie wordt toegewezen aan de naam van de bijbehorende sectie in de configuratie voor bekende expressietypen of de expressie wordt toegewezen aan de klasse aangepaste expressie."
  syntax:
    content: public string ExpressionPrefix { get; set; }
    return:
      type: System.String
      description: "Een tekenreeks die aangeeft welk type van de expressie om op te halen."
  overload: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  id: Properties
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: System.Web.Configuration.ExpressionBuilder.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.ExpressionBuilder.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.Type
  id: Type
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: System.Web.Configuration.ExpressionBuilder.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een tekenreeks die welk Expressietype aangeeft."
  remarks: "Het Type geeft het type object dat wordt gebruikt om de waarde van de expressie te bepalen. Het type kunt opgeven voor een sectie in de configuratie of een aangepaste klasse."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Een tekenreeks die welk Expressietype aangeeft."
  overload: System.Web.Configuration.ExpressionBuilder.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder(String,String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String,String)
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionBuilder(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: System.Web.Configuration.ExpressionBuilder.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ExpressionBuilder.Type
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: System.Web.Configuration.ExpressionBuilder.Type
- uid: System.Web.Configuration.ExpressionBuilder.#ctor*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder.ExpressionBuilder
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
- uid: System.Web.Configuration.ExpressionBuilder.Properties*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
- uid: System.Web.Configuration.ExpressionBuilder.Type*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
