### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  id: ServiceSettingsResponseInfo
  children:
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  langs:
  - csharp
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  type: Class
  summary: "Bevat de informatie die wordt geretourneerd wanneer een peer vraagt om de instellingen voor een peer-omzetter-service."
  remarks: "Instanties van deze klasse worden voornamelijk gebruikt om informatie over de reactie van de service instellingen van de omzettingsservice doorgeven aan een netwerkclient van die service."
  syntax:
    content: >-
      [System.ServiceModel.MessageContract(IsWrapped=false)]

      public class ServiceSettingsResponseInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initialiseert een nieuw exemplaar van de standaardwaarde van de <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> klasse."
  remarks: "De standaardwaarde van `control` is ingesteld op true."
  syntax:
    content: public ServiceSettingsResponseInfo ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> klasse met de opgegeven referentie beleidswaarde."
  syntax:
    content: public ServiceSettingsResponseInfo (bool control);
    parameters:
    - id: control
      type: System.Boolean
      description: "<xref:System.Boolean>die aangeeft of de verwijzingen worden doorgegeven door de resolver-service.</xref:System.Boolean>"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  id: ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Opgehaald of ingesteld of verwijzingen worden door de omzettingsservice doorgegeven."
  syntax:
    content: public bool ControlMeshShape { get; set; }
    return:
      type: System.Boolean
      description: "De waarde True als de verwijzingen van peers die deel uitmaken van de mesh worden doorgegeven; False als ze worden genegeerd."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  id: HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Hiermee wordt aangegeven of de hoofdtekst van het bericht met een geserialiseerde exemplaar van dit type correct is gevormd."
  syntax:
    content: public bool HasBody ();
    parameters: []
    return:
      type: System.Boolean
      description: "Waar als de service-instellingen antwoordtekst informatie goed gevormd door de afzender; ONWAAR als het niet."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody
  nameWithType: ServiceSettingsResponseInfo.HasBody
