### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WebServiceProtocols
  id: WebServiceProtocols
  children:
  - System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  - System.Web.Services.Configuration.WebServiceProtocols.Documentation
  - System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  - System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  - System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  - System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  - System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  - System.Web.Services.Configuration.WebServiceProtocols.Unknown
  langs:
  - csharp
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
  type: Enum
  summary: "Hiermee geeft u de overdrachtsprotocollen die worden gebruikt voor het ontsleutelen van gegevens vanaf een clientbrowser in de HTTP-aanvraag is verzonden."
  remarks: >-
    > [!CAUTION]

    >  Using the HttpPostLocalhost value of this enumeration does not prevent access to the test or web service from remote computers. This value checks only the host header of the request; no other validation, authentication, or authorization checks are performed. This check mitigates only browser-based redirection attacks. Authentication and authorization are still required to restrict access to a Web service.
  syntax:
    content: >-
      [System.Flags]

      public enum WebServiceProtocols
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  id: AnyHttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: AnyHttpSoap
  nameWithType: WebServiceProtocols.AnyHttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Alle versies van het HTTP-SOAP-protocol."
  syntax:
    content: AnyHttpSoap
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  id: Documentation
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: Documentation
  nameWithType: WebServiceProtocols.Documentation
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Het protocol Web Services-documentatie."
  syntax:
    content: Documentation
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  id: HttpGet
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpGet
  nameWithType: WebServiceProtocols.HttpGet
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "De HTTP GET-protocol."
  syntax:
    content: HttpGet
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  id: HttpPost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpPost
  nameWithType: WebServiceProtocols.HttpPost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Het HTTP POST-protocol."
  syntax:
    content: HttpPost
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  id: HttpPostLocalhost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpPostLocalhost
  nameWithType: WebServiceProtocols.HttpPostLocalhost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Het protocol HTTP POST LOCALHOST."
  remarks: >-
    > [!CAUTION]

    >  See the Remarks section. This value only checks the request's host header to mitigate only browser-redirect attacks. Authentication and authorization are still required to restrict access to a Web service.
  syntax:
    content: HttpPostLocalhost
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  id: HttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpSoap
  nameWithType: WebServiceProtocols.HttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "De HTTP SOAP-protocol."
  syntax:
    content: HttpSoap
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  id: HttpSoap12
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpSoap12
  nameWithType: WebServiceProtocols.HttpSoap12
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "De HTTP SOAP-versie 1.2-protocol."
  syntax:
    content: HttpSoap12
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  id: Unknown
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: Unknown
  nameWithType: WebServiceProtocols.Unknown
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Onbekende protocol."
  syntax:
    content: Unknown
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: AnyHttpSoap
  nameWithType: WebServiceProtocols.AnyHttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: Documentation
  nameWithType: WebServiceProtocols.Documentation
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Documentation
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpGet
  nameWithType: WebServiceProtocols.HttpGet
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpPost
  nameWithType: WebServiceProtocols.HttpPost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpPostLocalhost
  nameWithType: WebServiceProtocols.HttpPostLocalhost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpSoap
  nameWithType: WebServiceProtocols.HttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpSoap12
  nameWithType: WebServiceProtocols.HttpSoap12
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
- uid: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: Unknown
  nameWithType: WebServiceProtocols.Unknown
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Unknown
