### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Hiermee wordt bepaald hoe Unicode-tekens worden geïnterpreteerd door de <xref:System.Net.WebUtility.HtmlDecode*>methoden.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "Voor meer informatie over hoe Unicode-tekens zijn moeten worden gecodeerd in HTML-code, Zie [teken verlaat in markup- en CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik automatische gedrag. Het decoderen gedrag wordt bepaald door de huidige toepassing doel-Framework. Voor [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] en hoger, Unicode-codering decoderen strikte is."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik compatibel gedrag. Hiermee geeft u op dat binnenkomende gegevens is niet ingeschakeld voor geldigheid voordat worden gedecodeerd. Bijvoorbeeld, een invoertekenreeks &quot;&amp;amp; #xD84C; &quot;wilt decoderen als U + D84C, dit een niet-gekoppelde vervangende is. Bovendien de decoder niet begrijpt in het SMP-codepunten tenzij ze wordt weergegeven als HTML-codering vervangingen dus de inputstring &quot;&amp;#144308; &quot; zou leiden tot de uitvoertekenreeks &quot;&amp;#144308; &quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik losse gedrag. Vergelijkbaar zijn met Compat in dat er geen cheques geldigheid zijn, maar de decoder ook codepunten begrijpt. De invoerreeks &quot;&amp;#144308; &quot;wilt decoderen in het teken U +&233;B4 correct. Deze switch is bedoeld voor maximale interoperabiliteit bij de decoder niet welke indeling van de provider wordt gebruikt weet voor het genereren van de gecodeerde tekenreeks."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik strikte gedrag. Geeft aan dat de binnenkomende gecodeerde gegevens voor geldigheid is gecontroleerd voordat worden gedecodeerd. Bijvoorbeeld, een invoertekenreeks &quot;&amp;#144308; &quot;wilt decoderen als U +&233;B4, maar een invoertekenreeks &quot;&amp;#xD84C;&amp; #xDFB4;&quot;decoderen goed mislukken. Al gedecodeerd gegevens in de tekenreeks wordt niet gecontroleerd op geldigheid. Bijvoorbeeld, resulteert een invoertekenreeks &quot;\\ud800&quot; in een uitvoertekenreeks van &quot;\\ud800&quot;, zoals de vervangende al gedecodeerd is overgeslagen tijdens het decoderen, zelfs als het niet-gekoppelde."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
