### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "Een Web.config-bestand voor een SOAP-functionaliteit COM +-toepassing maakt en onderdeel vermeldingen toegevoegd aan het bestand voor de COM-interfaces wordt gepubliceerd in de toepassing."
  remarks: "De interface IServerWebConfig is geïmplementeerd, alleen door de <xref:System.EnterpriseServices.Internal.ServerWebConfig>klasse en wordt alleen gebruikt in de .NET Framework-infrastructuur.</xref:System.EnterpriseServices.Internal.ServerWebConfig> Gebruik in plaats van deze interface implementeren of instantiëren van een object van de interface IServerWebConfig, de <xref:System.EnterpriseServices.Internal.Publish>klasse, welke implementeert de <xref:System.EnterpriseServices.Internal.IComSoapPublisher>interface.</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig wordt intern gebruikt door het .NET Framework. U hoeft niet te gebruiken deze rechtstreeks in uw code."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "XML-elementen worden toegevoegd aan een Web.config-bestand voor een COM-interface wordt gepubliceerd in een SOAP-functionaliteit COM +-toepassing."
  remarks: "Zie de <xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>methode voor implementatiegegevens.</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> Echter, u hoeft niet aan te roepen `AddElement` rechtstreeks methode."
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Het pad voor het bestaande bestand Web.config."
    - id: AssemblyName
      type: System.String
      description: "De naam van de assembly waarin het type dat wordt toegevoegd."
    - id: TypeName
      type: System.String
      description: "De naam van het type dat wordt toegevoegd."
    - id: ProgId
      type: System.String
      description: "De programma-id voor het type dat wordt toegevoegd."
    - id: Mode
      type: System.String
      description: "Een tekenreeksconstante die overeenkomt met de naam van een lid van de <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> opsomming, waarmee wordt aangegeven hoe een bekend object wordt geactiveerd."
    - id: Error
      type: System.String
      description: "Een tekenreeks waarmee een foutbericht kan worden geschreven."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Een Web.config-bestand voor een SOAP-functionaliteit COM +-toepassing maakt zodat het bestand is gereed om te hebben van XML-elementen toegevoegd voor COM-interfaces wordt gepubliceerd."
  remarks: "Zie de <xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>methode voor implementatiegegevens.</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> Echter, u hoeft niet aan te roepen `Create` rechtstreeks."
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "De map waarin u het configuratiebestand te maken."
    - id: FileRootName
      type: System.String
      description: "De tekenreekswaarde waaraan een config-extensie kan worden toegevoegd (bijvoorbeeld Internet voor Web.config)."
    - id: Error
      type: System.String
      description: "Een tekenreeks waarmee een foutbericht kan worden geschreven."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
