### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProfileGroupSettings
  id: ProfileGroupSettings
  children:
  - System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  - System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  - System.Web.Configuration.ProfileGroupSettings.GetHashCode
  - System.Web.Configuration.ProfileGroupSettings.Name
  - System.Web.Configuration.ProfileGroupSettings.Properties
  - System.Web.Configuration.ProfileGroupSettings.PropertySettings
  langs:
  - csharp
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings
  fullName: System.Web.Configuration.ProfileGroupSettings
  type: Class
  summary: "Programmatische toegang biedt tot de <xref uid=&quot;langword_csharp_group&quot; name=&quot;group&quot; href=&quot;&quot;> </xref> subsectie van het <xref uid=&quot;langword_csharp_profiles&quot; name=&quot;profiles&quot; href=&quot;&quot;> </xref> System.Data.localdb."
  remarks: "De klasse ProfileGroupSettings biedt een manier programmatisch maken, openen en wijzigen van groepen van eigenschappen die zijn toegevoegd aan de `group` subsectie van het `profile` gedeelte van een configuratiebestand.       De `profile` sectie van het configuratiebestand wordt een schema voor de gebruikersprofielen. Tijdens runtime, de ASP.NET-compilatie-systeem gebruikt de informatie die is opgegeven in de `profile` sectie voor het genereren van een klasse met de naam `ProfileCommon`, die is afgeleid van <xref:System.Web.Profile.ProfileBase>.</xref:System.Web.Profile.ProfileBase> De `ProfileCommon` klassedefinitie is gebaseerd op de eigenschappen gedefinieerd in de `properties` subsectie van het `profile` gedeelte van het configuratiebestand. Een exemplaar van deze klasse is gemaakt voor elk gebruikersprofiel en u toegang hebt tot de waarden voor profieleigenschappen in uw code via de <xref:System.Web.HttpContext.Profile%2A?displayProperty=fullName>eigenschap.</xref:System.Web.HttpContext.Profile%2A?displayProperty=fullName> Voor meer informatie over de functies van het profiel wordt toegevoegd aan [!INCLUDE[vstecasplong](~/add/includes/vstecasplong-md.md)], Zie [overzicht van ASP.NET profiel eigenschappen](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following code example shows how to use the ProfileGroupSettings type. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/csharp/t-system.web.configurati_94_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/visualbasic/t-system.web.configurati_94_1.vb)]"
  syntax:
    content: 'public sealed class ProfileGroupSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.ProfileGroupSettings&quot;> </xref> klasse met de standaardinstellingen."
  remarks: "De constructor ProfileGroupSettings is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Verkrijgen van een exemplaar van de <xref:System.Web.Configuration.ProfileGroupSettings>klasse met behulp van de <xref:System.Configuration.Configuration.GetSection%2A>methode.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.ProfileGroupSettings>"
  syntax:
    content: public ProfileGroupSettings (string name);
    parameters:
    - id: name
      type: System.String
      description: "De naam van de nieuwe groep."
  overload: System.Web.Configuration.ProfileGroupSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee wordt bepaald of de opgegeven <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref> gelijk is aan de huidige <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "De <xref:System.Object>moeten worden vergeleken met de huidige <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>.</xref:System.Object>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de opgegeven <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref> gelijk is aan de huidige <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ProfileGroupSettings.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee wordt een unieke waarde die aangeeft van de huidige <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> exemplaar."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Een unieke waarde die aangeeft van de huidige <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> exemplaar."
  overload: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  id: Name
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Naam van de groep opgehaald of ingesteld <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objecten van dit object bevat."
  remarks: "De naam moet uniek zijn binnen een <xref:System.Web.Configuration.ProfileGroupSettingsCollection>verzameling; anders wordt een uitzondering wordt gegenereerd wanneer het configuratiebestand wordt opgeslagen.</xref:System.Web.Configuration.ProfileGroupSettingsCollection>"
  example:
  - "The following code example shows how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/csharp/p-system.web.configurati_232_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/visualbasic/p-system.web.configurati_232_1.vb)]"
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "Een tekenreeks met de naam van de groep van <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objecten van dit object bevat. De standaardwaarde is een lege tekenreeks (&quot;&quot;)."
  overload: System.Web.Configuration.ProfileGroupSettings.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  id: Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.ProfileGroupSettings.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  id: PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Dit object bevat de instellingen voor de verzameling van profiel opgehaald."
  remarks: ''
  example:
  - "The following code example shows how to use the PropertySettings property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/csharp/p-system.web.configurati_256_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/visualbasic/p-system.web.configurati_256_1.vb)]"
  syntax:
    content: public System.Web.Configuration.ProfilePropertySettingsCollection PropertySettings { get; }
    return:
      type: System.Web.Configuration.ProfilePropertySettingsCollection
      description: "Een <xref href=&quot;System.Web.Configuration.ProfilePropertySettingsCollection&quot;> </xref> verzameling die alle bevat de <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objecten in deze groep."
  overload: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
- uid: System.Web.Configuration.ProfilePropertySettingsCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ProfilePropertySettingsCollection
  nameWithType: ProfilePropertySettingsCollection
  fullName: System.Web.Configuration.ProfilePropertySettingsCollection
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings.ProfileGroupSettings
- uid: System.Web.Configuration.ProfileGroupSettings.Equals*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals
  nameWithType: ProfileGroupSettings.Equals
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode
  nameWithType: ProfileGroupSettings.GetHashCode
- uid: System.Web.Configuration.ProfileGroupSettings.Name*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
