### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement
  id: WebHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  langs:
  - csharp
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement
  type: Class
  summary: "Een XML-element dat Hiermee configureert u de beveiliging voor een service met de eindpunten die HTTP-aanvragen ontvangen. Deze klasse kan niet worden overgenomen."
  syntax:
    content: 'public sealed class WebHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> klasse."
  syntax:
    content: public WebHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Hiermee haalt u een XML-element waarmee de beveiligingsmodus voor een eenvoudige HTTP-service."
  remarks: "Deze eigenschap bepaalt u of de instellingen van de <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>eigenschap wordt van kracht.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "Een waarde van <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref> die aangeeft of beveiliging op gebruikersniveau transport of geen beveiliging wordt gebruikt door een eindpunt. De standaardwaarde is <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De waarde is geen geldige <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Hiermee haalt u een XML-element waarmee wordt aangegeven van de beveiligingsinstellingen van transportniveau voor een service-eindpunt is geconfigureerd voor het ontvangen van HTTP-aanvragen."
  remarks: "Gebruik de <xref:System.ServiceModel.Configuration.WebHttpSecurityElement>object dat wordt geretourneerd door deze eigenschap in te stellen het transport van beveiligingsparameters.</xref:System.ServiceModel.Configuration.WebHttpSecurityElement> De <xref:System.ServiceModel.WebHttpSecurityMode>moet worden ingesteld op de <xref:System.ServiceModel.WebHttpSecurityMode>of <xref:System.ServiceModel.WebHttpSecurityMode>waarde voor de instellingen van de <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>eigenschap om te worden van kracht voor het service-eindpunt.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> Deze waarde kan worden ingesteld in de configuratie of in de <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>constructor.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>"
  syntax:
    content: public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: "Een <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> Hiermee worden de beveiligingsinstellingen op transportniveau. De standaardset van waarden zijn een <> </> *> van <xref:System.ServiceModel.HttpClientCredentialType>, een <> </> *> van <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>, en <xref:System.ServiceModel.HttpTransportSecurity.Realm*>= &quot;&quot;.</xref:System.ServiceModel.HttpTransportSecurity.Realm*> </xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
