### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadManager
  id: IApplicationPreloadManager
  children:
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  langs:
  - csharp
  name: IApplicationPreloadManager
  nameWithType: IApplicationPreloadManager
  fullName: System.Web.Hosting.IApplicationPreloadManager
  type: Interface
  summary: "Biedt methoden die ASP.NET gebruikt om aan te roepen van de toepassing preload-functie in [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("AE54F424-71BC-4da5-AA2F-8C0CD53496FC")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadManager
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  id: SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Aangeroepen door [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] melden ASP.NET of een toepassing vooraf moet worden geladen."
  syntax:
    content: public void SetApplicationPreloadState (string context, string appId, bool enabled);
    parameters:
    - id: context
      type: System.String
      description: "De context van de toepassing."
    - id: appId
      type: System.String
      description: "De unieke ID van de toepassing."
    - id: enabled
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>om aan te geven dat de toepassing moet vooraf worden geladen; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  id: SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Aanroepen [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] ophalen van informatie die is vereist voor een toepassing vooraf laden."
  remarks: "Roept IIS ASP.NET via deze interface levert een verwijzing naar een object dat u implementeert de <xref:System.Web.Hosting.IApplicationPreloadUtil>interface.</xref:System.Web.Hosting.IApplicationPreloadUtil> ASP.NET maakt gebruik van die interface later een retouraanroep in IIS voor preload-informatie voor afzonderlijke toepassingen uitvoeren."
  syntax:
    content: public void SetApplicationPreloadUtil (System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
    parameters:
    - id: preloadUtil
      type: System.Web.Hosting.IApplicationPreloadUtil
      description: "De ingang naar een niet-beheerde interface in [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] die ASP.NET-aanroepen voor informatie."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
- uid: System.Web.Hosting.IApplicationPreloadUtil
  parent: System.Web.Hosting
  isExternal: false
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil
