### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.CacheModeValueSerializer
  id: CacheModeValueSerializer
  children:
  - System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer
  type: Class
  summary: "Exemplaren van converteert <xref:System.String>naar en van exemplaren van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref>.</xref:System.String>"
  remarks: "Deze klasse wordt doorgaans alleen gebruikt door de <xref:System.Windows.Markup.Primitives.MarkupWriter>voor serialisatie doeleinden.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class CacheModeValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Windows.Media.Converters.CacheModeValueSerializer&quot;> </xref> klasse."
  syntax:
    content: public CacheModeValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Hiermee wordt bepaald of de opgegeven <xref:System.String>kunnen worden geconverteerd naar een exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref>.</xref:System.String>"
  remarks: "Deze methode retourneert altijd `true`."
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Een <xref:System.String>moet worden geëvalueerd voor conversie.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie die wordt gebruikt voor conversie."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als <code> value </code> kunnen worden geconverteerd, anders wordt <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Hiermee wordt bepaald of het opgegeven exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> kunnen worden geconverteerd naar een <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Een exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> moet worden geëvalueerd voor conversie."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie die wordt gebruikt voor conversie."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als <code> value </code> kan worden geconverteerd naar een <xref:System.String>; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Converteert een <xref:System.String>in een <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Een <xref:System.String>waarde te converteren naar een <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref>.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie die wordt gebruikt voor conversie."
    return:
      type: System.Object
      description: "Een nieuw exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> op basis van de opgegeven <code> value </code>."
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Converteert een exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> naar een <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Een exemplaar van <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> moet worden geëvalueerd voor conversie."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie die wordt gebruikt voor conversie."
    return:
      type: System.String
      description: "Een <xref:System.String>weergave van de opgegeven <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> object.</xref:System.String>"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: CacheModeValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: CacheModeValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: CacheModeValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: CacheModeValueSerializer.ConvertToString
