### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPath
  id: IConfigMapPath
  children:
  - System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  - System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  - System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
  type: Interface
  summary: "Biedt toegang tot de toewijzing tussen configuratiebestand virtuele en fysieke paden."
  remarks: "IConfigMapPath is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IConfigMapPath
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  id: GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee haalt u de naam van de virtuele map die is gekoppeld aan een specifieke site."
  remarks: "GetAppPathForPath is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetAppPathForPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    return:
      type: System.String
      description: "De <code> siteID </code> moeten uniek zijn. Er zijn geen twee sites delen dezelfde id. De <code> siteID </code> onderscheidt van sites met dezelfde naam hebben."
  overload: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  id: GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de standaardnaam van de site en de site-ID."
  remarks: "GetDefaultSiteNameAndID is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetDefaultSiteNameAndID (out string siteName, out string siteID);
    parameters:
    - id: siteName
      type: System.String
      description: "De naam van de standaard-site."
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
  overload: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  id: GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee haalt u de configuratie van de machine-bestandsnaam."
  remarks: "GetMachineConfigFilename is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetMachineConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "De configuratie van de machine-bestandsnaam."
  overload: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  id: GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de directory en de naam van het configuratiebestand op basis van de site-ID en het sitepad."
  remarks: "GetPathConfigFilename is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetPathConfigFilename (string siteID, string path, out string directory, out string baseName);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    - id: directory
      type: System.String
      description: "De fysieke map van het configuratiepad."
    - id: baseName
      type: System.String
      description: "De naam van het configuratiebestand."
  overload: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  id: GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee haalt u de naam van het configuratiebestand in de hoofdmap van het Web."
  remarks: "GetRootWebConfigFilename is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetRootWebConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "De naam van het configuratiebestand in de hoofdmap van het Web."
  overload: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  id: MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee haalt u het fysieke pad op basis van de site-ID en de URL die is gekoppeld aan de site."
  remarks: "MapPath is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string MapPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    return:
      type: System.String
      description: "Het fysieke pad."
  overload: System.Web.Configuration.IConfigMapPath.MapPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  id: ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de sitenaam en site-ID op basis van de waarde van een site-argument."
  remarks: "Als `siteArgument` is `null`, gelijk is aan de standaardnaam van de site of gelijk is aan de site-id van het standaard de `siteName` en `siteID` zijn gevuld met de standaardwaarden van de site.       ResolveSiteArgument is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void ResolveSiteArgument (string siteArgument, out string siteName, out string siteID);
    parameters:
    - id: siteArgument
      type: System.String
      description: "De sitenaam of de site-id."
    - id: siteName
      type: System.String
      description: "De naam van de standaard-site."
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
  overload: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath
  nameWithType: IConfigMapPath.GetAppPathForPath
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename
  nameWithType: IConfigMapPath.GetMachineConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename
  nameWithType: IConfigMapPath.GetPathConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename
  nameWithType: IConfigMapPath.GetRootWebConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.MapPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath
  nameWithType: IConfigMapPath.MapPath
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument
  nameWithType: IConfigMapPath.ResolveSiteArgument
