### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCookiesSection
  id: HttpCookiesSection
  children:
  - System.Web.Configuration.HttpCookiesSection.#ctor
  - System.Web.Configuration.HttpCookiesSection.Domain
  - System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  - System.Web.Configuration.HttpCookiesSection.Properties
  - System.Web.Configuration.HttpCookiesSection.RequireSSL
  langs:
  - csharp
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection
  fullName: System.Web.Configuration.HttpCookiesSection
  type: Class
  summary: "Hiermee configureert u de eigenschappen voor cookies die worden gebruikt door een webtoepassing."
  remarks: "De klasse HttpCookiesSection biedt een manier om programmatisch toegang en wijzig de `httpCookies` gedeelte van een configuratiebestand.       Hiermee definieert u de standaard toegepast op alle cookies die zijn uitgegeven door de toepassing, tenzij deze wordt overschreven door de code voor het uitgeven van de cookie-instellingen.       Een doel van de `httpCookies` element is de ondersteuning van het gebruik van `HttpOnly` cookies. `HttpOnly`cookies (cookies die de `HttpOnly` kenmerk) zijn geïntroduceerd in Internet Explorer 6 om u te helpen bij het risico cross-site scripting. De `HttpOnly` kenmerk voorkomt u dat cookies worden geopend via clientscript. Alle gegevens in een `HttpOnly` cookie is minder waarschijnlijk worden vrijgegeven aan een persoon of een schadelijke website. Voor meer informatie zoekt MSDN (msdn.microsoft.com) &quot;HttpOnly.&quot;      > [!NOTE] > De HttpCookiesSection kunnen lezen en schrijven van gegevens van en naar de bijbehorende sectie van het configuratiebestand op basis van de sectie eigenschap <xref:System.Configuration.SectionInformation.AllowDefinition%2A>waarvan de waarde is <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A>"
  example:
  - "The following code example shows how to obtain the HttpCookiesSection object from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_7_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/csharp/t-system.web.configurati_7_1.cs)]"
  syntax:
    content: 'public sealed class HttpCookiesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.HttpCookiesSection&quot;> </xref> klasse."
  remarks: "Deze constructor is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Verkrijgen van een exemplaar van de <xref:System.Web.Configuration.HttpCookiesSection>klasse met behulp van de <xref:System.Configuration.Configuration.GetSection%2A>methode.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpCookiesSection>"
  syntax:
    content: public HttpCookiesSection ();
    parameters: []
  overload: System.Web.Configuration.HttpCookiesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  id: Domain
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de domeinnaam van de cookie."
  remarks: ''
  example:
  - "The following code example shows how to use the Domain property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_9_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/csharp/p-system.web.configurati_9_1.cs)]"
  syntax:
    content: public string Domain { get; set; }
    return:
      type: System.String
      description: "De domeinnaam van de cookie."
  overload: System.Web.Configuration.HttpCookiesSection.Domain*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  id: HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld met een waarde die aangeeft of de ondersteuning voor de browser <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> cookie is ingeschakeld."
  remarks: "De `httpCookies` element ondersteunt het gebruik van `HttpOnly` cookies. `HttpOnly`cookies (cookies die de `HttpOnly` kenmerk) zijn geïntroduceerd in Internet Explorer 6 om u te helpen bij het risico cross-site scripting. De `HttpOnly` kenmerk voorkomt u dat cookies worden geopend via clientscript. Alle gegevens in een `HttpOnly` cookie is minder waarschijnlijk worden vrijgegeven aan een persoon of een schadelijke website. Voor meer informatie zoekt MSDN (msdn.microsoft.com) &quot;HttpOnly.&quot;"
  example:
  - "The following code example shows how to use the HttpOnlyCookies property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_227_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/csharp/p-system.web.configurati_227_1.cs)]"
  syntax:
    content: public bool HttpOnlyCookies { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als ondersteuning voor de <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> cookie is ingeschakeld, anders, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.HttpCookiesSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  id: RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of communicatie Secure Sockets Layer (SSL) vereist is."
  remarks: "De eigenschap RequireSSL Hiermee of uitvoer van het kenmerk beveiligde cookie zoals beschreven in RFC 2109 uitgeschakeld. Bij gebruik door compatibele browsers, wordt de cookie wordt alleen verzonden terug via een verbinding met behulp van SSL/TLS. De standaardwaarde is `false`."
  example:
  - "The following code example shows how to use the RequireSSL property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_82_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/csharp/p-system.web.configurati_82_1.cs)]"
  syntax:
    content: public bool RequireSSL { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als SSL is ingeschakeld; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
- uid: System.Web.Configuration.HttpCookiesSection.#ctor*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection.HttpCookiesSection
- uid: System.Web.Configuration.HttpCookiesSection.Domain*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
- uid: System.Web.Configuration.HttpCookiesSection.Properties*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
