### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlWriterSettings
  id: XamlXmlWriterSettings
  children:
  - System.Xaml.XamlXmlWriterSettings.#ctor
  - System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  - System.Xaml.XamlXmlWriterSettings.CloseOutput
  - System.Xaml.XamlXmlWriterSettings.Copy
  langs:
  - csharp
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
  type: Class
  summary: "Biedt initialisatie-instellingen voor de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> XAML writer implementatie."
  remarks: "De standaardwaarden voor alle XamlXmlWriterSettings waarden zijn `false`."
  syntax:
    content: 'public class XamlXmlWriterSettings : System.Xaml.XamlWriterSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlWriterSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlXmlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  id: AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> moet altijd wordt ervan uitgegaan dat geldige XAML-invoer voor de doeleinden van dubbele resolutie of andere foutcontrole."
  syntax:
    content: public bool AssumeValidInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> zoals ArgumentOutOfRangeException uitzonderingen op dubbele leden van bepaalde controles validatie of fout wordt overgeslagen. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Als de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> uitzonderingen genereert wanneer ongeldige XAML is opgetreden. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> onmiddellijk moet worden gesloten op <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> of andere bewerkingen, of of de XAML-schrijver de uitvoer van de buffer voordat u afsluit in plaats daarvan moet schrijven. Gebruik deze instelling behoedzaam; Sluit het onmiddellijk kan resulteren in ongeldige XAML die opnieuw kan niet worden geladen."
  remarks: "Deze instelling beïnvloedt de logica van <xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>, welke aanroepen `Close` op de onderliggende <xref:System.Xml.XmlWriter>of <xref:System.IO.TextWriter>wanneer CloseOutput is `true`; of roept deze <xref:System.Xaml.XamlXmlWriter.Flush%2A>(opnieuw worden gekoppeld aan de onderliggende <xref:System.Xml.XmlWriter>of <xref:System.IO.TextWriter>) als CloseOutput `false`.</xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Flush%2A> </xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>"
  syntax:
    content: public bool CloseOutput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> onmiddellijk wordt gesloten op een <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> of vergelijkbare bewerkingen. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Als de uitvoer van de resterende buffer wordt geschreven voordat de <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> wordt vrijgegeven. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  id: Copy
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
  type: Method
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Retourneert een kopie van dit <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> exemplaar."
  syntax:
    content: public System.Xaml.XamlXmlWriterSettings Copy ();
    parameters: []
    return:
      type: System.Xaml.XamlXmlWriterSettings
      description: "Het geretourneerde exemplaar."
  overload: System.Xaml.XamlXmlWriterSettings.Copy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlWriterSettings
  isExternal: false
  name: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
- uid: System.Xaml.XamlXmlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy
  nameWithType: XamlXmlWriterSettings.Copy
