### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCaches
  id: IdentityModelCaches
  children:
  - System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  - System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: System.IdentityModel.Configuration.IdentityModelCaches
  type: Class
  summary: "Hiermee definieert u de caches die zijn geconfigureerd voor het detecteren van herhaald tokens en in de cache van sessie-tokens. Deze klasse kan niet worden overgenomen."
  remarks: "Opgehaald en worden de geconfigureerde <xref:System.IdentityModel.Tokens.TokenReplayCache>en <xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>.</xref:System.IdentityModel.Tokens.SessionSecurityTokenCache> </xref:System.IdentityModel.Tokens.TokenReplayCache> De `Caches` eigenschap van de <xref:System.IdentityModel.Configuration.IdentityConfiguration>klasse en van de <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration>klasse is een exemplaar van IdentityModelCaches.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration> </xref:System.IdentityModel.Configuration.IdentityConfiguration>"
  syntax:
    content: public sealed class IdentityModelCaches
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCaches&quot;> </xref> klasse."
  syntax:
    content: public IdentityModelCaches ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityTokenCache&quot;> </xref> die wordt gebruikt voor de cache de <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityToken&quot;> </xref>."
  syntax:
    content: public System.IdentityModel.Tokens.SessionSecurityTokenCache SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.SessionSecurityTokenCache
      description: "De geconfigureerde token sessiecache."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Een poging de eigenschap instellen op <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> optreedt."
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.IdentityModel.Tokens.TokenReplayCache&quot;> </xref> die wordt gebruikt om te bepalen of tokens opnieuw en nu worden afgespeeld."
  syntax:
    content: public System.IdentityModel.Tokens.TokenReplayCache TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.TokenReplayCache
      description: "De geconfigureerde tokenreplay-cache."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Een poging de eigenschap instellen op <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> optreedt."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Tokens.SessionSecurityTokenCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: SessionSecurityTokenCache
  fullName: System.IdentityModel.Tokens.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
- uid: System.IdentityModel.Tokens.TokenReplayCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: TokenReplayCache
  nameWithType: TokenReplayCache
  fullName: System.IdentityModel.Tokens.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches.IdentityModelCaches
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
