### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidatorAttribute
  id: LongValidatorAttribute
  children:
  - System.Configuration.LongValidatorAttribute.#ctor
  - System.Configuration.LongValidatorAttribute.ExcludeRange
  - System.Configuration.LongValidatorAttribute.MaxValue
  - System.Configuration.LongValidatorAttribute.MinValue
  - System.Configuration.LongValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute
  fullName: System.Configuration.LongValidatorAttribute
  type: Class
  summary: "Hiermee geeft u de .NET Framework lange gehele validatie uitvoeren op een configuratie-eigenschap declaratief. Deze klasse kan niet worden overgenomen."
  remarks: "Het kenmerk LongValidatorAttribute kunt u een configuratie-eigenschap opmaken. Dit is voor het valideren van de eigenschap met behulp van .NET Framework instrueren een <xref:System.Configuration.LongValidator>object en de waarde van de decorating parameters doorgeven aan.</xref:System.Configuration.LongValidator>       U kunt het kenmerk LongValidatorAttribute toepassen op alleen eigenschaptypen."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the LongValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/t-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/t-system.configuration.l_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class LongValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.LongValidatorAttribute&quot;> </xref> klasse."
  remarks: "U kunt deze constructor gebruiken in het model attributed om ervoor te zorgen dat de waarde die is toegewezen aan de bijbehorende eigenschap een lange integer is."
  syntax:
    content: public LongValidatorAttribute ();
    parameters: []
  overload: System.Configuration.LongValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Opgehaald of ingesteld van een waarde die of u aangeeft wilt opnemen of uitsluiten van de gehele getallen in het bereik dat is gedefinieerd door de <> </> *> en <> </> *> eigenschapswaarden."
  remarks: "Het bereik is inclusive van de <xref:System.Configuration.LongValidatorAttribute.MinValue%2A>en <xref:System.Configuration.LongValidatorAttribute.MaxValue%2A>eigenschapswaarden.</xref:System.Configuration.LongValidatorAttribute.MaxValue%2A> </xref:System.Configuration.LongValidatorAttribute.MinValue%2A> Wanneer de waarde van de eigenschap ExcludeRange is `false`, de toegestane waarden vallen buiten het bereik."
  example:
  - "The following example shows how to use the <xref:System.Configuration.IntegerValidatorAttribute.ExcludeRange%2A> property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de waarde moet worden uitgesloten; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.LongValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Opgehaald of ingesteld van de toegestane maximumwaarde voor de eigenschap."
  remarks: "De waarde van de eigenschap MaxValue is opgenomen in het toegestane bereik."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_1_1.cs)]"
  syntax:
    content: public long MaxValue { get; set; }
    return:
      type: System.Int64
      description: "Een lange integer die aangeeft van de toegestane maximumwaarde."
  overload: System.Configuration.LongValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De geselecteerde waarde is kleiner dan <xref:System.Configuration.LongValidatorAttribute.MinValue*>.</xref:System.Configuration.LongValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Opgehaald of ingesteld van de toegestane minimumwaarde voor de eigenschap."
  remarks: "De waarde van de eigenschap MinValue is opgenomen in het toegestane bereik."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_2_1.cs)]"
  syntax:
    content: public long MinValue { get; set; }
    return:
      type: System.Int64
      description: "Een geheel getal dat aangeeft van de toegestane minimumwaarde."
  overload: System.Configuration.LongValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De geselecteerde waarde is groter dan <xref:System.Configuration.LongValidatorAttribute.MaxValue*>.</xref:System.Configuration.LongValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Opgehaald van een exemplaar van de <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> klasse."
  remarks: "Gebruik van de waarde van de eigenschap ValidatorInstance tekenreeks validatie uitvoeren door het aanroepen van de <xref:System.Configuration.LongValidator.Validate%2A>methode.</xref:System.Configuration.LongValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "De <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> validator exemplaar."
  overload: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.LongValidatorAttribute.#ctor
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidatorAttribute.MinValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.LongValidatorAttribute.#ctor*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute.LongValidatorAttribute
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
- uid: System.Configuration.LongValidatorAttribute.MaxValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
- uid: System.Configuration.LongValidatorAttribute.MinValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
