### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.HttpMessageSettings
  id: HttpMessageSettings
  children:
  - System.ServiceModel.Channels.HttpMessageSettings.#ctor
  - System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  - System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  langs:
  - csharp
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
  type: Class
  summary: "Ondersteuning voor een binding-parameter die kan worden gebruikt met het HTTP-Transport om op te geven van de instelling voor HttpMessage."
  syntax:
    content: 'public sealed class HttpMessageSettings : IEquatable<System.ServiceModel.Channels.HttpMessageSettings>'
  inheritance:
  - System.Object
  implements:
  - System.IEquatable<System.ServiceModel.Channels.HttpMessageSettings>
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Channels.HttpMessageSettings&quot;> </xref> klasse."
  syntax:
    content: public HttpMessageSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  id: Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Hiermee wordt bepaald of het opgegeven Object gelijk aan het huidige Object is."
  syntax:
    content: public bool Equals (System.ServiceModel.Channels.HttpMessageSettings other);
    parameters:
    - id: other
      type: System.ServiceModel.Channels.HttpMessageSettings
      description: "Het object dat moet worden vergeleken met het huidige object."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het opgegeven Object gelijk aan het huidige Object is. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  id: HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of het HTTP-transport moet ondersteunen <xref href=&quot;System.Net.Http.HttpRequestMessage&quot;> </xref> en <xref href=&quot;System.Net.Http.HttpResponseMessage&quot;> </xref> exemplaren."
  syntax:
    content: public bool HttpMessagesSupported { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de HTTP-transport ondersteunt <xref href=&quot;System.Net.Http.HttpRequestMessage&quot;> </xref> en <xref href=&quot;System.Net.Http.HttpResponseMessage&quot;> </xref> exemplaren; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.HttpMessageSettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals
  nameWithType: HttpMessageSettings.Equals
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
