### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FcnMode
  id: FcnMode
  children:
  - System.Web.Configuration.FcnMode.Default
  - System.Web.Configuration.FcnMode.Disabled
  - System.Web.Configuration.FcnMode.NotSet
  - System.Web.Configuration.FcnMode.Single
  langs:
  - csharp
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
  type: Enum
  summary: "Hiermee geeft u het gedrag voor wijzigingsmelding bestand (FCN) in de toepassing."
  syntax:
    content: public enum FcnMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Default
  id: Default
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Voor elke submap zijn en maakt de toepassing een object dat wordt bewaakt de submap. Dit is de standaardinstelling."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.FcnMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Disabled
  id: Disabled
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Wijzigingsmelding bestand is uitgeschakeld."
  syntax:
    content: Disabled
    return:
      type: System.Web.Configuration.FcnMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.NotSet
  id: NotSet
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Wijzigingsmelding bestand niet is ingesteld, zodat de toepassing maakt een object dat wordt bewaakt elke submap. Dit is de standaardinstelling."
  syntax:
    content: NotSet
    return:
      type: System.Web.Configuration.FcnMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Single
  id: Single
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De toepassing wordt een object voor het controleren van de hoofdmap gemaakt en dit object gebruikt voor het bewaken van elke submap."
  syntax:
    content: Single
    return:
      type: System.Web.Configuration.FcnMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FcnMode.Default
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
- uid: System.Web.Configuration.FcnMode
  parent: System.Web.Configuration
  isExternal: false
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
- uid: System.Web.Configuration.FcnMode.Disabled
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
- uid: System.Web.Configuration.FcnMode.NotSet
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
- uid: System.Web.Configuration.FcnMode.Single
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
