### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComUdtElement
  id: ComUdtElement
  children:
  - System.ServiceModel.Configuration.ComUdtElement.#ctor
  - System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComUdtElement.Name
  - System.ServiceModel.Configuration.ComUdtElement.Properties
  - System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  langs:
  - csharp
  name: ComUdtElement
  nameWithType: ComUdtElement
  fullName: System.ServiceModel.Configuration.ComUdtElement
  type: Class
  summary: "Hiermee geeft u een gebruiker gedefinieerd Type (UDT) die moet worden opgenomen in het servicecontract. Deze klasse kan niet worden overgenomen."
  remarks: "De COM + integration runtime maakt services door het inspecteren van de typebibliotheek. Wanneer een COM +-onderdeel methoden die doorgeven bevat een `VARIANT`, de werkelijke typen moeten worden doorgegeven voordat runtime kan niet worden bepaald. Daarom wanneer u probeert om door te geven van een gebruiker gedefinieerd Type (UDT) binnen een `VARIANT`, omdat het is niet een bekend type voor serialisatie is mislukt.       Om dit probleem omzeilen, kunt u de UDT&quot;s toevoegen aan het configuratiebestand zodat ze opgenomen als bekende typen op de juiste servicecontract worden kunnen. U hebt dit doet, unieke identificatie van de UDT en de contract(en), dat wil zeggen, de oorspronkelijke COM interface (s) die wordt gebruikt.       Het volgende voorbeeld toont toe te voegen twee specifieke UDT&quot;s naar de `userDefinedTypes`> gedeelte van het configuratiebestand voor dit doel.       [!code-cs[XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] de kenmerken van de `userDefinedType`> element zijn als volgt gedefinieerd:- `typeName`: een optionele kenmerk dat de leesbare naam bevat. Dit wordt niet gebruikt door de runtime, maar u helpt een lezer te onderscheiden van de typen.      - `typeLibID`: een GUID-tekenreeks waarmee het geregistreerde type-bibliotheek die u het type definieert.      - `typeLibVersion`: een tekenreeks waarmee de versie van de type-bibliotheek die het type definieert.      - `typeDefID`: een GUID-tekenreeks waarmee het specifieke type UDT binnen het geregistreerde type-bibliotheek.       Wanneer de service is geïnitialiseerd, wordt de COM + integration runtime Hiermee zoekt u de opgegeven typen en voegt deze toe aan de verzameling bekende typen voor de opgegeven contracten."
  example:
  - "The following example demonstrates adding two specific UDTs to the <`userDefinedTypes`> section of the configuration file for this purpose.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: 'public sealed class ComUdtElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klasse."
  syntax:
    content: public ComUdtElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klasse met de opgegeven GUID-tekenreeks."
  syntax:
    content: public ComUdtElement (string typeDefID);
    parameters:
    - id: typeDefID
      type: System.String
      description: "Een GUID-tekenreeks waarmee het specifieke type UDT binnen het geregistreerde type-bibliotheek."
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van de leesbare typenaam."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "De naam leesbare."
  overload: System.ServiceModel.Configuration.ComUdtElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.ComUdtElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  id: TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van een GUID-tekenreeks waarmee het specifieke type UDT binnen het geregistreerde type-bibliotheek."
  syntax:
    content: public string TypeDefID { get; set; }
    return:
      type: System.String
      description: "Het specifieke UDT-type in het geregistreerde type-bibliotheek."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  id: TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van een GUID-tekenreeks die het geregistreerde type-bibliotheek die u het type definieert aanduidt."
  syntax:
    content: public string TypeLibID { get; set; }
    return:
      type: System.String
      description: "De geregistreerde typebibliotheek die het type definieert."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  id: TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van een tekenreeks met de versie van de type-bibliotheek die het type definieert identificatie."
  syntax:
    content: public string TypeLibVersion { get; set; }
    return:
      type: System.String
      description: "De versie van de type-bibliotheek die het type definieert."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement
  nameWithType: ComUdtElement.ComUdtElement
- uid: System.ServiceModel.Configuration.ComUdtElement.Name*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
