### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die verantwoordelijk is voor de <xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;> </xref> gebeurtenis van een <xref href=&quot;System.Drawing.Printing.PrintDocument&quot;> </xref>."
  remarks: "Wanneer u een gemachtigde QueryPageSettingsEventHandler maakt, kunt u de methode waarmee de gebeurtenis wordt afgehandeld identificeren. Toevoegen om te koppelen van de gebeurtenis met gebeurtenis-handler, een exemplaar van de gemachtigde aan de gebeurtenis. De gebeurtenis-handler wordt aangeroepen wanneer de gebeurtenis plaatsvindt, tenzij u de gemachtigde verwijdert. Zie voor meer informatie over de gebeurtenis-handler gemachtigden [gebeurtenissen](~/add/includes/ajax-current-ext-md.md).       Zie voor meer informatie over afdrukken de <xref:System.Drawing.Printing>overzicht van de naamruimte.</xref:System.Drawing.Printing>"
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
