### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  id: MsmqIntegrationSecurity
  children:
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  type: Class
  summary: "De klasse MsmqIntegrationSecurity kapselt de beveiligingsinstellingen voor transport voor het integratiekanaal Message Queuing (MSMQ)."
  remarks: "De Message Queuing-integratiekanaal kan [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] toepassingen om te communiceren met de bestaande Message Queuing-toepassingen."
  syntax:
    content: public sealed class MsmqIntegrationSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Initialiseert een nieuw exemplaar van <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity&quot;> </xref>."
  syntax:
    content: public MsmqIntegrationSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  id: Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> dat is gekoppeld aan het integratiekanaal Message Queuing (MSMQ)-."
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>is een opsomming met de volgende waarden: <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>en <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> De standaardwaarde is <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "De <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> dat is gekoppeld aan de integratie van Message Queuing-kanaal."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  id: Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Haalt de <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> dat is gekoppeld aan het integratiekanaal Message Queuing (MSMQ)-."
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>de beveiligingsinstellingen voor de integratie van Message Queuing-transport ingekapseld.</xref:System.ServiceModel.MsmqTransportSecurity> De instellingen zijn hetzelfde voor de Message Queuing-integratie en in de wachtrij transporten. <xref:System.ServiceModel.MsmqTransportSecurity>Hiermee kunt u de verificatiemodus, versleutelingsalgoritme, Secure Hash Algorithm en beveiligingsniveau ingesteld.</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "De <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> dat is gekoppeld aan de integratie van Message Queuing-kanaal."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
