### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die wordt afgehandeld tijdens de <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> gebeurtenis."
  remarks: "De <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>gebeurtenis treedt op wanneer de instellingen van een provider worden opgehaald.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> Deze gebeurtenis treedt eenmaal voor elke provider."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
