### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderCollection
  id: SettingsProviderCollection
  children:
  - System.Configuration.SettingsProviderCollection.#ctor
  - System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.SettingsProviderCollection.Item(System.String)
  langs:
  - csharp
  name: SettingsProviderCollection
  nameWithType: SettingsProviderCollection
  fullName: System.Configuration.SettingsProviderCollection
  type: Class
  summary: "Vertegenwoordigt een verzameling instellingen voor providers van toepassing."
  remarks: "De klasse SettingsProviderCollection is een eenvoudige uitbreiding van de <xref:System.Configuration.Provider.ProviderCollection>klasse om te bieden voor de opslag van <xref:System.Configuration.SettingsProvider>objecten.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderCollection>       De <xref:System.Configuration.ApplicationSettingsBase>klasse maakt gebruik van deze verzameling voor het beheren van de providers voor instellingen die zijn gekoppeld aan elk van de eigenschappen van de toepassing-instellingen via de <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> </xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: 'public class SettingsProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: SettingsProviderCollection()
  nameWithType: SettingsProviderCollection.SettingsProviderCollection()
  fullName: System.Configuration.SettingsProviderCollection.SettingsProviderCollection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsProviderCollection&quot;> </xref> klasse."
  remarks: "Dit is de standaard-constructor die impliciet wordt geleverd."
  syntax:
    content: public SettingsProviderCollection ();
    parameters: []
  overload: System.Configuration.SettingsProviderCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: SettingsProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.SettingsProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Een nieuwe instellingen provider toegevoegd aan de verzameling."
  remarks: "De <xref:System.Configuration.Provider.ProviderBase.Name%2A>eigenschap van de <xref:System.Configuration.SettingsProvider>wordt gebruikt als de opslagsleutel.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderBase.Name%2A>      > [!CAUTION] > Hoewel de Add-methode één heeft <xref:System.Configuration.Provider.ProviderBase>parameter overeenkomen met de handtekening van dezelfde methode in de basisklasse <xref:System.Configuration.Provider.ProviderCollection>, deze methode Veroorzaak een uitzondering als de `provider` parameter is niet van het type <xref:System.Configuration.SettingsProvider>.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderCollection> </xref:System.Configuration.Provider.ProviderBase>"
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "Een <xref href=&quot;System.Configuration.Provider.ProviderBase&quot;> </xref> om toe te voegen aan de verzameling."
  overload: System.Configuration.SettingsProviderCollection.Add*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "De <code> provider </code> parameter is niet van het type <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref>.       - of - de <> </> *> eigenschap van de providerparameter is null of een lege tekenreeks.       - of - instellingen voor provider met dezelfde <> </> *> bestaat al in de verzameling."
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "De verzameling is alleen-lezen."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>provider</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: SettingsProviderCollection.Item(String)
  fullName: System.Configuration.SettingsProviderCollection.Item(String)
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt de provider van instellingen in de verzameling die overeenkomt met de opgegeven naam."
  remarks: "Kunt u een <xref:System.Configuration.SettingsProviderCollection>alleen-lezen met behulp van de <xref:System.Configuration.Provider.ProviderCollection.SetReadOnly%2A>methode.</xref:System.Configuration.Provider.ProviderCollection.SetReadOnly%2A> </xref:System.Configuration.SettingsProviderCollection> Het is echter ongeldig methoden zoals <xref:System.Configuration.SettingsProviderCollection.Add%2A>, <xref:System.Configuration.Provider.ProviderCollection.Remove%2A>, en <xref:System.Configuration.Provider.ProviderCollection.Clear%2A>voor deze verzameling.</xref:System.Configuration.Provider.ProviderCollection.Clear%2A> </xref:System.Configuration.Provider.ProviderCollection.Remove%2A> </xref:System.Configuration.SettingsProviderCollection.Add%2A>"
  syntax:
    content: public System.Configuration.SettingsProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "Een <xref:System.String>met de beschrijvende naam van de provider van instellingen.</xref:System.String>"
    return:
      type: System.Configuration.SettingsProvider
      description: "Als gevonden, de <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> waarvan de naam overeenkomt met die opgegeven door de parameter name; anders <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingsProviderCollection.Item*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>name</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "De verzameling is alleen-lezen wanneer u deze waarde instelt."
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.SettingsProviderCollection.#ctor
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: SettingsProviderCollection()
  nameWithType: SettingsProviderCollection.SettingsProviderCollection()
  fullName: System.Configuration.SettingsProviderCollection.SettingsProviderCollection()
- uid: System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: SettingsProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.SettingsProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.SettingsProviderCollection.Item(System.String)
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: SettingsProviderCollection.Item(String)
  fullName: System.Configuration.SettingsProviderCollection.Item(String)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderCollection.#ctor*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: SettingsProviderCollection
  nameWithType: SettingsProviderCollection.SettingsProviderCollection
- uid: System.Configuration.SettingsProviderCollection.Add*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Add
  nameWithType: SettingsProviderCollection.Add
- uid: System.Configuration.SettingsProviderCollection.Item*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Item
  nameWithType: SettingsProviderCollection.Item
