### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  summary: "Hiermee wordt aangegeven dat de toepassing geen het juiste beveiligingsniveau om uit te voeren op de lokale computer."
  remarks: "Standaard [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] toepassingen vertrouwensniveau op clientcomputers die voorkomt ze bezighouden potentieel schadelijke activiteiten dat, zoals het verwijderen van gegevens van de vaste schijf of toegang tot het netwerk worden toegewezen. Een [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] toepassing machtiging uitbreiding van bevoegdheden of de implementatie van vertrouwde toepassingen kan gebruiken om aan te vragen van een hoger niveau van de vertrouwensrelatie:-machtiging verhoging vraagt de gebruiker toe te kennen van de toepassing een hoger niveau van beveiliging.      -Implementatie vertrouwde toepassing overeenkomt met de digitale handtekening van de [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] toepassing op basis van een lijst met vertrouwde uitgevers op de lokale computer.       TrustNotGrantedException wordt gegenereerd als: - de toepassing toestemming bevoegdheden gebruikt en de gebruiker weigert de aanvraag voor verhoogde vertrouwensmodus; of de toepassing gebruikt een betrouwbare implementatie van de toepassing en het digitale certificaat gebruikt voor het ondertekenen van de toepassing wordt niet vermeld als een vertrouwde uitgever op de lokale computer. Als u een update hebt geïmplementeerd naar een toepassing en de update meer machtigingen dan de vorige versie gebruikt en [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] er wordt een TrustNotGrantedException de nieuwe versie wordt niet geïnstalleerd."
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> klasse met een systeem geleverd bericht met een beschrijving van de fout."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A>eigenschap van het nieuwe exemplaar voor een systeem geleverd bericht met een beschrijving van de fout, zoals &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot; Dit bericht rekening gehouden met de huidige systeemcultuur.</xref:System.Exception.Message%2A>       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout."
  remarks: "De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.TrustNotGrantedException>.</xref:System.Deployment.Application.TrustNotGrantedException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> klasse met de geserialiseerde gegevens."
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "De contextuele informatie over de bron- of doelserver."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering. Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor*
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException.TrustNotGrantedException
