### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SiteMapSection
  id: SiteMapSection
  children:
  - System.Web.Configuration.SiteMapSection.#ctor
  - System.Web.Configuration.SiteMapSection.DefaultProvider
  - System.Web.Configuration.SiteMapSection.Enabled
  - System.Web.Configuration.SiteMapSection.Properties
  - System.Web.Configuration.SiteMapSection.Providers
  langs:
  - csharp
  name: SiteMapSection
  nameWithType: SiteMapSection
  fullName: System.Web.Configuration.SiteMapSection
  type: Class
  summary: "Hiermee definieert u configuratie-instellingen die worden gebruikt ter ondersteuning van de infrastructuur voor het configureren, opslaan en sitenavigatie rendering. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse SiteMapSection biedt een manier om programmatisch toegang en de inhoud van het configuratiebestand aanpassen `siteMap` sectie."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `siteMap` section, which can also be accessed as members of the SiteMapSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `siteMap` section.  \n  \n```  \n<system.web>  \n  <siteMap defaultProvider=\"XmlSiteMapReader\" enabled=\"true\">  \n    <providers>  \n      <clear />  \n      <add   \n        name=\"XmlSiteMapReader\"  \n        type=\"XmlSiteMapProvider, System.Web, Version=1.1.3300.0,  \n              Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\"  \n        siteMapFile=\"my.sitemap\"   \n        description=\"XmlSiteMapProvider that loads my.sitemap\"/>  \n    </providers>  \n  </siteMap>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the SiteMapSection class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_8_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#1](~/add/codesnippet/csharp/t-system.web.configurati_8_1.cs)]"
  syntax:
    content: 'public sealed class SiteMapSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: SiteMapSection()
  nameWithType: SiteMapSection.SiteMapSection()
  fullName: System.Web.Configuration.SiteMapSection.SiteMapSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.SiteMapSection&quot;> </xref> klasse met standaardinstellingen."
  remarks: "De constructor SiteMapSection is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Verkrijgen van een exemplaar van de <xref:System.Web.Configuration.SiteMapSection>klasse met behulp van de <xref:System.Configuration.Configuration.GetSection%2A>methode.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SiteMapSection>"
  syntax:
    content: public SiteMapSection ();
    parameters: []
  overload: System.Web.Configuration.SiteMapSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
  fullName: System.Web.Configuration.SiteMapSection.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de naam van de standaardprovider voor navigatie."
  remarks: "Navigatieproviders bieden een API voor navigatie-waarden in een algemene wijze bewerken. Kunt u navigatieproviders in de `providers` subsectie van het `siteMap` gedeelte van een configuratiebestand."
  example:
  - "The following code example demonstrates how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_66_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#2](~/add/codesnippet/csharp/p-system.web.configurati_66_1.cs)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "De naam van een provider in de <xref:System.Web.Configuration.SiteMapSection.Providers*>eigenschap of een <xref:System.String.Empty>veld.</xref:System.String.Empty> </xref:System.Web.Configuration.SiteMapSection.Providers*> De standaardwaarde is <xref uid=&quot;langword_csharp_&quot;AspNetXmlSiteMapProvider&quot;&quot; name=&quot;&quot;AspNetXmlSiteMapProvider&quot;&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.SiteMapSection.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Enabled
  nameWithType: SiteMapSection.Enabled
  fullName: System.Web.Configuration.SiteMapSection.Enabled
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de functie ASP.NET kaart is ingeschakeld."
  remarks: "De eigenschap Enabled retourneert een Booleaanse waarde die aangeeft of de navigatiefunctie ASP.NET tijdens runtime toegankelijk zijn of niet."
  example:
  - "The following code example demonstrates how to use the Enabled property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_360_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#3](~/add/codesnippet/csharp/p-system.web.configurati_360_1.cs)]"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de functie ASP.NET kaart is ingeschakeld; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.SiteMapSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Properties
  id: Properties
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Properties
  nameWithType: SiteMapSection.Properties
  fullName: System.Web.Configuration.SiteMapSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.SiteMapSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Providers
  id: Providers
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Providers
  nameWithType: SiteMapSection.Providers
  fullName: System.Web.Configuration.SiteMapSection.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Haalt een <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> verzameling <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> objecten."
  remarks: "Site kaart providers zijn de onderdelen die toegang tot de navigatiestructuur voor een site verlenen. Kunt u providers voor site-toewijzing in de `providers` subsectie van het `siteMap` gedeelte van een configuratiebestand.       De <xref:System.Web.Configuration.SiteMapSection.DefaultProvider%2A>Eigenschapsnamen welke provider wordt standaard gebruikt.</xref:System.Web.Configuration.SiteMapSection.DefaultProvider%2A>"
  example:
  - "The following code example demonstrates how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_273_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#4](~/add/codesnippet/csharp/p-system.web.configurati_273_1.cs)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "Een <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> die de instellingen die zijn gedefinieerd binnen providers bevat de <xref uid=&quot;langword_csharp_providers&quot; name=&quot;providers&quot; href=&quot;&quot;> </xref> subsectie van het <xref uid=&quot;langword_csharp_siteMap&quot; name=&quot;siteMap&quot; href=&quot;&quot;> </xref> gedeelte van het configuratiebestand."
  overload: System.Web.Configuration.SiteMapSection.Providers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SiteMapSection.#ctor
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: SiteMapSection()
  nameWithType: SiteMapSection.SiteMapSection()
  fullName: System.Web.Configuration.SiteMapSection.SiteMapSection()
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
  fullName: System.Web.Configuration.SiteMapSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.SiteMapSection.Enabled
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Enabled
  nameWithType: SiteMapSection.Enabled
  fullName: System.Web.Configuration.SiteMapSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.SiteMapSection.Properties
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Properties
  nameWithType: SiteMapSection.Properties
  fullName: System.Web.Configuration.SiteMapSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SiteMapSection.Providers
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Providers
  nameWithType: SiteMapSection.Providers
  fullName: System.Web.Configuration.SiteMapSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.SiteMapSection.#ctor*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: SiteMapSection
  nameWithType: SiteMapSection.SiteMapSection
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
- uid: System.Web.Configuration.SiteMapSection.Enabled*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Enabled
  nameWithType: SiteMapSection.Enabled
- uid: System.Web.Configuration.SiteMapSection.Properties*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Properties
  nameWithType: SiteMapSection.Properties
- uid: System.Web.Configuration.SiteMapSection.Providers*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Providers
  nameWithType: SiteMapSection.Providers
