### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  id: AssemblyHashAlgorithm
  children:
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  langs:
  - csharp
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
  type: Enum
  summary: "Hiermee geeft u alle hash-algoritmen die worden gebruikt voor de hash-bestanden en voor het genereren van de sterke naam."
  remarks: "Een `hash function``H` is een transformatie die een invoer `m` en retourneert een tekenreeks met vaste grootte, die de hash-waarde is aangeroepen `h` (dat wil zeggen, `h`  =  `H` (`m`)). Hash-functies met alleen deze eigenschap hebben een aantal algemene rekenkundige gebruikt, maar wanneer gebruikt cryptografie, de hash-functies zijn meestal wilt hebben een aantal aanvullende eigenschappen.       De basisvereisten voor een cryptografische hash-functie zijn:-de invoer kan zijn van een willekeurige lengte.      -De uitvoer heeft een vaste lengte.      - `H` (`x)` is betrekkelijk eenvoudig te berekenen voor een bepaalde x.      -   `H` (`x`) is one-way.      - `H` (`x`) conflicten vrij is.       De hash-waarde vertegenwoordigt bondig het langer bericht of document waaruit het is berekend; Deze waarde wordt de distributielijst genoemd. U kunt een distributielijst beschouwen als een digitale vingerafdruk van het grotere document. Voorbeelden van bekende hash-functies zijn MD2 en en SHA."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyHashAlgorithm
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  id: MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Haalt de MD5-algoritme. MD5 is ontwikkeld door Rivest 1991. Het is in feite MD4 met veiligheidsgordels en het iets langer dan MD4 is, is het handig meer beveiliging bieden. Het algoritme bestaat uit vier verschillende Rondt, die een ontwerp voor iets anders dan die van MD4 heeft. De grootte van het Message digest, evenals opvulling vereisten, blijven hetzelfde."
  syntax:
    content: MD5
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  id: None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Een masker waarmee wordt aangegeven dat er geen hash-algoritme. Als u opgeeft <xref uid=&quot;langword_csharp_None&quot; name=&quot;None&quot; href=&quot;&quot;> </xref> voor een assembly met meerdere module de common language runtime wordt standaard ingesteld op het SHA1-algoritme omdat meerdere modules assembly&quot;s moeten een hash genereren."
  syntax:
    content: None
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  id: SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Een masker dat wordt gebruikt voor het ophalen van een revisie van de Secure Hash Algorithm die een niet-gepubliceerde fout in SHA corrigeert."
  syntax:
    content: SHA1
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  id: SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Een masker dat wordt gebruikt voor het ophalen van een versie van de Secure Hash Algorithm en een hash-grootte van 256 bits."
  syntax:
    content: SHA256
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  id: SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Een masker dat wordt gebruikt voor het ophalen van een versie van de Secure Hash Algorithm met een hash-grootte van 384 bits."
  syntax:
    content: SHA384
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  id: SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Een masker dat wordt gebruikt voor het ophalen van een versie van de Secure Hash Algorithm met een hash-grootte van 512 bits."
  syntax:
    content: SHA512
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
