### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.FlowLayoutSettings
  id: FlowLayoutSettings
  children:
  - System.Windows.Forms.FlowLayoutSettings.FlowDirection
  - System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  - System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  - System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  - System.Windows.Forms.FlowLayoutSettings.WrapContents
  langs:
  - csharp
  name: FlowLayoutSettings
  nameWithType: FlowLayoutSettings
  fullName: System.Windows.Forms.FlowLayoutSettings
  type: Class
  summary: "Verzamelt de kenmerken die zijn gekoppeld aan de stroom-indelingen."
  remarks: "De klasse FlowLayoutSettings verzamelt en beheert de kenmerken die zijn gekoppeld aan het schema van de lay-out stroom. Deze klasse wordt gebruikt, intern door de <xref:System.Windows.Forms.FlowLayoutPanel>en <xref:System.Windows.Forms.ToolStrip>klassen, evenals de stroom lay-outengine.</xref:System.Windows.Forms.ToolStrip> </xref:System.Windows.Forms.FlowLayoutPanel> De klasse FlowLayoutSettings wordt gebruikt door de lay-outengine om te bepalen hoe naar lay-out van de container onderliggende besturingselementen.       De klasse FlowLayoutSettings beheert de volgende informatie:-de stroomrichting van opeenvolgende besturingselementen.      -Of de inhoud moeten ingepakt of als de onderliggende besturingselementen kunnen niet worden opgenomen in hun bovenliggende afgekapt.       FlowLayoutSettings heeft geen openbare constructor."
  syntax:
    content: >-
      [System.ComponentModel.DefaultProperty("FlowDirection")]

      public class FlowLayoutSettings : System.Windows.Forms.LayoutSettings
  inheritance:
  - System.Object
  - System.Windows.Forms.LayoutSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  id: FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Opgehaald of ingesteld van een waarde die aangeeft van de stroomrichting van opeenvolgende besturingselementen."
  remarks: "De FlowDirection is de standaardinstelling voor de eigenschap voor de <xref:System.Windows.Forms.FlowLayoutSettings>klasse.</xref:System.Windows.Forms.FlowLayoutSettings>"
  syntax:
    content: public System.Windows.Forms.FlowDirection FlowDirection { get; set; }
    return:
      type: System.Windows.Forms.FlowDirection
      description: "Een <xref href=&quot;System.Windows.Forms.FlowDirection&quot;> </xref> die wijzen op de stroomrichting van opeenvolgende besturingselementen in de container. De standaardwaarde is <xref href=&quot;System.Windows.Forms.FlowDirection&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  id: GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Retourneert een waarde die aangeeft van de stroom break-instelling van het besturingselement."
  syntax:
    content: public bool GetFlowBreak (object child);
    parameters:
    - id: child
      type: System.Object
      description: "Het onderliggende besturingselement."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>het einde van de stroom is opgegeven bij. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  id: LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hiermee haalt u de huidige stroom lay-outengine."
  remarks: "De <xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>eigenschap wordt doorgaans gebruikt in twee contexten:-een container die gebruikmaakt van een stroomindeling.</xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>      -Een besturingselement dat is opgenomen binnen een container stroom-indeling (bijvoorbeeld een knop die zijn opgenomen in een cel van een <xref:System.Windows.Forms.FlowLayoutPanel>).</xref:System.Windows.Forms.FlowLayoutPanel>"
  syntax:
    content: public override System.Windows.Forms.Layout.LayoutEngine LayoutEngine { get; }
    return:
      type: System.Windows.Forms.Layout.LayoutEngine
      description: "De <xref href=&quot;System.Windows.Forms.Layout.LayoutEngine&quot;> </xref> momenteel wordt gebruikt."
  overload: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  id: SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Retourneert de waarde voor de stroom break-instelling van het besturingselement."
  syntax:
    content: public void SetFlowBreak (object child, bool value);
    parameters:
    - id: child
      type: System.Object
      description: "Het onderliggende besturingselement."
    - id: value
      type: System.Boolean
      description: "De stroom-break-waarde in te stellen."
  overload: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  id: WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de inhoud moeten worden ingepakt of afgekapt wanneer deze groter is dan de oorspronkelijke grenzen van de container."
  remarks: "Het gebied van de container is te klein om de onderliggende besturingselementen weer te geven, wordt ten minste één besturingselement worden afgekapt ongeacht de WrapContents-waarde.       Daaropvolgende vergroten of verkleinen van de container, wordt de lay-out toepassen op de opgenomen besturingselementen."
  syntax:
    content: public bool WrapContents { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de inhoud moeten worden verpakt; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> als de inhoud moeten worden afgekapt. De standaardwaarde is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: System.Windows.Forms.LayoutSettings
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowDirection
  parent: System.Windows.Forms
  isExternal: false
  name: FlowDirection
  nameWithType: FlowDirection
  fullName: System.Windows.Forms.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.Layout.LayoutEngine
  parent: System.Windows.Forms.Layout
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutEngine
  fullName: System.Windows.Forms.Layout.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak
  nameWithType: FlowLayoutSettings.GetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak
  nameWithType: FlowLayoutSettings.SetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
