### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerHelper
  id: IConfigurationManagerHelper
  children:
  - System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  langs:
  - csharp
  name: IConfigurationManagerHelper
  nameWithType: IConfigurationManagerHelper
  fullName: System.Configuration.Internal.IConfigurationManagerHelper
  type: Interface
  summary: "Definieert een interface die door het .NET Framework wordt gebruikt ter ondersteuning van beheer van de configuratie."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerHelper
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  id: EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  langs:
  - csharp
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Zorgt ervoor dat de netwerkconfiguratie is geladen."
  remarks: "Deze methode wordt gebruikt om te voorkomen dat impassen in de netwerken klassen door ervoor te zorgen dat netwerkconfiguratie wordt geladen voordat de VPN-aanvragen worden gedaan."
  syntax:
    content: public void EnsureNetConfigLoaded ();
    parameters: []
  overload: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded
