### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationHost
  id: ApplicationHost
  children:
  - System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  langs:
  - csharp
  name: ApplicationHost
  nameWithType: ApplicationHost
  fullName: System.Web.Hosting.ApplicationHost
  type: Class
  summary: "Kan hosting van ASP.NET-pagina&quot;s buiten de Internet Information Services (IIS)-toepassing. Deze klasse kan de host om toepassingsdomeinen voor het verwerken van ASP.NET-aanvragen te maken."
  remarks: "ApplicationHost is opgenomen in de .NET Framework versie 3.5.  Zie voor meer informatie [versies en afhankelijkheden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public sealed class ApplicationHost
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  id: CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  langs:
  - csharp
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Maakt en configureert u een toepassingsdomein voor het hosten van ASP.NET."
  syntax:
    content: public static object CreateApplicationHost (Type hostType, string virtualDir, string physicalDir);
    parameters:
    - id: hostType
      type: System.Type
      description: "De naam van een gebruiker opgegeven klasse worden gemaakt in het nieuwe toepassingsdomein."
    - id: virtualDir
      type: System.String
      description: "De virtuele map voor het toepassingsdomein; bijvoorbeeld/Mijntoep."
    - id: physicalDir
      type: System.String
      description: "De fysieke map voor het toepassingsdomein waarin ASP.NET-pagina&quot;s bevinden; bijvoorbeeld: c:\\mypages."
    return:
      type: System.Object
      description: "Een exemplaar van een gebruiker opgegeven klasse die wordt gebruikt voor het marshallen van aanroepen in de zojuist gemaakte toepassingsdomein."
  overload: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  exceptions:
  - type: System.PlatformNotSupportedException
    commentId: T:System.PlatformNotSupportedException
    description: "De Web-hostcomputer wordt niet uitgevoerd voor de Windows NT-platform of een Coriolis-omgeving."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.PlatformNotSupportedException
  isExternal: true
  name: System.PlatformNotSupportedException
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost
  nameWithType: ApplicationHost.CreateApplicationHost
