### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TrustLevel
  id: TrustLevel
  children:
  - System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  - System.Web.Configuration.TrustLevel.Name
  - System.Web.Configuration.TrustLevel.PolicyFile
  - System.Web.Configuration.TrustLevel.Properties
  langs:
  - csharp
  name: TrustLevel
  nameWithType: TrustLevel
  fullName: System.Web.Configuration.TrustLevel
  type: Class
  summary: "Hiermee definieert u de toewijzing van bepaalde beveiligingsniveaus en benoemde beleidsbestanden. Deze klasse kan niet worden overgenomen."
  remarks: "U kunt de beveiliging van uw webtoepassing uitbreiden door het maken van uw eigen benoemde TrustLevel-object dat is toegewezen aan een bestand dat is opgegeven door de `policyFile` kenmerk."
  example:
  - "The following code example demonstrates how to use the TrustLevel type.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#1](~/add/codesnippet/csharp/t-system.web.configurati_38_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#1](~/add/codesnippet/visualbasic/t-system.web.configurati_38_1.vb)]"
  syntax:
    content: 'public sealed class TrustLevel : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: TrustLevel(String,String)
  nameWithType: TrustLevel.TrustLevel(String,String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Maakt een exemplaar van de <xref href=&quot;System.Web.Configuration.TrustLevel&quot;> </xref> klasse die is geïnitialiseerd op basis van de opgegeven waarden, dit is de toewijzing van bepaalde beveiligingsniveaus te definiëren met de naam beleidsbestanden."
  remarks: "De constructor TrustLevel maakt een <xref:System.Web.Configuration.TrustLevel>object met behulp van de opgegeven parameters.</xref:System.Web.Configuration.TrustLevel>"
  example:
  - "The following code example demonstrates how to use the TrustLevel constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#4](~/add/codesnippet/csharp/m-system.web.configurati_43_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#4](~/add/codesnippet/visualbasic/m-system.web.configurati_43_1.vb)]"
  syntax:
    content: public TrustLevel (string name, string policyFile);
    parameters:
    - id: name
      type: System.String
      description: "Een benoemde beveiligingsniveau dat is toegewezen aan een bestand met beleidsregel."
    - id: policyFile
      type: System.String
      description: "Het configuratiebestand dat instellingen voor beveiligingsbeleid voor het benoemde beveiligingsniveau bevat."
  overload: System.Web.Configuration.TrustLevel.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustLevel.Name
  id: Name
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een benoemde beveiligingsniveau dat is toegewezen aan een bestand met beleidsregel."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#3](~/add/codesnippet/csharp/p-system.web.configurati_0_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#3](~/add/codesnippet/visualbasic/p-system.web.configurati_0_1.vb)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "De naam die is toegewezen aan een bestand met beleidsregel."
  overload: System.Web.Configuration.TrustLevel.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  id: PolicyFile
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de configuratie van verwijzing naar een bestand met de instellingen voor beveiligingsbeleid voor het benoemde beveiligingsniveau."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the PolicyFile property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#5](~/add/codesnippet/csharp/p-system.web.configurati_352_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#5](~/add/codesnippet/visualbasic/p-system.web.configurati_352_1.vb)]"
  syntax:
    content: public string PolicyFile { get; set; }
    return:
      type: System.String
      description: "De verwijzing van de configuratie-bestand met de instellingen voor beveiligingsbeleid voor het bijbehorende beveiligingsniveau."
  overload: System.Web.Configuration.TrustLevel.PolicyFile*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustLevel.Properties
  id: Properties
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.TrustLevel.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel(String,String)
  nameWithType: TrustLevel.TrustLevel(String,String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TrustLevel.Name
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
- uid: System.Web.Configuration.TrustLevel.Properties
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TrustLevel.#ctor*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel
  nameWithType: TrustLevel.TrustLevel
- uid: System.Web.Configuration.TrustLevel.Name*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
- uid: System.Web.Configuration.TrustLevel.PolicyFile*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
- uid: System.Web.Configuration.TrustLevel.Properties*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
