### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  id: CheckForUpdateCompletedEventArgs
  children:
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  langs:
  - csharp
  name: CheckForUpdateCompletedEventArgs
  nameWithType: CheckForUpdateCompletedEventArgs
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  type: Class
  summary: "Geeft gedetailleerde informatie over via een aanroep van <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*> verkregen"
  remarks: "Met CheckForUpdateCompletedEventArgs, kunt u beslissen of uw ClickOnce-toepassing op basis van informatie over de nieuwste versie te upgraden. <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A>retourneert een Booleaanse waarde die aangeeft of er een nieuwe update helemaal.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> De <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A>eigenschap bevat het versienummer van de nieuwe versie, terwijl <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A>biedt de oudste versie die de gebruiker moet op de computer geïnstalleerd.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A> <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A>Geeft aan of de nieuwste update van de gebruiker vereist is.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> Ten slotte <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>de totale grootte van de update wordt uitgedrukt.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>"
  example:
  - "The following code example uses <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/t-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: 'public class CheckForUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u het versienummer van de laatste niet-geïnstalleerde versie."
  remarks: "U kunt AvailableVersion gebruiken om te bepalen of de update op basis van de ernst van de update te installeren. Bijvoorbeeld, als alleen de <xref:System.Version.Build%2A>of <xref:System.Version.Revision%2A>versie-eigenschappen zijn gewijzigd, uw toepassing mogelijk niet nodig om bij te werken totdat de <xref:System.Version.Minor%2A>of <xref:System.Version.Major%2A>Eigenschappen wijzigen.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "De <xref:System.Version>uitdrukken van de primaire, secundaire, build en revisie cijfers van de meest recente versie.</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Haalt een waarde die aangeeft of de update moet worden geïnstalleerd."
  remarks: "Als u een update op de ClickOnce-toepassing implementeert, kunt u markeren als de vereiste update-signalering voor uw toepassing onmiddellijk moet bijwerken. Wilt u de update te markeren als de meest recente versie bevat een essentiële update, of als het is niet compatibel met bestandsindelingen of back-end-gegevensbronnen die worden gebruikt door de vorige versie."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/2aa4f4df-e487-4c83-87b0-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de update vereist is. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u de minimumversie die de gebruiker moet op de computer geïnstalleerd."
  remarks: "Toepassingen kunnen vereiste updates gemist, wanneer een gebruiker de toewijzing van een speciale krijgt of niet op de computer voor weken of maanden is. Gebruik MinimumRequiredVersion om te bepalen als de gebruiker de toepassing een tijdje niet bijgewerkt en een of meer vereiste updates ontbreekt."
  example:
  - "The following code example calls <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync%2A>, and forces an application update if MinimumRequiredVersion is greater than <xref:System.Deployment.Application.ApplicationDeployment.CurrentVersion%2A>.  \n  \n [!code-cs[ClickOnceAPI#10](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#10)]\n [!code-vb[ClickOnceAPI#10](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#10)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "Een <xref:System.Version>object uitdrukken van de oudste versie die alle gebruikers moeten installeren.</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee wordt opgehaald of een niet-geïnstalleerde update beschikbaar is."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether or not there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/847038a4-fd95-4e16-a133-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>indien nieuwe versie van de toepassing beschikbaar is. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u de grootte van de update beschikbaar."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "Een <xref:System.Int64>met een beschrijving van de grootte, in bytes van de update beschikbaar.</xref:System.Int64> Als er geen update beschikbaar is, 0 geretourneerd."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
