### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SerializationMode
  id: SerializationMode
  children:
  - System.Web.Configuration.SerializationMode.Binary
  - System.Web.Configuration.SerializationMode.ProviderSpecific
  - System.Web.Configuration.SerializationMode.String
  - System.Web.Configuration.SerializationMode.Xml
  langs:
  - csharp
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
  type: Enum
  summary: "Bepaalt de serialisatiemethode gebruikt voor een <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> object."
  remarks: "De <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>eigenschap van de <xref:System.Web.Configuration.ProfilePropertySettings>object bepaalt de serialisatiemodus voor de instelling van een profiel voor één eigenschap.</xref:System.Web.Configuration.ProfilePropertySettings> </xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/csharp/t-system.web.configurati_92_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_92_1.vb)]"
  syntax:
    content: public enum SerializationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Binary
  id: Binary
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> object wordt geserialiseerd met de binaire serialisatie."
  syntax:
    content: Binary
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  id: ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De provider impliciete kennis van het type en is verantwoordelijk voor het bepalen hoe u voor het serialiseren van de <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> object in het gegevensarchief."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.String
  id: String
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> object wordt geserialiseerd naar een eenvoudige tekenreeks."
  syntax:
    content: String
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Xml
  id: Xml
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Het profiel <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> wordt geserialiseerd als XML met XML-serialisatie."
  syntax:
    content: Xml
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.SerializationMode.Binary
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
- uid: System.Web.Configuration.SerializationMode
  parent: System.Web.Configuration
  isExternal: false
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
- uid: System.Web.Configuration.SerializationMode.String
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
- uid: System.Web.Configuration.SerializationMode.Xml
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
