### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BuildProvider
  id: BuildProvider
  children:
  - System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.BuildProvider.Equals(System.Object)
  - System.Web.Configuration.BuildProvider.Extension
  - System.Web.Configuration.BuildProvider.GetHashCode
  - System.Web.Configuration.BuildProvider.Properties
  - System.Web.Configuration.BuildProvider.Type
  langs:
  - csharp
  name: BuildProvider
  nameWithType: BuildProvider
  fullName: System.Web.Configuration.BuildProvider
  type: Class
  summary: "Biedt functionaliteit om een bepaald bestandstype parseren en code genereren tijdens de compilatie van een dynamische bron. Deze klasse kan niet worden overgenomen."
  syntax:
    content: 'public sealed class BuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Maakt een exemplaar van een <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> klasse is geïnitialiseerd voor de opgegeven waarden."
  syntax:
    content: public BuildProvider (string extension, string type);
    parameters:
    - id: extension
      type: System.String
      description: "De bestandsextensie van de dynamische resource gebruikt tijdens de compilatie."
    - id: type
      type: System.String
      description: "Het type dat vertegenwoordigt de <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> exemplaar moet worden gebruikt bij het parseren en het compileren van de opgegeven extensie."
  overload: System.Web.Configuration.BuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee wordt bepaald of het object van de opgegeven build-provider gelijk aan het huidige object is."
  remarks: "De serialisatiefunctie maakt gebruik van deze methode om te bepalen of hetzelfde object al in de bovenliggende verzameling en of deze moeten op een lager niveau worden geserialiseerd bestaat als deze niet is overgenomen."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Het build-provider-object om te vergelijken met het huidige object."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de objecten gelijk zijn. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Extension
  id: Extension
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de bestandsextensie om toe te wijzen tijdens de compilatie van een dynamische bron."
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "Een tekenreeks opgeven van de bestandsextensie om toe te wijzen tijdens de compilatie van een dynamische bron."
  overload: System.Web.Configuration.BuildProvider.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De hash-code genereert voor de build-provider."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Een geheel getal dat de hash-code voor de build-provider."
  overload: System.Web.Configuration.BuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.BuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Type
  id: Type
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de door komma&quot;s gescheiden klasse assembly combinatie en die aangeeft de <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> exemplaar te gebruiken."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Een door komma&quot;s gescheiden klasse assembly combinatie en die aangeeft de <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> exemplaar te gebruiken."
  overload: System.Web.Configuration.BuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.BuildProvider.Extension
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.BuildProvider.Properties
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.BuildProvider.Type
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
- uid: System.Web.Configuration.BuildProvider.#ctor*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider
  nameWithType: BuildProvider.BuildProvider
- uid: System.Web.Configuration.BuildProvider.Equals*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals
  nameWithType: BuildProvider.Equals
- uid: System.Web.Configuration.BuildProvider.Extension*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: BuildProvider.GetHashCode
- uid: System.Web.Configuration.BuildProvider.Properties*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
- uid: System.Web.Configuration.BuildProvider.Type*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
