### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyIsReadOnlyException
  id: SettingsPropertyIsReadOnlyException
  children:
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException
  type: Class
  summary: "Biedt een uitzondering voor alleen-lezen <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> objecten."
  remarks: "Deze uitzondering wordt gegenereerd door de <xref:System.Configuration.SettingsBase>klasse bij een poging tot het wijzigen van de waarde van een <xref:System.Configuration.SettingsPropertyValue>die is gemarkeerd als alleen-lezen.</xref:System.Configuration.SettingsPropertyValue> </xref:System.Configuration.SettingsBase>"
  syntax:
    content: 'public class SettingsPropertyIsReadOnlyException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasse."
  syntax:
    content: public SettingsPropertyIsReadOnlyException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasse op basis van een opgegeven parameter."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Een tekenreeks met een uitzonderingsbericht."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: protected SettingsPropertyIsReadOnlyException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "De <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> -object met de geserialiseerde objectgegevens over de uitzondering."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "De <xref:System.Runtime.Serialization.StreamingContext>object dat contextuele informatie over de bron of bestemming van de geserialiseerde stroom bevat.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Een tekenreeks met een uitzonderingsbericht."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException
