### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Biedt ondersteuning voor runtime-versies 1.0 en 1.1 voor het lezen van de configuratiesecties en algemene configuratie-instellingen."
  remarks: "Met behulp van de statische methoden en eigenschappen van het type ConfigurationSettings is de aanbevolen methode voor het lezen van configuratiegegevens tijdens runtime voor de versies 1.0 en 1.1-toepassingen.      > [!NOTE] > De ConfigurationSettings klasse biedt alleen achterwaartse compatibiliteit. Voor nieuwe toepassingen moet u de <xref:System.Configuration.ConfigurationManager>klasse of <xref:System.Web.Configuration.WebConfigurationManager>in plaats daarvan klasse.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> Voor het gebruik van deze twee klassen, moet u een verwijzing toevoegen in uw project of toepassing naar de System.Configuration-naamruimte."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Haalt een alleen-lezen <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> van het toepassingsgedeelte van de instellingen van het configuratiebestand."
  remarks: "De `appSettings` sectie-element van het configuratiebestand bevat een reeks naam/waarde-paren die uw toepassing voor enig doel gebruiken kunt.       Deze methode is afgeschaft en blijft behouden voor achterwaartse compatibiliteit. Gebruik in plaats daarvan de methode GetSection.      > [!NOTE] > De <xref:System.Configuration.ConfigurationSettings>klasse biedt alleen achterwaartse compatibiliteit.</xref:System.Configuration.ConfigurationSettings> Moet u de <xref:System.Configuration.ConfigurationManager>klasse of <xref:System.Web.Configuration.WebConfigurationManager>in plaats daarvan klasse.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "Een alleen-lezen <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> van de sectie instellingen voor de toepassing uit het configuratiebestand."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Retourneert de <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> -object voor de configuratie van doorgegeven sectienaam en pad."
  remarks: "Deze methode is afgeschaft en blijft behouden voor achterwaartse compatibiliteit. Gebruik in plaats daarvan de methode GetSection."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Een naam van de configuratie en het pad, bijvoorbeeld &quot;system.net/settings&quot;."
    return:
      type: System.Object
      description: "De <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> -object voor de configuratie van doorgegeven sectienaam en pad.       <div class=&quot;alert NOTE&quot;>    De <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> klasse biedt alleen achterwaartse compatibiliteit. Moet u de <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> klasse of <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> klasse in plaats daarvan.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Kan de aangevraagde sectie ophalen."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
