### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  id: StateElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  langs:
  - csharp
  name: StateElement
  nameWithType: StateElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  type: Class
  summary: "Een configuratie-element waarmee de status van de werkstroom-exemplaar of de gebruiker de status van activiteit exemplaar is lid van traceringsgegevens voor."
  remarks: "Dit element wordt geplaatst in een <xref:System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection>binnen een <xref:System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement>om op te geven van de activiteit bepaalt de query moeten filter op de.</xref:System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement> </xref:System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection>"
  syntax:
    content: 'public class StateElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.StateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.StateElement&quot;> </xref> klasse."
  syntax:
    content: public StateElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Hiermee haalt u een sleutel die een unieke identificatie van de query element."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "De elementsleutel."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Name
  nameWithType: StateElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Statusnaam opgehaald of ingesteld de kunt u filteren op."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "De statusnaam kunt u filteren op. De standaardwaarde is &quot;*&quot; (alle)."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Properties
  nameWithType: StateElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Hiermee wordt een verzameling <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> eigenschappen."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Een verzameling van configuratie-eigenschappen."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.StateElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement
  nameWithType: StateElement.StateElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
