### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpConfigurationContext
  id: HttpConfigurationContext
  children:
  - System.Web.Configuration.HttpConfigurationContext.VirtualPath
  langs:
  - csharp
  name: HttpConfigurationContext
  nameWithType: HttpConfigurationContext
  fullName: System.Web.Configuration.HttpConfigurationContext
  type: Class
  summary: "Levert de huidige contextinformatie aan configuratiesectie handlers in ASP.NET-toepassingen."
  remarks: "De contextinformatie is die door deze klasse voor de huidige HTTP-aanvraag."
  syntax:
    content: public class HttpConfigurationContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  id: VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  langs:
  - csharp
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee haalt u het virtuele pad naar het Web.config-configuratiebestand."
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "Het virtuele pad naar het bestand Web.config. <xref uid=&quot;langword_csharp_Null&quot; name=&quot;Null&quot; href=&quot;&quot;></xref>bij het evalueren van Machine.config; een lege tekenreeks (&quot;&quot;) bij het evalueren van het bestand Web.config voor de site."
  overload: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
