### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  id: BrowserCapabilitiesCodeGenerator
  children:
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  type: Class
  summary: "De klasse BrowserCapabilitiesCodeGenerator door intern wordt gebruikt de <xref uid=&quot;langword_csharp_aspnet_regbrowsers&quot; name=&quot;aspnet_regbrowsers&quot; href=&quot;&quot;> </xref> hulpprogramma .browser browser definitiebestanden parseren en browsers toevoegen aan de runtime-verzameling van bekende browsers die zijn opgenomen in de <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;> </xref> object."
  remarks: "Deze klasse genereert de broncode voor een assembly voor de <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klasse, die tijdens runtime, die de aanvraag-specifieke <xref:System.Web.Configuration.HttpCapabilitiesBase>objecten openbaar toegankelijk via de ingebouwde ASP.NET `Request.Browser` eigenschap.</xref:System.Web.Configuration.HttpCapabilitiesBase> </xref:System.Web.Configuration.BrowserCapabilitiesFactory>"
  syntax:
    content: public class BrowserCapabilitiesCodeGenerator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Intern gebruikt voor het maken van een nieuw exemplaar van <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;> </xref>."
  syntax:
    content: public BrowserCapabilitiesCodeGenerator ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  id: Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Intern gebruikt voor het coördineren van het gedrag van deze klasse."
  remarks: "Deze methode doorlopen eerst naar de map &quot;Browsers&quot;. Vervolgens roept <xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A>, die wordt geladen en parseert de XML in een verzameling van browserdefinitie bestanden en voegt de informatie die hierin staan in een interne verzameling browsers.</xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A> Vervolgens wordt een interne methode die de bron-code wordt gecompileerd genereert aangeroepen en registreert als een assembly in de global assembly cache om de <xref:System.Web.Configuration.BrowserCapabilitiesFactory>object.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Indien nodig, zijn deze methode roept vervolgens een interne methode die de webserver opnieuw wordt opgestart."
  syntax:
    content: public virtual void Create ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  id: ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Wordt geladen en parseert de XML in een verzameling browserdefinitie bestanden en voegt de informatie in een interne verzameling browsers daarin."
  syntax:
    content: protected void ProcessBrowserFiles (bool useVirtualPath, string virtualDir);
    parameters:
    - id: useVirtualPath
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>gebruik van een virtueel pad zijn. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: virtualDir
      type: System.String
      description: "Het pad naar de virtuele map met de definitie van de browser-bestanden. De standaardwaarde is <xref:System.String>.</xref:System.String>"
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  exceptions:
  - type: System.Web.HttpParseException
    commentId: T:System.Web.HttpParseException
    description: "One of the browser-definition files does not have a root element named \"browsers\".  \n  \n \\- or -  \n  \n One of the browser-definition files fails to load."
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  id: Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee verwijdert u de browser mogelijkheden factory uit de global assemblycache en wordt verwijderd van de sterke naam token bestand met openbare sleutel."
  remarks: "Deze methode wordt opnieuw gestart met de webservice. De browser mogelijkheden factory vervolgens wordt verwijderd uit de global assemblycache en de sterke naam public key token bestand wordt verwijderd. De webservice wordt vervolgens opnieuw worden gestart als de verwijdering is gelukt."
  syntax:
    content: public bool Uninstall ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de browser mogelijkheden factory is verwijderd uit de global assemblycache; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.HttpParseException
  parent: System.Web
  isExternal: false
  name: HttpParseException
  nameWithType: HttpParseException
  fullName: System.Web.HttpParseException
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create
  nameWithType: BrowserCapabilitiesCodeGenerator.Create
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall
