### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlReaderSettings
  id: XamlReaderSettings
  children:
  - System.Xaml.XamlReaderSettings.#ctor
  - System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  langs:
  - csharp
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
  type: Class
  summary: "Hiermee geeft u het verwerken van regels of de optie-instellingen voor een <xref href=&quot;System.Xaml.XamlReader&quot;> </xref> implementatie."
  remarks: "Een geïnitialiseerd XamlReaderSettings object gebruikt standaard waarden voor de eigenschappen die met overeenkomen standaardinstellingen, zoals verwacht `false` voor Boole-eigenschappen of null-waarden voor de eigenschappen van het type verwijzing. De initialisatie van de standaard resulteert in de volgende waarden: - de <xref:System.Xaml.XamlReaderSettings.BaseUri%2A>en <xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A>Eigenschappen zijn `null`.</xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A> </xref:System.Xaml.XamlReaderSettings.BaseUri%2A>      -De <xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>eigenschap is `false`.</xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>      -De <xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>eigenschap is `false` in het objectmodel; echter, kan worden ingesteld op `true` tijdens runtime op basis van het geladen uitvoerbare bestanden en hun instellingen voor foutopsporing of door de XAML-schemacontext.</xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>"
  syntax:
    content: public class XamlReaderSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> klasse."
  remarks: "Voor meer informatie over de initialisatie van een <xref:System.Xaml.XamlReaderSettings>standaard exemplaar, Zie <xref:System.Xaml.XamlReaderSettings>.</xref:System.Xaml.XamlReaderSettings> </xref:System.Xaml.XamlReaderSettings>"
  syntax:
    content: public XamlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  id: '#ctor(System.Xaml.XamlReaderSettings)'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> klasse op basis van waarden in een andere <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> object."
  remarks: "Deze constructor biedt ondersteuning voor het samenvoegen van instellingen voor XAML lezers waar extra instellingen ook afkomstig uit andere deelnemers aan de lezer zijn kunnen."
  syntax:
    content: public XamlReaderSettings (System.Xaml.XamlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlReaderSettings
      description: "Een bestaande <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> object."
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  id: AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of het hoofdobject leden waarvoor een model van de toegang tot beveiligde code wordt de weergave van het XAML-type kan bevatten."
  remarks: "Deze instelling is relevant zijn voor sommige implementaties XAML zoals WPF waarbij het hoofdobject vaak een &quot;factory is&quot; voor het genereren van een exemplaar van een patroontype wanneer dat patroontype niet altijd een praktische objectexemplaar is. Bijvoorbeeld, een toegangspunt van `UserControl` heeft een bepaalde betekenis voor WPF en Silverlight-toepassing-modellen en `UserControl` mogelijk beveiligd eigenschappen (`UserControl.Content`) dat de parser toegang tot heeft. Hulpprogramma&quot;s en ontwerp verwerkingsinformatie moeten ook toegang tot dergelijke eigenschappen. Dergelijke gevallen moeten in het algemeen worden gerapporteerd aan het XAML-typesysteem als schrijfbare eigenschappen zelfs als ze toegang hebben beveiligd in het typesysteem back-ups maken."
  syntax:
    content: public bool AllowProtectedMembersOnRoot { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het hoofdobject leden kan bevatten die een code voor beveiligde toegangsmodel hebben; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.BaseUri
  id: BaseUri
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van de basis-URI die wordt gebruikt voor het omzetten van relatieve paden."
  remarks: "Bepaalde URI-eigenschappen in de .NET Framework XAML Services API behandelen URI&quot;s voor XAML naamruimten als tekenreeksen; Deze eigenschap wordt echter de true <xref:System.Uri>type.</xref:System.Uri>"
  syntax:
    content: public Uri BaseUri { get; set; }
    return:
      type: System.Uri
      description: "De basis-URI te gebruiken. De standaardwaarde is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.BaseUri*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  id: IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of waarden voor moet worden genegeerd door de XAML-lezer <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> kenmerken die bestaan op eigenschapselementen."
  remarks: "Tijdens de lokalisatie, de `x:Uid` kenmerk wordt gebruikt voor het identificeren van elementen in de opmaak zodat lokalisatie extra XAML elementen als afzonderlijke entiteiten voor lokalisatie kunnen verwerken. Kenmerken worden meestal niet weergegeven in eigenschapselementen in XAML. Echter, `x:Uid` is een uitzondering omdat sommige gebruik gelokaliseerde tekst in een eigenschapselement als inhoud, plaatsen in plaats van als een afzonderlijke object dat kan ontvangen een eigen `x:Uid`. Als u een waarde IgnoreUidsOnPropertyElements op `true` kunnen een strenger modus. De standaardwaarde van `false` doorgaat met het verwerken van eigenschapselement `x:Uid` kenmerken."
  syntax:
    content: public bool IgnoreUidsOnPropertyElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de lezer moet waarden voor negeert <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> kenmerken in eigenschapselementen. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Als de lezer moet verwerken <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> kenmerken in eigenschapselementen. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  id: LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van het object waarmee de huidige lokale assembly voor verwerking. Deze Assemblyinformatie wordt gebruikt voor het aanroepen van helper API&quot;s, zoals &lt;xref:System.Xaml.XamlType.GetAllMembers%2A?displayProperty=fullName&gt;."
  syntax:
    content: public System.Reflection.Assembly LocalAssembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: "Een CLR-reflectie <xref:System.Reflection.Assembly>object.</xref:System.Reflection.Assembly>"
  overload: System.Xaml.XamlReaderSettings.LocalAssembly*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  id: ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de lezer regelnummer en positie kan bieden."
  remarks: "ProvideLineInfo is `false` in het objectmodel; echter, kan worden ingesteld op `true` tijdens runtime op basis van het geladen uitvoerbare bestanden en hun instellingen voor foutopsporing."
  syntax:
    content: public bool ProvideLineInfo { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de lezer kan bieden op regelnummer en plaatst informatie; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  id: ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de lezer dat afgedwongen alle <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> knooppunten worden verwerkt als een <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> type."
  remarks: "Naast <xref:System.String>, een mogelijke `Value` inhoud onder sommige implementaties XAML is <xref:System.Windows.Markup.XData>.</xref:System.Windows.Markup.XData> </xref:System.String>"
  syntax:
    content: public bool ValuesMustBeString { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de lezer dat alleen afgedwongen <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> is opgenomen in <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> knooppunten; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlReaderSettings.#ctor
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
- uid: System.Xaml.XamlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlReaderSettings.BaseUri
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
- uid: System.Xaml.XamlReaderSettings.#ctor*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Xaml.XamlReaderSettings.BaseUri*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
