### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  id: PeerApplicationCollection
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  langs:
  - csharp
  name: PeerApplicationCollection
  nameWithType: PeerApplicationCollection
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  type: Class
  summary: "Hiermee geeft u een container voor <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> elementen. Een exemplaar van dit type wordt geretourneerd door de <xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>statische methode.</xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>"
  remarks: "Er is geen openbare constructors zijn gedefinieerd voor deze klasse."
  syntax:
    content: 'public class PeerApplicationCollection : System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>'
  inheritance:
  - System.Collections.ObjectModel.Collection`1
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Voegt een nieuwe <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> element in de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;> </xref> op de opgegeven index of sleutel."
  remarks: '`Null`items zijn niet toegestaan.'
  syntax:
    content: protected override void InsertItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "De op nul gebaseerde index van het element dat u wilt vervangen"
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "De nieuwe waarde voor het element bij de opgegeven index"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Vervangt de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> bij de opgegeven index."
  remarks: '`Null`items zijn niet toegestaan.'
  syntax:
    content: protected override void SetItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "De op nul gebaseerde index van het element te vervangen."
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "De nieuwe waarde voor het element bij de opgegeven index."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  id: ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Retourneert een <xref:System.String>voor de huidige waarde van elke <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> object, gescheiden door komma&quot;s.</xref:System.String>"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "Een <xref:System.String>voor de huidige waarde van elke <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> in de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;> </xref>, gescheiden door komma&quot;s.</xref:System.String>"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ObjectModel.Collection`1
  isExternal: false
  name: System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem
  nameWithType: PeerApplicationCollection.InsertItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem
  nameWithType: PeerApplicationCollection.SetItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString
  nameWithType: PeerApplicationCollection.ToString
