### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Maakt een Web.config-bestand voor een SOAP-functionaliteit COM +-toepassing. Kan onderdeel vermeldingen ook toevoegen aan het bestand voor de COM-interfaces wordt gepubliceerd in de toepassing."
  remarks: "De klasse ServerWebConfig wordt gebruikt voor een Web.config-bestand maken tijdens het maken van een virtuele hoofdmap in Internet Information Services (IIS) 6.0 voor een SOAP-functionaliteit COM +-toepassing. Het kan ook XML-elementen in het bestand Web.config voor componentinterfaces wordt toegevoegd aan de toepassing toevoegen.       ServerWebConfig wordt intern gebruikt door het .NET Framework. U hoeft niet te gebruiken deze rechtstreeks in uw code."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> klasse."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "XML-elementen worden toegevoegd aan een Web.config-bestand voor een COM-interface wordt gepubliceerd in een SOAP-functionaliteit COM +-toepassing."
  remarks: "Voor het opgegeven type, de methode AddElement wordt toegevoegd aan het bestand Web.config de `<wellknown>` en `<activated>` elementen als onderliggende elementen van de `<service>` element met de volgende XPath: `/configuration/system.runtime.remoting/application/service` de `AssemblyName`, `TypeName`, `ProgId`, en `WkoMode` parameters zijn opgenomen in de kenmerkwaarden van de twee elementen toegevoegd.       AddElement mag niet rechtstreeks worden aangeroepen. Roep in plaats daarvan de <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>methode.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Het pad van het bestaande bestand Web.config."
    - id: AssemblyName
      type: System.String
      description: "De naam van de assembly waarin het type dat wordt toegevoegd."
    - id: TypeName
      type: System.String
      description: "De naam van het type dat wordt toegevoegd."
    - id: ProgId
      type: System.String
      description: "De programma-id voor het type dat wordt toegevoegd."
    - id: WkoMode
      type: System.String
      description: "Een tekenreeksconstante die overeenkomt met de naam van een lid van de <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> opsomming, waarmee wordt aangegeven hoe een bekend object wordt geactiveerd."
    - id: Error
      type: System.String
      description: "Een tekenreeks waarmee een foutbericht kan worden geschreven."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Een Web.config-bestand voor een SOAP-functionaliteit COM +-toepassing maakt zodat het bestand is gereed om te hebben van XML-elementen toegevoegd voor COM-interfaces wordt gepubliceerd."
  remarks: "De methode Create maakt een Web.config-bestand met de hiërarchie voor een leeg element met de volgende XPath: ```   /configuration/system.runtime.remoting/application/service   ``` in plaats van het instantiëren van een <xref:System.EnterpriseServices.Internal.ServerWebConfig>klasse object en het maken rechtstreeks aanroep aanroepen de <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>methode.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "De map waarin het configuratiebestand moet worden gemaakt."
    - id: FilePrefix
      type: System.String
      description: "De tekenreekswaarde &quot;Web&quot;, waarmee een config-uitbreiding is toegevoegd."
    - id: Error
      type: System.String
      description: "Een tekenreeks waarmee een foutbericht kan worden geschreven."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
