### YamlMime:ManagedReference
items:
- uid: System.Windows.Automation.ClientSettings
  id: ClientSettings
  children:
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  langs:
  - csharp
  name: ClientSettings
  nameWithType: ClientSettings
  fullName: System.Windows.Automation.ClientSettings
  type: Class
  summary: "Methoden die aan de clientzijde providers beschikbaar te maken voor de client bevat."
  syntax:
    content: public static class ClientSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  id: RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Registreert een assembly met client-side &quot;-providers."
  remarks: "Deze methode wordt aangeroepen bij het opstarten door UI Automation-clients die gebruikmaken van de client-side UI Automation providers van een assembly is geladen. Toepassingen die gebruikmaken van de providers die zijn geïmplementeerd in hun eigen assembly moeten <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviders%2A>.</xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviders%2A> aanroepen"
  example:
  - For example code, see [Register a Client-Side Provider Assembly](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public static void RegisterClientSideProviderAssembly (System.Reflection.AssemblyName assemblyName);
    parameters:
    - id: assemblyName
      type: System.Reflection.AssemblyName
      description: "De naam van de assembly."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "De assembly kan niet worden geladen."
  platform:
  - net462
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  id: RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Registreert clientzijde providers."
  remarks: "Deze methode wordt aangeroepen bij het opstarten door clients die hun eigen client-side &quot;-providers te implementeren. Clients die gebruikmaken van providers via een aparte assembly moeten <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly%2A>.</xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly%2A> aanroepen"
  example:
  - For example code, see [Implement UI Automation Providers in a Client Application](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public static void RegisterClientSideProviders (System.Windows.Automation.ClientSideProviderDescription[] clientSideProviderDescription);
    parameters:
    - id: clientSideProviderDescription
      type: System.Windows.Automation.ClientSideProviderDescription[]
      description: "Een matrix met beschrijvingen van de provider."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "De assembly kan niet worden geladen."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Windows.Automation.ProxyAssemblyNotLoadedException
  parent: System.Windows.Automation
  isExternal: false
  name: ProxyAssemblyNotLoadedException
  nameWithType: ProxyAssemblyNotLoadedException
  fullName: System.Windows.Automation.ProxyAssemblyNotLoadedException
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
- uid: System.Reflection.AssemblyName
  parent: System.Reflection
  isExternal: true
  name: AssemblyName
  nameWithType: AssemblyName
  fullName: System.Reflection.AssemblyName
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
- uid: System.Windows.Automation.ClientSideProviderDescription[]
  parent: System.Windows.Automation
  isExternal: false
  name: ClientSideProviderDescription
  nameWithType: ClientSideProviderDescription
  fullName: System.Windows.Automation.ClientSideProviderDescription[]
  spec.csharp:
  - uid: System.Windows.Automation.ClientSideProviderDescription
    name: ClientSideProviderDescription
    nameWithType: ClientSideProviderDescription
    fullName: ClientSideProviderDescription[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders
  nameWithType: ClientSettings.RegisterClientSideProviders
