### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  id: CheckForUpdateCompletedEventHandler
  langs:
  - csharp
  name: CheckForUpdateCompletedEventHandler
  nameWithType: CheckForUpdateCompletedEventHandler
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die wordt afgehandeld tijdens de <xref href=&quot;System.Deployment.Application.ApplicationDeployment.CheckForUpdateCompleted&quot;> </xref> gebeurtenis van een <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'Wanneer u een gemachtigde CheckForUpdateCompletedEventHandler maakt, kunt u de methode waarmee de gebeurtenis wordt afgehandeld identificeren. Toevoegen om te koppelen van de gebeurtenis met gebeurtenis-handler, een exemplaar van de gemachtigde aan de gebeurtenis. De gebeurtenis-handler wordt aangeroepen wanneer de gebeurtenis plaatsvindt, tenzij u de gemachtigde verwijdert. Zie voor meer informatie over de gebeurtenis-handler gemachtigden [KROONTJESPEN: gebeurtenissen en gemachtigden](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void CheckForUpdateCompletedEventHandler(object sender, CheckForUpdateCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
