### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "Beschrijving van een afdruktaak."
  remarks: "De <xref:System.Printing.PrintTicket>-object, dat de waarde is van de <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>eigenschap, bevat de gedetailleerde instellingen voor een afdruktaak.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> De bovenliggende, PrintJobSettings, voegt alleen een beschrijving.      > [!CAUTION] > Klassen binnen de <xref:System.Printing>naamruimte worden niet ondersteund voor gebruik in een Windows-service of ASP.NET-toepassing of service.</xref:System.Printing> Bij het gebruik van deze klassen uit binnen één van deze toepassingstypen kan leiden tot onverwachte problemen, zoals verminderde prestaties en runtime-uitzonderingen service.       Als u afdrukken vanuit een Windows Forms-toepassingen wilt, raadpleegt u de <xref:System.Drawing.Printing>naamruimte.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Opgehaald of ingesteld een <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> -object met de gedetailleerde instellingen voor de afdruktaak."
  remarks: "Als u deze eigenschap CurrentPrintTicket is geen valideren of de opgegeven wijzigen <xref:System.Printing.PrintTicket>voor een bepaalde <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Indien nodig, gebruiken de <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>methode voor het maken van een <xref:System.Printing.PrintQueue>-specifieke <xref:System.Printing.PrintTicket>die geldt voor een bepaalde printer.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "Een <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> object dat de details over de afdruktaak, zoals het aantal exemplaren dat u wilt afdrukken, bevat en of nieten of dubbelzijdig afdrukken wordt gebruikt."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Opgehaald of ingesteld van een beschrijving van een afdruktaak."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "Een <xref:System.String>die beschrijft de afdruktaak, bijvoorbeeld &quot;rapport per kwartaal.&quot;</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
