### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpHandlersSection
  id: HttpHandlersSection
  children:
  - System.Web.Configuration.HttpHandlersSection.#ctor
  - System.Web.Configuration.HttpHandlersSection.Handlers
  - System.Web.Configuration.HttpHandlersSection.Properties
  langs:
  - csharp
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection
  fullName: System.Web.Configuration.HttpHandlersSection
  type: Class
  summary: "Hiermee configureert u een HTTP-handler voor een webtoepassing. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse HttpHandlersSection biedt een manier om programmatisch toegang en wijzig de `httpHandlers` gedeelte van een configuratiebestand. Dit type maakt deel uit van een groep met de <xref:System.Web.Configuration.HttpHandlerAction>en de <xref:System.Web.Configuration.HttpHandlerActionCollection>typen.</xref:System.Web.Configuration.HttpHandlerActionCollection> </xref:System.Web.Configuration.HttpHandlerAction>      > [!NOTE] > De HttpHandlersSection kunnen lezen en schrijven van gegevens van en naar de bijbehorende sectie van het configuratiebestand volgens de <xref:System.Configuration.SectionInformation.AllowDefinition%2A>eigenschap sectie waarvan de waarde <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> is</xref:System.Configuration.SectionInformation.AllowDefinition%2A>"
  example:
  - "The following code example shows how to use the HttpHandlersSection class to access the `httpHandlers` section of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#1](~/add/codesnippet/csharp/t-system.web.configurati_16_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#1](~/add/codesnippet/visualbasic/t-system.web.configurati_16_1.vb)]  \n  \n The following configuration excerpt shows how to specify values declaratively for the `httpHandlers` section.  \n  \n```  \n<httpHandlers>  \n  <add path=\"Calculator.custom\"  \n    type=\"Samples.Aspnet.SystemWebConfiguration.Calculator, CalculatorHandler\"  \n    verb=\"GET\" validate=\"false\" />  \n</httpHandlers>   \n```"
  syntax:
    content: 'public sealed class HttpHandlersSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.HttpHandlersSection&quot;> </xref> klasse."
  remarks: "De constructor HttpHandlersSection is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Verkrijgen van een exemplaar van de <xref:System.Web.Configuration.HttpHandlersSection>klasse met behulp van de <xref:System.Configuration.Configuration.GetSection%2A>methode.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpHandlersSection>"
  syntax:
    content: public HttpHandlersSection ();
    parameters: []
  overload: System.Web.Configuration.HttpHandlersSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  id: Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Haalt de <xref href=&quot;System.Web.Configuration.HttpHandlerActionCollection&quot;> </xref> verzameling <xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;> </xref> objecten in de <xref href=&quot;System.Web.Configuration.HttpHandlersSection&quot;> </xref> object."
  remarks: "De Handlers eigenschap verzameling geretourneerd door deze methode verwijst niet naar een werkelijke element in het onderliggende configuratiebestand. Het is een <xref:System.Web.Configuration>constructie waarmee u eenvoudig toegang krijgen tot de handlers die deze bevat.</xref:System.Web.Configuration> Dit is een algemene patroon voor het verwerken van de elementen van een configuratiebestand."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpHandlerAction> handlers.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#4](~/add/codesnippet/csharp/p-system.web.configurati_121_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#4](~/add/codesnippet/visualbasic/p-system.web.configurati_121_1.vb)]"
  syntax:
    content: public System.Web.Configuration.HttpHandlerActionCollection Handlers { get; }
    return:
      type: System.Web.Configuration.HttpHandlerActionCollection
      description: "Een <xref href=&quot;System.Web.Configuration.HttpHandlerActionCollection&quot;> </xref> die bevat de <xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;> </xref> objecten of -handlers."
  overload: System.Web.Configuration.HttpHandlersSection.Handlers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.HttpHandlersSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
- uid: System.Web.Configuration.HttpHandlerActionCollection
  parent: System.Web.Configuration
  isExternal: false
  name: HttpHandlerActionCollection
  nameWithType: HttpHandlerActionCollection
  fullName: System.Web.Configuration.HttpHandlerActionCollection
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection.HttpHandlersSection
- uid: System.Web.Configuration.HttpHandlersSection.Handlers*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
- uid: System.Web.Configuration.HttpHandlersSection.Properties*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
