### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationInfo
  id: ApplicationInfo
  children:
  - System.Web.Hosting.ApplicationInfo.ID
  - System.Web.Hosting.ApplicationInfo.PhysicalPath
  - System.Web.Hosting.ApplicationInfo.VirtualPath
  langs:
  - csharp
  name: ApplicationInfo
  nameWithType: ApplicationInfo
  fullName: System.Web.Hosting.ApplicationInfo
  type: Class
  summary: "Bevat informatie over een actieve toepassing. Deze klasse kan niet worden overgenomen."
  remarks: "Het object ApplicationInfo wordt gebruikt door de <xref:System.Web.Hosting.ApplicationManager>klasse voor informatie over het uitvoeren van toepassingen.</xref:System.Web.Hosting.ApplicationManager>"
  example:
  - "The following code example gets an array of ApplicationInfo objects from the <xref:System.Web.Hosting.ApplicationManager> object associated with the current process.  \n  \n [!code-vb[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/visualbasic/t-system.web.hosting.app_1.aspx)]\n [!code-cs[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/csharp/t-system.web.hosting.app_1.aspx)]"
  syntax:
    content: public sealed class ApplicationInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.ID
  id: ID
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hiermee wordt de unieke id voor de toepassing."
  remarks: "De toepassings-ID is voor toepassingen die worden uitgevoerd onder Microsoft Internet Information Services (IIS), het metabasepad naar de hoofdmap van de toepassing, zoals /LM/W3SVC/1/Root/application."
  syntax:
    content: public string ID { get; }
    return:
      type: System.String
      description: "De unieke id voor de toepassing opgegeven wanneer de toepassing is gemaakt met behulp van de <xref:System.Web.Hosting.ApplicationManager.CreateObject*>methode.</xref:System.Web.Hosting.ApplicationManager.CreateObject*>"
  overload: System.Web.Hosting.ApplicationInfo.ID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  id: PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hiermee haalt u het fysieke pad overeenkomt met de hoofdmap van de toepassing."
  remarks: "De eigenschap PhysicalPath is het pad dat is doorgegeven aan de <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>methode toen de toepassing werd gemaakt.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string PhysicalPath { get; }
    return:
      type: System.String
      description: "Het fysieke pad overeenkomt met de hoofdmap van de toepassing."
  overload: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  id: VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hiermee haalt u het virtuele pad overeenkomt met de hoofdmap van de toepassing."
  remarks: "De eigenschap VirtualPath is het virtuele pad dat is doorgegeven aan de <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>methode toen de toepassing werd gemaakt.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "Het virtuele pad overeenkomt met de hoofdmap van de toepassing."
  overload: System.Web.Hosting.ApplicationInfo.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Hosting.ApplicationInfo.ID
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
- uid: System.Web.Hosting.ApplicationInfo.ID*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
