### YamlMime:ManagedReference
items:
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  id: ServiceNameElement
  children:
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  langs:
  - csharp
  name: ServiceNameElement
  nameWithType: ServiceNameElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  type: Class
  summary: "De klasse ServiceNameElement vertegenwoordigt een configuratie-element voor de naam van een service gebruikt in een <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection&quot;> </xref>."
  syntax:
    content: 'public sealed class ServiceNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: ServiceNameElement()
  nameWithType: ServiceNameElement.ServiceNameElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.ServiceNameElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement&quot;> </xref> klasse."
  remarks: "Wanneer deze constructor is gebruikt voor het initialiseren van een nieuw exemplaar van de <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement>klasse, de <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A>eigenschap is ingesteld op `null`.</xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A> </xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement>       De <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A>eigenschap moet worden ingesteld op een geschikte waarde voor de toepassing voordat u de <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection.Add%2A>methode voor het toevoegen van het <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement>exemplaar van de <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection>klasse.</xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection> </xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement> </xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection.Add%2A> </xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A>"
  syntax:
    content: public ServiceNameElement ();
    parameters: []
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  id: Name
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Opgehaald of ingesteld van de Service Provider Name (SPN) voor deze <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement&quot;> </xref> exemplaar."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Een <xref:System.String>die bevat de weergave van de SPN voor deze <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement&quot;> </xref> exemplaar.</xref:System.String>"
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  id: Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceNameElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: ServiceNameElement()
  nameWithType: ServiceNameElement.ServiceNameElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.ServiceNameElement()
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Properties
  nameWithType: ServiceNameElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: ServiceNameElement
  nameWithType: ServiceNameElement.ServiceNameElement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Name
  nameWithType: ServiceNameElement.Name
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Properties
  nameWithType: ServiceNameElement.Properties
