### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup
  id: CachingSectionGroup
  children:
  - System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  - System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  langs:
  - csharp
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup
  type: Class
  summary: "Hiermee definieert u een configuratie sectie for.NET Framework opslaan in cache. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse CachingSectionGroup definieert een cache in sectie (`system.runtime.caching`) voor configuratiebestanden. In dit gedeelte bevat elementen die worden gebruikt voor het configureren van verschillende typen caches. In ASP.NET is het enige element dat beschikbaar is in de sectie cache in het element. Dit element configureert caches die zijn gebaseerd op de <xref:System.Runtime.Caching.MemoryCache>klasse.</xref:System.Runtime.Caching.MemoryCache>"
  syntax:
    content: 'public sealed class CachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Runtime.Caching.Configuration.CachingSectionGroup&quot;> </xref> klasse."
  syntax:
    content: public CachingSectionGroup ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  id: MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Hiermee wordt de verzameling <xref href=&quot;System.Runtime.Caching.Configuration.MemoryCacheElement&quot;> </xref> objecten."
  remarks: "De eigenschap MemoryCaches retourneert de verzameling van <xref:System.Runtime.Caching.Configuration.MemoryCacheSection>objecten uit de bovenliggende sectie caching.</xref:System.Runtime.Caching.Configuration.MemoryCacheSection>"
  syntax:
    content: public System.Runtime.Caching.Configuration.MemoryCacheSection MemoryCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSection
      description: "De verzameling van objecten van de cache-sectie."
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup.CachingSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
