### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die wordt afgehandeld tijdens de <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;> </xref> gebeurtenis."
  remarks: "De <xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>gebeurtenis treedt op vlak voor een groep van toepassing instellingen blijven bewaard, doorgaans tijdens het uitvoeren van de <xref:System.Configuration.ApplicationSettingsBase.Save%2A>methode van een wrapperklasse is afgeleid van <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Save%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
