### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Geeft aan dat een groep van toepassingen instellingen of de eigenschap verschillende waarden voor elke gebruiker van een toepassing bevat. Deze klasse kan niet worden overgenomen."
  remarks: "Toepassingseigenschappen instellingen hebben een bereik dat is gebaseerd op de toepassing of het gebruikersniveau van de. Als de categorieën impliceren, aanwezig eigenschappen toepassingsbereik uniform waarden voor alle gebruikers van de toepassing dat gericht op de gebruiker eigenschappen hebben speciale waarden voor elke gebruiker van de toepassing.       De UserScopedSettingAttribute geeft aan dat een eigenschap moet worden beschouwd als een instelling voor gebruiker en dat de juiste opslag beslissingen dienovereenkomstig moeten worden aangebracht door de provider van instellingen.       Een kenmerk scope is vereist voor elke eigenschap van de instellingen van toepassing. Als een eigenschap niet met ofwel toegepast wordt een <xref:System.Configuration.ApplicationScopedSettingAttribute>of geen UserScopedSettingAttribute, de eigenschap wordt genegeerd door de provider van instellingen, het is niet geserialiseerd.</xref:System.Configuration.ApplicationScopedSettingAttribute> Het is echter ongeldig, beide kenmerken toepassen op de eigenschap met dezelfde instellingen. Een poging gedaan, wordt een <xref:System.Configuration.ConfigurationErrorsException>gegenereerd.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> klasse."
  remarks: "Elke eigenschap van de instellingen van toepassing moet worden toegepast met een kenmerk één scope om deze kan worden herkend en door de provider van instellingen is geserialiseerd."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
