### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebApplicationLevel
  id: WebApplicationLevel
  children:
  - System.Web.Configuration.WebApplicationLevel.AboveApplication
  - System.Web.Configuration.WebApplicationLevel.AtApplication
  - System.Web.Configuration.WebApplicationLevel.BelowApplication
  langs:
  - csharp
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
  type: Enum
  summary: "Hiermee geeft u het pad van een configuratiebestand voor de webtoepassing."
  remarks: "De klasse WebApplicationLevel biedt drie niveaus die worden gebruikt om te onderscheiden waarbij een configuratiebestand is ten opzichte van het hoogste niveau van een ASP.NET-webtoepassing. Er zijn drie pad niveau typen AboveApplication AtApplication en BelowApplication."
  syntax:
    content: public enum WebApplicationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  id: AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat het configuratiebestand in een globale map ten opzichte van de huidige ASP.NET-webtoepassing."
  syntax:
    content: AboveApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  id: AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat het configuratiebestand in de hoofdmap van de huidige ASP.NET-webtoepassing."
  syntax:
    content: AtApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  id: BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat het configuratiebestand in een submap van de huidige ASP.NET-webtoepassing."
  syntax:
    content: BelowApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
