### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: "Biedt gegevens voor de <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadApplicationCompleted&quot;> </xref> gebeurtenis."
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u het pad van het logboekbestand ClickOnce."
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: "Het pad van het logboekbestand ClickOnce."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u de inhoud van een .appref-ms-bestand dat deze ClickOnce-toepassing kunt starten."
  remarks: 'Deze eigenschap de tekst bevat een aangepast installatieprogramma kunt schrijven naar een bestand .appref ms om deze ClickOnce-toepassing te starten. ClickOnce Dit startbestand voor u gemaakt wanneer installeert een ClickOnce-toepassing die beschikbaar is offline, met uitzondering van toepassingen met de `<customUX>` element. Een aangepast installatieprogramma maakt een snelkoppeling start een ClickOnce-toepassing waarin een `<customUX>` element door de tekst in deze eigenschap schrijven naar een nieuwe .appref-ms-bestand in Unicode-indeling. Zie voor meer informatie [ \&lt; entryPoint\&gt; Element](../Topic/%3CentryPoint%3E%20Element%20\(ClickOnce%20Application\).md) en [scenario: een aangepaste installatieprogramma voor een ClickOnce-toepassing maken](~/add/includes/ajax-current-ext-md.md).'
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: "De inhoud van een .appref-ms-bestand."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
