### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement
  id: XPathMessageFilterElement
  children:
  - System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  - System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  - System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  - System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  langs:
  - csharp
  name: XPathMessageFilterElement
  nameWithType: XPathMessageFilterElement
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement
  type: Class
  summary: "Een configuratie-element dat wordt gebruikt in de logboekregistratie van berichten vertegenwoordigt. Deze klasse kan niet worden overgenomen."
  remarks: "Een filter XPath is een query op een XML-document dat is gedefinieerd door een 1.0 XPath-expressie.       XPath-filters kunnen worden toegevoegd aan de `messageLogging` sectie specifieke berichten op het niveau van transport en -service aanmelden. Als er geen filters zijn gedefinieerd, worden alle berichten worden geregistreerd. Filters worden alleen toegepast op de kop van het bericht. De instantie wordt genegeerd. [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]negeert de berichttekst om prestaties te verbeteren. Als u wilt filteren op basis van de inhoud van de instantie, kunt u een aangepaste listener kunt maken met een filter dat doet.       Wanneer transport berichtregistratie is ingeschakeld (<xref:System.ServiceModel.Configuration.MessageLoggingElement.LogMessagesAtTransportLevel%2A> is `true`), alleen berichten die overeenkomen met de filters worden geregistreerd.</xref:System.ServiceModel.Configuration.MessageLoggingElement.LogMessagesAtTransportLevel%2A>"
  syntax:
    content: 'public sealed class XPathMessageFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: XPathMessageFilterElement()
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.XPathMessageFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> klasse."
  syntax:
    content: public XPathMessageFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "Moet worden toegevoegd."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  id: Filter
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van het filter XPath is gedefinieerd."
  syntax:
    content: public System.ServiceModel.Dispatcher.XPathMessageFilter Filter { get; set; }
    return:
      type: System.ServiceModel.Dispatcher.XPathMessageFilter
      description: "Het filter XPath is gedefinieerd."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement (System.Xml.XmlWriter writer, string elementName);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Moet worden toegevoegd."
    - id: elementName
      type: System.String
      description: "Moet worden toegevoegd."
    return:
      type: System.Boolean
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: XPathMessageFilterElement()
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.XPathMessageFilterElement()
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
- uid: System.ServiceModel.Dispatcher.XPathMessageFilter
  parent: System.ServiceModel.Dispatcher
  isExternal: false
  name: XPathMessageFilter
  nameWithType: XPathMessageFilter
  fullName: System.ServiceModel.Dispatcher.XPathMessageFilter
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: XPathMessageFilterElement
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: DeserializeElement
  nameWithType: XPathMessageFilterElement.DeserializeElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: SerializeToXmlElement
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement
