### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "Biedt een tekenreeks die een groep van toepassingen instellingen eigenschap beschrijft. Deze klasse kan niet worden overgenomen."
  remarks: "Een klasse-instellingen van toepassing is afgeleid van <xref:System.Configuration.ApplicationSettingsBase>, een of meer eigenschappen die deel uitmaken van dezelfde toepassingsgroep voor de eigenschap worden gedefinieerd.</xref:System.Configuration.ApplicationSettingsBase> SettingsGroupDescriptionAttribute is een optionele kenmerk waarmee u kunt een beschrijvende tekst voor een groep van de eigenschap instellingen. Deze tekst is bedoeld om zowel ontwerptijd hulpprogramma&quot;s en runtime-Systeembeheer helpt bij het identificeren en de gekoppelde eigenschappengroep beschrijven.      > [!NOTE] > Dit kenmerk kan alleen worden toegepast op het niveau van de wrapper-klasse."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsGroupDescriptionAttribute&quot;> </xref> klasse."
  remarks: "Hoewel de theoretische maximale lengte van de `description` parameter wordt begrensd door de bovengrens van een <xref:System.Int32>, praktische grenzen, bepaald door de gebruiksvriendelijkheid en quotumbeperkingen die zijn opgelegd door de provider van instellingen, worden veel kleiner.</xref:System.Int32>"
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "Een <xref:System.String>waarin de beschrijvende tekst voor de groep van toepassingen instellingen.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "De beschrijvende tekst voor de toepassingsgroep voor de eigenschappen van instellingen."
  remarks: "De waarde van de beschrijving-eigenschap is ingesteld in de <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>constructor.</xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>waarin de beschrijvende tekst voor de groep van toepassingen instellingen.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
