### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderException
  id: ProviderException
  children:
  - System.Configuration.Provider.ProviderException.#ctor
  - System.Configuration.Provider.ProviderException.#ctor(System.String)
  - System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ProviderException
  nameWithType: ProviderException
  fullName: System.Configuration.Provider.ProviderException
  type: Class
  summary: "De uitzondering die wordt gegenereerd wanneer een provider configuratiefout opgetreden. Deze uitzonderingsklasse wordt ook gebruikt door providers uitzonderingen genereert interne fouten binnen de provider die niet zijn toegewezen aan andere bestaande uitzonderingsklassen."
  remarks: "De ProviderException wordt gegenereerd wanneer er een fout optreedt tijdens het laden van een configuratieprovider."
  syntax:
    content: 'public class ProviderException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: System.Configuration.Provider.ProviderException.ProviderException()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> klasse."
  syntax:
    content: public ProviderException ();
    parameters: []
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> klasse."
  syntax:
    content: public ProviderException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Een bericht met een beschrijving van waarom dit <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> is opgetreden."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(SerializationInfo,StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> klasse."
  syntax:
    content: protected ProviderException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de informatie bevat te deserialiseren."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Contextuele informatie over de bron- of doelserver."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String,Exception)
  nameWithType: ProviderException.ProviderException(String,Exception)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String,Exception)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> klasse."
  syntax:
    content: public ProviderException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Een bericht met een beschrijving van waarom dit <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> is opgetreden."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die dit <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> gegenereerd."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.Provider.ProviderException.#ctor
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: System.Configuration.Provider.ProviderException.ProviderException()
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(SerializationInfo,StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String,Exception)
  nameWithType: ProviderException.ProviderException(String,Exception)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String,Exception)
- uid: System.Configuration.Provider.ProviderException.#ctor*
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException
  nameWithType: ProviderException.ProviderException
