### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FolderLevelBuildProvider
  id: FolderLevelBuildProvider
  children:
  - System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  - System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  - System.Web.Configuration.FolderLevelBuildProvider.Name
  - System.Web.Configuration.FolderLevelBuildProvider.Properties
  - System.Web.Configuration.FolderLevelBuildProvider.Type
  langs:
  - csharp
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider
  fullName: System.Web.Configuration.FolderLevelBuildProvider
  type: Class
  summary: "Hiermee geeft u configuratie-instellingen waarmee u gebruik van de <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> klasse voor specifieke mappen."
  remarks: "De ASP.NET-build-omgeving maakt gebruik van FolderLevelBuildProvider objecten voor het genereren van de broncode voor de verschillende bestandstypen en submappen in een toepassing. Klassen die zijn afgeleid van de klasse FolderLevelBuildProvider broncode voor mappen, zoals Bin, App_GlobalResources, app_localresources heen gekopieerd, App_WebReferences, App_Browsers, thema en voor andere aangepaste mappen genereren. Normaal gesproken maakt niet u een exemplaar van de klasse FolderLevelBuildProvider rechtstreeks. In plaats daarvan het implementeren van een klasse die is afgeleid van <xref:System.Web.Compilation.BuildProvider>en toe te passen de <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>klasse toe en configureer vervolgens de afgeleide klasse voor gebruik in de ASP.NET-opbouwomgeving.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute> </xref:System.Web.Compilation.BuildProvider> De <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>klasse gericht is op de mappen in plaats van bestanden.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>       Gebruik van exemplaren van de klasse FolderLevelBuildProvider samen met <xref:System.Web.Compilation.AssemblyBuilder>objecten voor het bouwen van een of meer bestanden in een gecompileerde assembly.</xref:System.Web.Compilation.AssemblyBuilder> Het exemplaar FolderLevelBuildProvider genereert broncode in de juiste taal voor afzonderlijke bestanden en de <xref:System.Web.Compilation.AssemblyBuilder>object maakt de broncode die is bijgedragen door elk exemplaar FolderLevelBuildProvider in één assembly.</xref:System.Web.Compilation.AssemblyBuilder>       De klasse FolderLevelBuildProvider is opgegeven in de `configuration` gedeelte van het bestand Web.config."
  example:
  - "The following example shows how to add a build provider named `BuildProvider1` to the Web.config file.  \n  \n```  \n<compilation>  \n  <folderLevelBuildProviders>  \n    <add type=\"BuildProvider1, Assembly1,Version=1.0.0.0,    \n        PublicKeyToken=xxxxx\"/>  \n  </folderLevelBuildProviders>  \n</compilation>  \n```"
  syntax:
    content: 'public sealed class FolderLevelBuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> klasse met behulp van een id en de volledig gekwalificeerde naam."
  syntax:
    content: public FolderLevelBuildProvider (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "De id voor de <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> te gebruiken."
    - id: type
      type: System.String
      description: "De volledig gekwalificeerde naam van de <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> te gebruiken."
  overload: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Retourneert een waarde die aangeeft of een opgegeven object gelijk aan de huidige is <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> object."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Het build-provider-object om te vergelijken."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het niveau van de opgegeven map build-provider-object is gelijk aan het huidige object. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Genereert een hashcode voor de <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> object."
  remarks: "Deze methode genereert een geheel getal dat kan worden gebruikt om het mapobject niveau build-provider te identificeren. Deze methode neemt over van de <xref:System.Object.GetHashCode%2A>methode.</xref:System.Object.GetHashCode%2A> De <xref:System.Object.GetHashCode%2A>methode is geschikt voor hash-algoritmen en gegevens structuren zoals hash-tabel.</xref:System.Object.GetHashCode%2A>"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "De hash-code voor de <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> object."
  overload: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  id: Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de naam van de <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> object."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "De naam van het object van de build-provider."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  id: Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de volledig gekwalificeerde naam van de klasse build-provider."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "De volledig gekwalificeerde naam van de klasse build-provider."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals
  nameWithType: FolderLevelBuildProvider.Equals
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: FolderLevelBuildProvider.GetHashCode
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
