### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: "Geeft de XML-naamruimte en de XML-naamruimtevoorvoegsel moet worden gebruikt voor een indelingsextensie voor een beschrijving in een beschrijving van de service. Deze klasse kan niet worden overgenomen."
  remarks: "Een beschrijving van indelingsextensie breidt hoe een beschrijving van de service wordt gegenereerd voor een XML-webservice gemaakt met behulp van ASP.NET. Een beschrijving van indelingsextensie wordt in het bijzonder XML-elementen toegevoegd aan de servicebeschrijving. Dit is handig wanneer een SOAP-extensie wordt gemaakt om uit te voeren op de client en de server-zijde van een XML-webservice, zoals informatie over de SOAP-extensies niet automatisch wordt geplaatst in de servicebeschrijving van de. Als u informatie over de SOAP-extensie aan de beschrijving van de service toevoegen, herkent een client dus dat de specifieke SOAP-uitbreiding moet worden uitgevoerd. Een voorbeeld van een SOAP-extensie die moet worden uitgevoerd op de client en de server is een versleuteling SOAP-extensie. Als een versleuteling SOAP-extensie op alleen de server wordt uitgevoerd en deze retourwaarden worden versleuteld voordat ze worden verzonden naar de client, moet de client voor het ontsleutelen van het SOAP-bericht met de SOAP-extensie hebben. Anders wordt de client kan de retourwaarde niet verwerken.       Gebruik de volgende stappen voor het bouwen van een beschrijving van indelingsextensie: 1.  Een klasse die is afgeleid van <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension> bouwen      2.  Van toepassing een <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>aan de klasse en geef de Extensiepunten waarmee de beschrijving van indelingsextensie moet worden uitgevoerd.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Desgewenst een XmlFormatExtensionPointAttribute van toepassing op de klasse en geef een lid in de klasse om te fungeren als een nieuwe extensiepunt.      4.  Eventueel van toepassing een <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>aan de klasse en geef het voorvoegsel van de XML-naamruimte om te worden gekoppeld aan XML-elementen die worden gegenereerd door de beschrijving van indelingsextensie.</xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>      5.  Configureren van de service beschrijving indeling uitbreiding om uit te voeren binnen de `serviceDescriptionFormatExtensionTypes` gedeelte van het configuratiebestand."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPointAttribute&quot;> </xref> klasse."
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: "Het lid van de klasse die de indelingsextensie beschrijving waarvoor een beschrijving indelingsextensie gekoppeld implementeert."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of het lid van de klasse die de beschrijving van indelingsextensie implementeert opgegeven in de <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>eigenschap onbewerkte XML-elementen kan accepteren.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>"
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het lid van de klasse die de servicebeschrijving implementeert extensie die is opgegeven formatteert de <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>eigenschap onbewerkte XML-elementen kan accepteren; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> De standaardwaarde is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Hiermee geeft u op dat het lid van de klasse die de beschrijving van indelingsextensie implementeert een beschrijving indelingsextensie gekoppeld kan hebben."
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: "Het lid van de klasse die de indelingsextensie beschrijving waarvoor een beschrijving indelingsextensie gekoppeld implementeert."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
