### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.VirtualDirectoryMapping
  id: VirtualDirectoryMapping
  children:
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  - System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  - System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  - System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  - System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  langs:
  - csharp
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping
  fullName: System.Web.Configuration.VirtualDirectoryMapping
  type: Class
  summary: "Hiermee geeft u een aangepaste virtuele map hiërarchie voor een webtoepassing. Deze klasse kan niet worden overgenomen."
  syntax:
    content: public sealed class VirtualDirectoryMapping
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "Een string-waarde die het absolute pad naar een fysieke map."
    - id: isAppRoot
      type: System.Boolean
      description: "Een Boolean die aangeeft of de virtuele map de hoofdmap van de toepassing van de webtoepassing is."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  id: '#ctor(System.String,System.Boolean,System.String)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot, string configFileBaseName);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "Een string-waarde die het absolute pad naar een fysieke map."
    - id: isAppRoot
      type: System.Boolean
      description: "Een Boolean die aangeeft of de virtuele map de hoofdmap van de toepassing van de webtoepassing is."
    - id: configFileBaseName
      type: System.String
      description: "De naam van het configuratiebestand."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  id: ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van de naam van het configuratiebestand."
  remarks: "Als de naam van het configuratiebestand niet is opgegeven, wordt Web.config gebruikt."
  syntax:
    content: public string ConfigFileBaseName { get; set; }
    return:
      type: System.String
      description: "Een waarde die aangeeft van de naam van het configuratiebestand."
  overload: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "De geselecteerde waarde is null of een lege tekenreeks (&quot;&quot;)."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  id: IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de virtuele map moet worden behandeld als de hoofdmap van de toepassing."
  syntax:
    content: public bool IsAppRoot { get; set; }
    return:
      type: System.Boolean
      description: "Een waarde die aangeeft of de virtuele map moet worden behandeld als de hoofdmap van de toepassing."
  overload: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  id: PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Opgehaald of ingesteld van een waarde die aangeeft van het volledige pad van een webtoepassing."
  syntax:
    content: public string PhysicalDirectory { get; set; }
    return:
      type: System.String
      description: "Een waarde die aangeeft van het volledige pad van een webtoepassing."
  overload: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "De geselecteerde waarde is ongeldig of interne beveiligingsvalidatie is mislukt."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  id: VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Haalt een waarde die aangeeft van de virtuele map ten opzichte van de hoofdmap van de webserver."
  syntax:
    content: public string VirtualDirectory { get; }
    return:
      type: System.String
      description: "Een waarde die aangeeft van de relatieve map van de webtoepassing."
  overload: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
