### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAs
  id: SettingsSerializeAs
  children:
  - System.Configuration.SettingsSerializeAs.Binary
  - System.Configuration.SettingsSerializeAs.ProviderSpecific
  - System.Configuration.SettingsSerializeAs.String
  - System.Configuration.SettingsSerializeAs.Xml
  langs:
  - csharp
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
  type: Enum
  summary: "Bepaalt de serialisatie-schema gebruikt voor het opslaan van toepassingsinstellingen."
  remarks: "De SettingsSerializeAsenumeration wordt gebruikt voor het serialisatiemechanisme voor gebruikt door de aanbieder van de toepassing-instellingen voor het persistent maken van de waarden van instellingen toepassingseigenschappen opgeven. Bijvoorbeeld, de ttribute deze opsomming gebruikt in de constructor om te vragen of een eigenschap of groep met eigenschappen worden opgeslagen met behulp van het serialisatiemechanisme voor opgegeven."
  syntax:
    content: public enum SettingsSerializeAs
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Binary
  id: Binary
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "De eigenschap voor instellingen wordt geserialiseerd object binaire serialisatie gebruiken."
  syntax:
    content: Binary
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  id: ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "De provider van instellingen impliciete kennis van de eigenschap of het type en kiest een geschikt mechanisme voor serialisatie. Vaak gebruikt voor aangepaste serialisatie."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.String
  id: String
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "De eigenschap voor instellingen wordt geserialiseerd als tekst zonder opmaak."
  syntax:
    content: String
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Xml
  id: Xml
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "De eigenschap voor instellingen wordt geserialiseerd als XML met XML-serialisatie."
  syntax:
    content: Xml
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsSerializeAs.Binary
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
- uid: System.Configuration.SettingsSerializeAs.String
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
- uid: System.Configuration.SettingsSerializeAs.Xml
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
