### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlSchemaContextSettings
  id: XamlSchemaContextSettings
  children:
  - System.Xaml.XamlSchemaContextSettings.#ctor
  - System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  - System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  - System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  langs:
  - csharp
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
  type: Class
  summary: "Biedt optionele instellingen voor een <xref href=&quot;System.Xaml.XamlSchemaContext&quot;> </xref>."
  syntax:
    content: public class XamlSchemaContextSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlSchemaContextSettings ();
    parameters: []
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  id: '#ctor(System.Xaml.XamlSchemaContextSettings)'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> klasse met het kopiëren van de waarden van een bestaande <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> exemplaar."
  syntax:
    content: public XamlSchemaContextSettings (System.Xaml.XamlSchemaContextSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlSchemaContextSettings
      description: "Een bestaande <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  id: FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die bepaalt of een XAML-schema en de context de volledig gekwalificeerde assembly-namen gebruiken in de waarden die worden geretourneerd door de lookup-API."
  remarks: "De waarde van deze eigenschap invloed is op de tekenreeksen die worden geretourneerd door <xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A>in de schemacontext geconstrueerde.</xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A> Als <xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>is `true`, assembly-onderdeel van de tekenreeks rapporteert het equivalent van <xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName>.</xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName> </xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>"
  syntax:
    content: public bool FullyQualifyAssemblyNamesInClrNamespaces { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als een XAML-schema en de context gebruikmaken van volledig gekwalificeerde assembly-namen in de waarden die worden geretourneerd door de lookup-API&quot;s; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  id: SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of een XAML-schemacontext toestaat voor opmaakextensies waarvoor twee constructors met de dezelfde ariteit (aantal invoerparameters)."
  remarks: "Van een <xref:System.Xaml.XamlSchemaContext>, u kunt de instellingen niet rechtstreeks lezen.</xref:System.Xaml.XamlSchemaContext> In plaats daarvan u waarden ontvangt van specifieke eigenschappen voor alleen-lezen, zoals <xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>, die de waarden op basis van instellingen rapporteren.</xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>"
  syntax:
    content: public bool SupportMarkupExtensionsWithDuplicateArity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de schemacontext voor opmaakextensies waarvoor dubbele ariteit; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
- uid: System.Xaml.XamlSchemaContextSettings
  parent: System.Xaml
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
- uid: System.Xaml.XamlSchemaContextSettings.#ctor*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
