### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsProtectionEnum
  id: FormsProtectionEnum
  children:
  - System.Web.Configuration.FormsProtectionEnum.All
  - System.Web.Configuration.FormsProtectionEnum.Encryption
  - System.Web.Configuration.FormsProtectionEnum.None
  - System.Web.Configuration.FormsProtectionEnum.Validation
  langs:
  - csharp
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
  type: Enum
  summary: "Definieert het type versleuteling op dat moet worden gebruikt voor cookies."
  remarks: "Als u de waarde voor alle selecteert, gebruikt het systeem de algoritme voor gegevensvalidatie is geconfigureerd, op basis van de [machineKey Element (ASP.NET-instellingenschema)](http://msdn.microsoft.com/en-us/4b5699a9-bc21-4c4a-85f1-8b3b8ebd2d46) label. Dit is de standaardinstelling en aanbevolen waarde.       Als u geen selecteert, cookies worden aangevallen vanwege onversleutelde gegevens.       Als u validatie selecteert, wordt de cookie gemaakt met door cookievalidatie een validatiesleutel met de cookiegegevens, een Message Authentication Code (MAC) en de MAC te voegen aan de uitgaande cookie."
  example:
  - "The following code example shows how to use the FormsProtectionEnum enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/visualbasic/t-system.web.configurati_72_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/csharp/t-system.web.configurati_72_1.cs)]"
  syntax:
    content: public enum FormsProtectionEnum
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.All
  id: All
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat de toepassing zowel gegevensvalidatie als versleuteling gebruiken ter bescherming van cookies. Deze optie wordt het algoritme geconfigureerde gegevensvalidatie gebruikt (op basis van de <xref uid=&quot;langword_csharp_machineKey&quot; name=&quot;machineKey&quot; href=&quot;&quot;> </xref> element). Triple-DES (3DES) wordt gebruikt voor versleuteling, als deze beschikbaar is en als de sleutel ten minste 48 bytes is. <xref uid=&quot;langword_csharp_All&quot; name=&quot;All&quot; href=&quot;&quot;></xref>is de standaardinstelling (en aanbevolen) waarde."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  id: Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat cookies worden versleuteld met Triple-DES of DES, maar geen gegevensvalidatie wordt uitgevoerd van cookies. Cookies die op deze manier gebruikt is mogelijk onderhevig aan leesbare beveiligingsaanvallen."
  syntax:
    content: Encryption
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.None
  id: None
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat zowel versleuteling als validatie zijn uitgeschakeld voor sites die cookies alleen gebruiken voor personalisatie en dus hebben zwakkere beveiligingsvereisten. Het gebruik van cookies op deze manier wordt niet aanbevolen; het is echter de manier minste bronnen gebruikt voor het inschakelen van persoonlijke instellingen met .NET Framework."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  id: Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat de toepassing een validatieschema gebruiken om te controleren dat de inhoud van een versleuteld cookie niet in overdracht is gewijzigd. De cookie wordt gemaakt met cookievalidatie een validatiesleutel met de cookiegegevens, een Message Authentication Code (MAC) en de MAC te voegen aan de uitgaande cookie."
  syntax:
    content: Validation
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsProtectionEnum.All
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
- uid: System.Web.Configuration.FormsProtectionEnum
  parent: System.Web.Configuration
  isExternal: false
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
- uid: System.Web.Configuration.FormsProtectionEnum.None
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
