### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ChannelPoolSettings
  id: ChannelPoolSettings
  children:
  - System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  - System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  langs:
  - csharp
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings
  fullName: System.ServiceModel.Channels.ChannelPoolSettings
  type: Class
  summary: "Hiermee geeft u quota&quot;s voor de kanalen die deel uitmaken van een pool van de kanalen die wordt gebruikt door een service-eindpunt."
  remarks: "Quota&quot;s worden gebruikt als een mechanisme beleid om te voorkomen dat het verbruik van overmatig gebruik van bronnen. Ze voorkomen denial of Service (DOS) aanvallen die schadelijke of onbedoelde. Deze klasse gebruiken bij het instellen van quota kanaal op een aangepast kanaal.       ChannelPoolSettings bevat drie quota&quot;s:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>om op te geven de maximale tijdsduur waarvoor de kanalen in de groep inactief zijn kunnen voordat wordt gesloten.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>het interval van de tijd waarna een kanaal als geretourneerd aan de groep, is gesloten.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>om op te geven het maximale aantal kanalen dat kan worden opgeslagen in de resourcegroep voor elke externe eindpunt.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>"
  syntax:
    content: public class ChannelPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Channels.ChannelPoolSettings&quot;> </xref> klasse."
  remarks: "De standaardset van waarden zijn:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>: 2 minuten.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>: 10 minuten.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>: 10 kanalen.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>       Deze Standaardquotawaarden zijn gebaseerd op een conservatieve matige toewijzing van resources die geschikt voor kleine installatiescenario&quot;s en ontwikkelomgevingen zijn. Servicebeheerders Controleer kanaal quota&quot;s en afstemmen van individuele quotawaarden als een installatie onvoldoende resources wordt uitgevoerd of als verbindingen zijn ondanks de beschikbaarheid van extra resources wordt beperkt."
  syntax:
    content: public ChannelPoolSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Ophalen of stelt de maximale tijdsduur waarvoor de kanalen in de groep inactief zijn kunnen voordat wordt gesloten."
  remarks: "Het quotum IdleTimeout wordt gebruikt om te beperken tot denial of Service (DOS) aanvallen op de server die afhankelijk zijn van het verbinden van resources voor langere tijd. Als u de juiste waarde verhoogt de betrouwbaarheid van het verbinden met de service op de client. De standaardwaarde is gebaseerd op een conservatieve matige toewijzing van resources. Het is geschikt voor kleine installatiescenario&quot;s en een ontwikkelingsomgeving. Servicebeheerders Neem de waarde als een installatie onvoldoende resources wordt uitgevoerd of als verbindingen zijn ondanks de beschikbaarheid van extra resources wordt beperkt."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "De <xref:System.TimeSpan>die aangeeft dat de maximale tijdsduur waarvoor de kanalen in de groep inactief zijn kunnen voordat wordt gesloten.</xref:System.TimeSpan> De standaardwaarde is 2 minuten."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De waarde is kleiner dan nul of groter zijn dan T:System.Int32.MaxValue in milliseconden."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Opgehaald of ingesteld van de levensduur van een kanaal, waarna het is gesloten."
  remarks: "Het quotum LeaseTimeout wordt gebruikt voor voor de integratie met load balancers en voor het verbeteren van betrouwbaarheid. De standaardwaarde is gebaseerd op een conservatief toewijzing van resources. Het is geschikt voor kleine installatiescenario&quot;s en een ontwikkelingsomgeving. Servicebeheerders Neem de waarde als een installatie onvoldoende resources wordt uitgevoerd of als verbindingen zijn ondanks de beschikbaarheid van extra resources wordt beperkt."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Een <xref:System.TimeSpan>die bepaalt wat de levensduur van een kanaal, waarna het is gesloten.</xref:System.TimeSpan> De standaardwaarde is 10 minuten."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De waarde kleiner is dan nul."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  id: MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Opgehaald of ingesteld van het maximale aantal kanalen verbinding te maken met externe eindpunten die kunnen worden gestart door de service."
  remarks: "Het quotum MaxOutboundChannelsPerEndpoint cachelimieten ingesteld op de server en de client en wordt gebruikt voor het verbeteren van betrouwbaarheid. De standaardwaarde is gebaseerd op een conservatieve matige toewijzing van resources die geschikt is voor kleine installatiescenario&quot;s en een ontwikkelingsomgeving. Servicebeheerders Neem de waarde als een installatie onvoldoende resources wordt uitgevoerd of als verbindingen zijn ondanks de beschikbaarheid van extra resources wordt beperkt."
  syntax:
    content: public int MaxOutboundChannelsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Een positief geheel getal dat het maximale aantal kanalen naar een externe eindpunt in de groep die kan worden gestart door de service. De standaardwaarde is 10 kanalen."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "De waarde kleiner is dan nul."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings.ChannelPoolSettings
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
