### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultSettingValueAttribute
  id: DefaultSettingValueAttribute
  children:
  - System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  - System.Configuration.DefaultSettingValueAttribute.Value
  langs:
  - csharp
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute
  fullName: System.Configuration.DefaultSettingValueAttribute
  type: Class
  summary: "Hiermee geeft u de standaardwaarde voor de eigenschap van een toepassing-instellingen."
  remarks: "> [!IMPORTANT]> DefaultSettingValueAttribute kan alleen worden toegepast op de eigenschappen van de afzonderlijke instellingen. het is ongeldig om toe te passen van dit kenmerk aan een volledige toepassing instellingen klasse.       Providers van verschillende instellingen hebben verschillende vereisten of beperkingen op het gebruik van de DefaultSettingValueAttribute. Bijvoorbeeld de <xref:System.Configuration.LocalFileSettingsProvider>vereist geen dit kenmerk en een waarde die door dit kenmerk worden opgegeven als er waarden wordt overschreven, standaard of de gebruiker is gewijzigd, al aanwezig in het gegevensarchief.</xref:System.Configuration.LocalFileSettingsProvider>       DefaultSettingValueAttribute vereist dat de standaardwaarde kan worden weergegeven als een tekenreeks. Instellingen van XML-serialisatie kunnen niet als gevolg hiervan een standaardwaarde opgegeven met behulp van dit kenmerk hebben. Sommige providers kunnen ervoor kiezen ter ondersteuning van meerdere serialisatie-schema&quot;s die kunnen worden opgegeven tijdens de compilatie met behulp van de <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>      > [!CAUTION] > De standaardwaarden die is opgegeven door dit kenmerk worden opgeslagen als tekst zonder opmaak in het resulterende gecompileerde .exe- of DLL-bestand. Deze standaardwaarden zijn daarom inherent onveilig."
  example:
  - "The following code example demonstrates the use of the DefaultSettingValueAttribute applied to three of the four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The first three of these form properties have default values associated with them.  \n  \n The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.d_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.d_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class DefaultSettingValueAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een exemplaar van de <xref href=&quot;System.Configuration.DefaultSettingValueAttribute&quot;> </xref> klasse."
  remarks: "De opgegeven tekenreeks moet een waarde die compatibel is met het serialisatiemechanisme voor beschikbaar die zijn gekoppeld aan het eigenschapstype. Bijvoorbeeld, als de eigenschap is van het type <xref:System.Drawing.Color>, en vervolgens een `value` van `&quot;Azure&quot;` kunnen worden gebruikt.</xref:System.Drawing.Color>      > [!CAUTION] > De standaardwaarden die is opgegeven door dit kenmerk worden opgeslagen als tekst zonder opmaak in het resulterende gecompileerde .exe- of DLL-bestand. Deze standaardwaarden zijn daarom inherent onveilig."
  syntax:
    content: public DefaultSettingValueAttribute (string value);
    parameters:
    - id: value
      type: System.String
      description: "Een <xref:System.String>die staat voor de standaardwaarde voor de eigenschap.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  id: Value
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee wordt de standaardwaarde voor de eigenschap voor instellingen van toepassing."
  remarks: "De eigenschap Value is ingesteld in de <xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>constructor.</xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>       Instellen van providers ondersteunen mogelijk meerdere serialisatie-schema&quot;s die kunnen worden opgegeven met de <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>"
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>die staat voor de standaardwaarde voor de eigenschap.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute
- uid: System.Configuration.DefaultSettingValueAttribute.Value*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
