### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.SupportedRuntimeMissingException
  id: SupportedRuntimeMissingException
  children:
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  langs:
  - csharp
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException
  fullName: System.Deployment.Application.SupportedRuntimeMissingException
  type: Class
  summary: "Deze uitzondering wordt gegenereerd wanneer een runtimeversie die compatibel is met deze toepassing kan niet worden gevonden."
  syntax:
    content: 'public class SupportedRuntimeMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> klasse met een systeem geleverd bericht met een beschrijving van de fout."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A>eigenschap van het nieuwe exemplaar op een systeem geleverd bericht die beschrijft de fout, zoals &quot;Runtime ontbreekt uitzondering&quot;.</xref:System.Exception.Message%2A> Dit bericht wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException ();
    parameters: []
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout."
  remarks: "De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> klasse met de geserialiseerde gegevens."
  remarks: "Deze constructor is aangeroepen tijdens de deserialisatie op het object exception verzonden via een stroom opnieuw samenstellen."
  syntax:
    content: protected SupportedRuntimeMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "De contextuele informatie over de bron- of doelserver."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException%2A>eigenschap.</xref:System.Exception.InnerException%2A> De <xref:System.Exception.InnerException%2A>eigenschap dezelfde waarde die is doorgegeven aan de constructor of `null` als de <xref:System.Exception.InnerException%2A>eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering. Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> klasse met de geserialiseerde gegevens."
  remarks: "Deze constructor is aangeroepen tijdens de deserialisatie op het object exception verzonden via een stroom opnieuw samenstellen."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "De contextuele informatie over de bron- of doelserver."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  id: SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u de versie van de runtime waar deze toepassing kunt installeren en uitvoeren."
  syntax:
    content: public string SupportedRuntimeVersion { get; }
    return:
      type: System.String
      description: "Een tekenreeks zijn met het nummer van de runtime-versie."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: SupportedRuntimeMissingException.GetObjectData
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
