### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  id: TimeSpanMinutesOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  type: Class
  summary: "Converteert een <xref:System.TimeSpan>uitgedrukt in minuten, of als een oneindige standaard tijdsspanne</xref:System.TimeSpan>"
  remarks: "Dit type is, net als alle andere configuratie converter typen, converteert tekenreeksen gevonden in het configuratiebestand naar en van de bijbehorende eigenschappen sterk getypeerde.       In het bijzonder de klasse TimeSpanMinutesOrInfiniteConverter converteert <xref:System.String>minuten, toegewezen aan een configuratie-eigenschap op <xref:System.TimeSpan>minuten en vice versa.</xref:System.TimeSpan> </xref:System.String> Als de configuratie-eigenschap heeft een <xref:System.String>waarde van &quot;oneindig&quot;, wordt deze waarde converteert <xref:System.TimeSpan>en vice versa.</xref:System.TimeSpan> </xref:System.String>       De oneindig <xref:System.TimeSpan>waarde wordt vertegenwoordigd door de <xref:System.TimeSpan.MaxValue>opsommingswaarde.</xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanMinutesOrInfiniteConverter : System.Configuration.TimeSpanMinutesConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanMinutesConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.TimeSpanMinutesOrInfiniteConverter&quot;> </xref> klasse."
  remarks: "Normaal gesproken gebruikt u de typen van de converter geleverd door het systeem. De enige keer dat u wilt gebruiken, de constructor TimeSpanMinutesOrInfiniteConverter is bij het maken van uw eigen conversietype."
  syntax:
    content: public TimeSpanMinutesOrInfiniteConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converteert een <xref:System.String>op een <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Het systeem wordt de methode ConverterenVan bij het lezen van een configuratiebestand om te zetten een <xref:System.String>van waarde naar <xref:System.TimeSpan>, of <xref:System.String>&quot;infinite&quot; tot <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "De <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> object dat wordt gebruikt voor conversie."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "De <xref:System.Globalization.CultureInfo>object dat wordt gebruikt tijdens de conversie.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "De <xref:System.String>object converteren.</xref:System.String>"
    return:
      type: System.Object
      description: "De <xref:System.TimeSpan.MaxValue>Als de <code> data </code> -parameter is de <xref:System.String>&quot;oneindig&quot;, anders wordt de <xref:System.TimeSpan>die vertegenwoordigt de <code> data </code> parameter in minuten.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converteert een <xref:System.TimeSpan>op een <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Het systeem wordt de ConvertTo-methode bij het schrijven naar een configuratiebestand om te zetten van een <xref:System.TimeSpan>waarde of <xref:System.TimeSpan.MaxValue>een <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "De <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> object dat wordt gebruikt voor conversie."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "De <xref:System.Globalization.CultureInfo>object dat wordt gebruikt tijdens de conversie.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "De waarde te converteren."
    - id: type
      type: System.Type
      description: "Het conversietype."
    return:
      type: System.Object
      description: "De <xref:System.String>&quot;oneindig&quot; als de <code> value </code> parameter <xref:System.TimeSpan.MaxValue>; anders wordt de <xref:System.String>die vertegenwoordigt de <code> value </code> parameter in minuten.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: System.Configuration.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo
