### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowEnvironment
  id: WorkflowEnvironment
  children:
  - System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  - System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  langs:
  - csharp
  name: WorkflowEnvironment
  nameWithType: WorkflowEnvironment
  fullName: System.Workflow.Runtime.WorkflowEnvironment
  type: Class
  summary: "Hiermee geeft u de transactionele omgeving van het werkstroomexemplaar dat wordt uitgevoerd op de huidige thread."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]De WorkflowEnvironment vertegenwoordigt de transactionele omgeving van het werkstroomexemplaar dat wordt uitgevoerd op de huidige thread. WorkflowEnvironment heeft twee eigenschappen: de <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>eigenschap, dit wordt de huidige werkbatch en biedt een host of op een host-service om deel te nemen in de huidige transactie door toe te voegen <xref:System.Workflow.Runtime.IPendingWork>items aan deze eigenschap; en de <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A>eigenschap waarmee de <xref:System.Guid>van het werkstroomexemplaar dat momenteel wordt uitgevoerd op deze thread.</xref:System.Guid> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A> </xref:System.Workflow.Runtime.IPendingWork> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public static class WorkflowEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  id: WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Hiermee haalt u de huidige werkbatch."
  remarks: "De eigenschap WorkBatch kunnen hosts of hostservices om deel te nemen in de huidige transactie door in behandeling werkitems toe te voegen aan de huidige werkbatch. Een host of een host-service die wil deelnemen aan de huidige transactie moet worden geïmplementeerd de <xref:System.Workflow.Runtime.IPendingWork>interface en gebruik <xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName>in behandeling werkitems toevoegen aan WorkBatch.</xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName> </xref:System.Workflow.Runtime.IPendingWork> Duurzame services moeten items toevoegen aan WorkBatch de status van hun gegevensarchieven om consistent te houden met de status van het workflowexemplaar. De duurzame services out of box <xref:System.Workflow.Runtime.Tracking.SqlTrackingService>en <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService>, beide deze functionaliteit kunnen worden geïmplementeerd.</xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> </xref:System.Workflow.Runtime.Tracking.SqlTrackingService>"
  syntax:
    content: public static System.Workflow.Runtime.IWorkBatch WorkBatch { get; }
    return:
      type: System.Workflow.Runtime.IWorkBatch
      description: "De <xref href=&quot;System.Workflow.Runtime.IWorkBatch&quot;> </xref> die staat voor de huidige werkbatch."
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  id: WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Haalt de <xref:System.Guid>van het workflowexemplaar gekoppeld aan de huidige thread.</xref:System.Guid>"
  remarks: "WorkflowInstanceId bevat de <xref:System.Guid>van het werkstroomexemplaar dat momenteel wordt uitgevoerd in deze thread.</xref:System.Guid> Wanneer de code wordt uitgevoerd vanuit een workflow-thread, krijgt u de <xref:System.Guid>van het workflowexemplaar via de eigenschap WorkflowInstanceId.</xref:System.Guid> Bijvoorbeeld, als uw code in een service die wordt aangeroepen door een activiteit, WorkflowInstanceId bieden <xref:System.Guid>van het workflowexemplaar voor de activiteit aanroepen.</xref:System.Guid>"
  syntax:
    content: public static Guid WorkflowInstanceId { get; }
    return:
      type: System.Guid
      description: "De <xref:System.Guid>die het huidige werkstroomexemplaar van de identificeert.</xref:System.Guid>"
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.IWorkBatch
  parent: System.Workflow.Runtime
  isExternal: false
  name: IWorkBatch
  nameWithType: IWorkBatch
  fullName: System.Workflow.Runtime.IWorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
