### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyValidation
  id: MachineKeyValidation
  children:
  - System.Web.Configuration.MachineKeyValidation.AES
  - System.Web.Configuration.MachineKeyValidation.Custom
  - System.Web.Configuration.MachineKeyValidation.HMACSHA256
  - System.Web.Configuration.MachineKeyValidation.HMACSHA384
  - System.Web.Configuration.MachineKeyValidation.HMACSHA512
  - System.Web.Configuration.MachineKeyValidation.MD5
  - System.Web.Configuration.MachineKeyValidation.SHA1
  - System.Web.Configuration.MachineKeyValidation.TripleDES
  langs:
  - csharp
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
  type: Enum
  summary: "Hiermee geeft u het hash-algoritme dat ASP.NET gebruikt voor formulierverificatie en voor het valideren van gegevens van de status en voor de identificatie van de status out of process-sessie."
  remarks: "ASP.NET gebruikt een hash op basis van een message authentication code (HMAC) om te detecteren of gegevens die worden gebruikt voor de verificatie of de weergave status formulieren is geknoeid met. Het HMAC wordt gegenereerd wanneer de weergave status inhoud wordt gemaakt en de HMAC is ingeschakeld op de volgende aanvragen. Het HMAC helpt te bepalen of iemand gegevens die worden verzonden tussen de server en de client is gewijzigd, maar de gegevens kunnen worden gelezen door iedereen doorheen via Internet tenzij ze zijn ook versleuteld ASP.NET. Standaard wordt de weergavestatus gevalideerd maar niet versleuteld. Zie voor meer informatie <xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>en <xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A>.</xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A> </xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>       De opsomming MachineKeyValidation kunt u de algoritme die ASP.NET maakt de HMAC opgeven. De standaardwaarde is HMACSHA256. ASP.NET gebruikt de waarde van de <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>eigenschap met de geselecteerde algoritme voor het genereren van de HMAC.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>"
  example:
  - "The following code example shows how to use the MachineKeyValidation enumeration. In the example, `configSection` is an instance of <xref:System.Web.Configuration.MachineKeySection>.This code example is part of a larger example provided for the <xref:System.Web.Configuration.MachineKeySection> class.  \n  \n [!code-vb[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/visualbasic/t-system.web.configurati_93_1.vb)]\n [!code-cs[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/csharp/t-system.web.configurati_93_1.cs)]"
  syntax:
    content: public enum MachineKeyValidation
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.AES
  id: AES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET gebruikt de <xref uid=&quot;langword_csharp_AES&quot; name=&quot;AES&quot; href=&quot;&quot;> </xref> versleutelingsalgoritme (Rijndael)."
  remarks: "Selecteer deze optie als u wilt versleutelen weergavestatus in uw webtoepassing. Als u deze optie kiest de <xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>eigenschap wordt gebruikt voor versleuteling en ontsleuteling, en de `HMACSHA1` hash-algoritme wordt gebruikt met de <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>eigenschap voor validatie.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A> </xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>"
  syntax:
    content: AES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  id: Custom
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET een aangepaste hash-algoritme gebruikt."
  remarks: "Aangepaste hash-algoritme kan worden geïmplementeerd in een klasse die is afgeleid van <xref:System.Security.Cryptography.KeyedHashAlgorithm>.</xref:System.Security.Cryptography.KeyedHashAlgorithm>       De aangepaste algoritme wordt doorgaans declaratief opgegeven in het validatiekenmerk van het element in de indeling `alg:` *algorithm_name*. Zie voor meer informatie over het opgeven van een aangepaste algoritme in de code de <xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>eigenschap.</xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>"
  syntax:
    content: Custom
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  id: HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET gebruikt de <xref uid=&quot;langword_csharp_HMACSHA256&quot; name=&quot;HMACSHA256&quot; href=&quot;&quot;> </xref> hash-algoritme.  Dit is de standaardwaarde."
  remarks: '`HMACSHA256`is een SHA2 hash-algoritme dat een 256-bits hash-code genereert.'
  syntax:
    content: HMACSHA256
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  id: HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET gebruikt de <xref uid=&quot;langword_csharp_HMACSHA384&quot; name=&quot;HMACSHA384&quot; href=&quot;&quot;> </xref> hash-algoritme."
  remarks: '`HMACSHA384`is een SHA2 hash-algoritme dat een 384 bits hash-code genereert. Deze optie is beschikbaar voor toepassingen waarvoor een betere beveiliging dan is opgegeven door de `HMACSHA256`algoritme.'
  syntax:
    content: HMACSHA384
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  id: HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET gebruikt de <xref uid=&quot;langword_csharp_HMACSHA512&quot; name=&quot;HMACSHA512&quot; href=&quot;&quot;> </xref> hash-algoritme."
  remarks: '`HMACSHA512`is een SHA2 hash-algoritme dat een 512-bits hash-code genereert. Deze optie is beschikbaar voor toepassingen waarvoor een betere beveiliging dan is opgegeven door de `HMACSHA384` algoritme.'
  syntax:
    content: HMACSHA512
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  id: MD5
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET het Message Digest 5 gebruikt (<xref uid=&quot;langword_csharp_MD5&quot; name=&quot;MD5&quot; href=&quot;&quot;></xref>) hash-algoritme."
  remarks: '`MD5`is een hash-algoritme dat een hash-128-bits waarde genereert. Deze optie is opgenomen voor oudere toepassing en mag alleen worden geselecteerd als compatibiliteit met eerdere versies van ASP.NET vereist is.'
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  id: SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET gebruikt de <xref uid=&quot;langword_csharp_HMACSHA1&quot; name=&quot;HMACSHA1&quot; href=&quot;&quot;> </xref> hash-algoritme."
  remarks: '`HMACSHA1`een hash-algoritme dat een 160-bits hash-waarde genereert is. Deze optie is opgenomen voor oudere toepassing en mag alleen worden geselecteerd als compatibiliteit met eerdere versies van ASP.NET vereist is.'
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  id: TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat ASP.NET de TripleDES gebruikt (<xref uid=&quot;langword_csharp_3DES&quot; name=&quot;3DES&quot; href=&quot;&quot;></xref>) versleutelingsalgoritme."
  remarks: "TripleDES is een algoritme die alleen gebruikt wordt als u opgeven dat de weergavestatus is versleuteld. Deze optie is opgenomen voor oudere toepassing en mag alleen worden geselecteerd als compatibiliteit met eerdere versies van ASP.NET vereist is."
  syntax:
    content: TripleDES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyValidation.AES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
- uid: System.Web.Configuration.MachineKeyValidation
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
