### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  id: ProcessModelComImpersonationLevel
  children:
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  langs:
  - csharp
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
  type: Enum
  summary: "Hiermee geeft u het verificatieniveau voor COM-beveiliging."
  remarks: "De klasse ProcessModelComImpersonationLevel inventariseert de waarden voor gebruik bij het instellen van de <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>eigenschap.</xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>       De standaardwaarde is imiteren."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/csharp/t-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/visualbasic/t-system.web.configurati_52_1.vb)]"
  syntax:
    content: public enum ProcessModelComImpersonationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  id: Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Geeft aan dat de client anoniem voor de server. Dit veld is constante."
  remarks: "De server kan de client te imiteren, maar het imitatietoken bevatten geen informatie."
  syntax:
    content: Anonymous
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat het imitatieniveau wordt bepaald door DCOM. Dit veld is constante."
  remarks: "DCOM bepaalt het imitatieniveau normale beveiligingsonderhandeling wordt gebruikt."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  id: Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op de server-proces kan de beveiligingscontext van de client namens de client worden geïmiteerd. Dit veld is constante."
  remarks: "Het server-proces kan uitgaande oproepen naar andere servers namens de client, met behulp van cloaking maken. De server kan de beveiligingscontext van de client op andere computers gebruiken voor toegang tot lokale en externe bronnen als de client. Wanneer het proces de client op dit niveau te imiteren is, kan het imitatietoken worden doorgegeven via een willekeurig aantal grenzen van de computer."
  syntax:
    content: Delegate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  id: Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat de server de identiteit van de client kan verkrijgen. Dit veld is constante."
  remarks: "De server zich voordoen als de client voor het controleren van de access control toegangsbeheerlijst (ACL), maar heeft geen toegang tot systeemobjecten als de client."
  syntax:
    content: Identify
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  id: Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op de server-proces kan de beveiligingscontext van de client namens de client worden geïmiteerd. Dit veld is constante."
  remarks: "Dit niveau van imitatie kan worden gebruikt voor toegang tot lokale bronnen zoals bestanden. Wanneer het proces de client op dit niveau te imiteren is, kan het imitatietoken grens slechts één computer worden doorgegeven."
  syntax:
    content: Impersonate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
