### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageability
  id: SettingsManageability
  children:
  - System.Configuration.SettingsManageability.Roaming
  langs:
  - csharp
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
  type: Enum
  summary: "Bevat de waarden voor het aangeven van welke services beschikbaar moeten worden gesteld voor toepassingsinstellingen."
  remarks: "De ttribute wordt gebruikt om de eigenschappen voor afzonderlijke toepassingen en eigenschapgroepen om aan te geven dat speciale, vooraf gedefinieerde services worden opgegeven voor deze toepassing. De opsomming SettingsManageability zijn de services die beschikbaar zijn. De meeste van deze services worden geleverd door de Windows-besturingssysteem."
  syntax:
    content: public enum SettingsManageability
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsManageability.Roaming
  id: Roaming
  parent: System.Configuration.SettingsManageability
  langs:
  - csharp
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee schakelt u de toepassingsinstellingen in zwervende gebruikersprofielen worden opgeslagen. Zie voor meer informatie over zwervende gebruikersprofielen [geïsoleerde opslag en Roaming](http://msdn.microsoft.com/en-us/d3cca593-4521-408d-b323-ea398d226de3)."
  syntax:
    content: Roaming
    return:
      type: System.Configuration.SettingsManageability
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsManageability.Roaming
  parent: System.Configuration.SettingsManageability
  isExternal: false
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
