### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProvider
  id: ProtectedConfigurationProvider
  children:
  - System.Configuration.ProtectedConfigurationProvider.#ctor
  - System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  langs:
  - csharp
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
  type: Class
  summary: "Is de basisklasse voor het maken van providers voor het versleutelen en ontsleutelen van gegevens van beveiligde-configuratie."
  remarks: "U kunt de secties van een configuratiebestand ter bescherming van gevoelige gegevens die door uw toepassing gebruikt versleutelen. Dit verbetert de beveiliging door waardoor het moeilijk voor onbevoegde toegang is zelfs als een aanvaller toegang tot uw configuratiebestand krijgt.       Het .NET Framework bevat twee beveiligde configuratieproviders die kunnen worden gebruikt voor het versleutelen van de secties van een configuratiebestand. De <xref:System.Configuration.RsaProtectedConfigurationProvider>klasse gebruikt de <xref:System.Security.Cryptography.RSACryptoServiceProvider>voor het versleutelen van configuratiesecties.</xref:System.Security.Cryptography.RSACryptoServiceProvider> </xref:System.Configuration.RsaProtectedConfigurationProvider> De <xref:System.Configuration.DpapiProtectedConfigurationProvider>klasse Windows Data Protection API (DPAPI) gebruikt voor het versleutelen van configuratiesecties.</xref:System.Configuration.DpapiProtectedConfigurationProvider>       U hebt mogelijk een vereiste voor het versleutelen van gevoelige gegevens met behulp van een algoritme dan de providers RSA of DPAPI. In dit geval kunt u uw eigen aangepaste beveiligde configuratie-provider maken. De ProtectedConfigurationProvider is een abstracte basisklasse die u eigenschappen overnemen moet van uw eigen provider beveiligd-configuratie te maken.       Of u een standaard of een aangepaste provider gebruiken, moet u ervoor zorgen dat is geconfigureerd met de `add` -element in de `providers` sectie van de `configProtectedData` configuratiesectie. (Zie het volgende voorbeeld.)       Zie voor meer informatie [uitvoering van een Configuratieprovider beveiligd](~/add/includes/ajax-current-ext-md.md).      > [!NOTE] > Wanneer ASP.NET wordt van versleutelde configuratiegegevens aangetroffen, wordt deze decodering transparant met de geconfigureerde provider gecontroleerd. Er is geen actie vereist aan uw kant dan om ervoor te zorgen dat u de vereiste provider configureren."
  example:
  - "The following example shows how to implement a custom ProtectedConfigurationProvider.  \n  \n To be able to configure this provider, as shown in the next configuration excerpt, you must install it in the Global Assembly Cache (GAC). Refer to [Implementing a Protected Configuration Provider](../Topic/Implementing%20a%20Protected%20Configuration%20Provider.md) for more information.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#1](~/add/codesnippet/csharp/t-system.configuration.p_7_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#1](~/add/codesnippet/visualbasic/t-system.configuration.p_7_1.vb)]  \n  \n The following example shows how to use the previous custom ProtectedConfigurationProvider.  \n  \n [!code-vb[System.Configuration.UsingProtectedConfigurationProvider#11](~/add/codesnippet/visualbasic/t-system.configuration.p_7_2.vb)]\n [!code-cs[System.Configuration.UsingProtectedConfigurationProvider#11](~/add/codesnippet/csharp/t-system.configuration.p_7_2.cs)]  \n  \n The following is an excerpt of the configuration file used by the above examples.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\" ?>  \n<configuration>  \n  \n  <configProtectedData >  \n    <providers>  \n      <clear />  \n      <add keyContainerName=\"pcKey.txt\"   \n        name=\"TripleDESProtectedConfigurationProvider\"  \ntype=\"Samples.Aspnet.TripleDESProtectedConfigurationProvider, protectedconfigurationproviderlib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79e01ae0f5cfc66f, processorArchitecture=MSIL\" />  \n    </providers>  \n  \n  </configProtectedData >  \n  \n  <connectionStrings>  \n    <add name=\"NorthwindConnectionString\"   \n      connectionString=\"Data Source=webnetue2;Initial Catalog=Northwind;User ID=aspnet_test;Password=test\"  \nproviderName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public abstract class ProtectedConfigurationProvider : System.Configuration.Provider.ProviderBase'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: ProtectedConfigurationProvider()
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  fullName: System.Configuration.ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> klasse met de standaardinstellingen."
  syntax:
    content: protected ProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "De doorgegeven ontsleutelt <xref href=&quot;System.Xml.XmlNode&quot;> </xref> object uit een configuratiebestand."
  remarks: ''
  example:
  - "The following example shows how to use Decrypt method to perform custom decryption.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#2](~/add/codesnippet/csharp/490b80fa-87ff-462a-bceb-_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#2](~/add/codesnippet/visualbasic/490b80fa-87ff-462a-bceb-_1.vb)]"
  syntax:
    content: public abstract System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: "De <xref href=&quot;System.Xml.XmlNode&quot;> </xref> object om te ontsleutelen."
    return:
      type: System.Xml.XmlNode
      description: "De <xref href=&quot;System.Xml.XmlNode&quot;> </xref> object met gegevens te ontsleutelen."
  overload: System.Configuration.ProtectedConfigurationProvider.Decrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "De doorgegeven versleutelt <xref href=&quot;System.Xml.XmlNode&quot;> </xref> object uit een configuratiebestand."
  remarks: ''
  example:
  - "The following example shows how to use Encrypt to perform custom encryption.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#3](~/add/codesnippet/csharp/1cc011d4-bc06-4499-99c2-_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#3](~/add/codesnippet/visualbasic/1cc011d4-bc06-4499-99c2-_1.vb)]"
  syntax:
    content: public abstract System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: "De <xref href=&quot;System.Xml.XmlNode&quot;> </xref> object om te versleutelen."
    return:
      type: System.Xml.XmlNode
      description: "De <xref href=&quot;System.Xml.XmlNode&quot;> </xref> -object dat versleutelde gegevens bevat."
  overload: System.Configuration.ProtectedConfigurationProvider.Encrypt*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: ProtectedConfigurationProvider()
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  fullName: System.Configuration.ProtectedConfigurationProvider.ProtectedConfigurationProvider()
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: ProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: ProtectedConfigurationProvider.Encrypt
