### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlReaderSettings
  id: XamlXmlReaderSettings
  children:
  - System.Xaml.XamlXmlReaderSettings.#ctor
  - System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  - System.Xaml.XamlXmlReaderSettings.CloseInput
  - System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  - System.Xaml.XamlXmlReaderSettings.XmlLang
  - System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  langs:
  - csharp
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
  type: Class
  summary: "Hiermee geeft u het verwerken van regels of de optie-instellingen voor de <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> XAML lezer implementatie."
  syntax:
    content: 'public class XamlXmlReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlXmlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  id: '#ctor(System.Xaml.XamlXmlReaderSettings)'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klasse door instellingen te kopiëren van een bestaand <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> object."
  syntax:
    content: public XamlXmlReaderSettings (System.Xaml.XamlXmlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlXmlReaderSettings
      description: "De bestaande <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> object om te kopiëren."
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de onderliggende stroom of tekst lezer moet worden gesloten wanneer de <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> is gesloten."
  syntax:
    content: public bool CloseInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de onderliggende stroom of lezer moet worden gesloten wanneer de <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> is gesloten, anders, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.CloseInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  id: SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die bepaalt of de lezer van de standaard verschillen moet <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> gedrag van hoe markup compatibiliteit inhoud wordt verwerkt."
  remarks: "De standaardwaarde voor het verwerken van gedrag voor compatibiliteit van de XML-opmaak in <xref:System.Xaml.XamlXmlReader>is dat de <xref:System.Xaml.XamlXmlReader>te gebruiken, zoals opgegeven voor de initialisatie, is die in een gemaakte interne helper-klasse.</xref:System.Xaml.XamlXmlReader> </xref:System.Xaml.XamlXmlReader> Deze helperklasse leest de opmaak compatibiliteit knooppunten afzonderlijk en voert in de knooppunten op basis van de compatibiliteit van de opmaak van de schemacontext.       Voorgestelde scenario&quot;s voor het instellen van SkipXmlCompatibilityProcessing voor `true` zijn:-u wilt behouden markup compatibiliteit inhoud in de primaire XAML-stroom.      -U hebt al de compatibiliteit markup verwerkt, omdat u een lezer die inhoud in line markup compatibiliteit kan worden verwerkt.      -U kiezen voor het negeren van XML-compatibiliteit overeenkomsten in uw implementatie van de XAML-lezer om redenen van prestaties."
  syntax:
    content: public bool SkipXmlCompatibilityProcessing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de gang worden gezet lezer rechtstreeks wordt gebruikt, wat betekent dat dat XML-compatibiliteit opmaak als onderdeel van de belangrijkste stroom wordt verwerkt en wordt niet beschouwd als compatibiliteit. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Als het standaardgedrag wordt gebruikt, welke processen XML-compatibiliteit afzonderlijk. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  id: XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van de waarde die de lezer kunt promoten instelt op schrijvers dat schrijven taal <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> kenmerken in de knooppunten."
  remarks: "De aanroeper is verantwoordelijk voor het om ervoor te zorgen dat de tekenreeks die u opgeeft geschikt is voor `xml:lang` gebruik."
  syntax:
    content: public string XmlLang { get; set; }
    return:
      type: System.String
      description: "De tekenreeks moet worden gebruikt voor mogelijke <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> uitvoer die is gebaseerd op de lezer."
  overload: System.Xaml.XamlXmlReaderSettings.XmlLang*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  id: XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Opgehaald of ingesteld van een waarde die bepaalt of een XAML-schrijvers schrijven Hiermee geeft u de XAML-lezer <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> kenmerken in de knooppunten. Als u dit gedrag, wordt deze informatie wordt doorgegeven via gedeelde schemacontext van XAML."
  remarks: "De concepten van XML-spaties zijn niet robuuste om toe te passen naar XAML en meestal worden genegeerd door de XAML lezers."
  syntax:
    content: public bool XmlSpacePreserve { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als schrijvers die worden verwerkt de XAML-knooppuntstroom kunnen schrijven `xml:space=&quot;preserve&quot;` in uitvoer. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> als <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> kenmerken in knooppunten kunnen worden geschreven."
  overload: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
- uid: System.Xaml.XamlXmlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
- uid: System.Xaml.XamlXmlReaderSettings.#ctor*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
