### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  id: XmlFormatExtensionPrefixAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  type: Class
  summary: "Geeft de XML-naamruimte en de XML-naamruimtevoorvoegsel moet worden gebruikt voor een indelingsextensie voor een beschrijving in een beschrijving van de service. Deze klasse kan niet worden overgenomen."
  remarks: "Een beschrijving van indelingsextensie breidt hoe een beschrijving van de service wordt gegenereerd voor een XML-webservice gemaakt met behulp van ASP.NET. Een beschrijving van indelingsextensie wordt in het bijzonder XML-elementen toegevoegd aan de servicebeschrijving. Dit is handig wanneer een SOAP-extensie wordt gemaakt om uit te voeren op de client en de server-zijde van een XML-webservice, zoals informatie over de SOAP-extensies niet in de beschrijving van de service wordt geplaatst. Als u informatie over de SOAP-extensie aan de servicebeschrijving toevoegt, kan een client interpreteren dat de specifieke SOAP-uitbreiding moet worden uitgevoerd. Een voorbeeld van een SOAP-extensie die moet worden uitgevoerd op de client en de server is een versleuteling SOAP-extensie. Als een versleuteling SOAP-extensie op alleen de server wordt uitgevoerd en deze retourwaarden worden versleuteld voordat ze worden verzonden naar de client, moet de client voor het ontsleutelen van het SOAP-bericht met de SOAP-extensie hebben. Anders wordt de client kan de retourwaarde niet verwerken.       Gebruik de volgende stappen voor het bouwen van een beschrijving van indelingsextensie: 1.  Een klasse die is afgeleid van <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension> bouwen      2.  Van toepassing een <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>aan de klasse en geef de Extensiepunten waarmee de beschrijving van indelingsextensie moet worden uitgevoerd.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Eventueel van toepassing een <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>aan de klasse en geef een lid in de klasse die als een nieuwe extensiepunt fungeert.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>      4.  Desgewenst een XmlFormatExtensionPrefixAttribute van toepassing op de klasse en de XML-naamruimtevoorvoegsel om te worden gekoppeld aan XML-elementen die worden gegenereerd door de indelingsextensie voor beschrijving opgeven.      5.  Configureren van de service beschrijving indeling uitbreiding om uit te voeren binnen de `serviceDescriptionFormatExtensionTypes` gedeelte van het configuratiebestand."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_2_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_2_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]

      public sealed class XmlFormatExtensionPrefixAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasse."
  syntax:
    content: public XmlFormatExtensionPrefixAttribute ();
    parameters: []
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasse, instellen van de XML-naamruimte en de XML-naamruimtevoorvoegsel voor een beschrijving van indelingsextensie."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/31a2fbe2-95e2-473f-8282-_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/31a2fbe2-95e2-473f-8282-_1.vb)]
  syntax:
    content: public XmlFormatExtensionPrefixAttribute (string prefix, string ns);
    parameters:
    - id: prefix
      type: System.String
      description: "De XML-naamruimtevoorvoegsel die zijn gekoppeld aan een beschrijving van indelingsextensie."
    - id: ns
      type: System.String
      description: "De XML-naamruimte die is gekoppeld aan een beschrijving van indelingsextensie."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  id: Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van de XML-naamruimte die is gekoppeld aan een beschrijving van indelingsextensie."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_4_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_4_1.vb)]
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "De XML-naamruimte die is gekoppeld aan een beschrijving van indelingsextensie."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  id: Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van het voorvoegsel van de XML-naamruimte die is gekoppeld aan een beschrijving van indelingsextensie."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_0_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_0_1.vb)]
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "De XML-naamruimtevoorvoegsel die zijn gekoppeld aan een beschrijving van indelingsextensie."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
