### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidator
  id: SubclassTypeValidator
  children:
  - System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  - System.Configuration.SubclassTypeValidator.Validate(System.Object)
  langs:
  - csharp
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator
  fullName: System.Configuration.SubclassTypeValidator
  type: Class
  summary: "Wordt gecontroleerd of een object een afgeleide klasse van een bepaald type."
  remarks: "De klasse SubclassTypeValidator wordt gebruikt om ervoor te zorgen dat een object aan bepaalde criteria voldoet. De criteria voor validatie wordt ingesteld wanneer een exemplaar van de klasse SubclassTypeValidator is gemaakt.       De <xref:System.Configuration.SubclassTypeValidator.CanValidate%2A>methode wordt bepaald of het type van het object dat wordt gevalideerd in feite een <xref:System.Type>.</xref:System.Type> </xref:System.Configuration.SubclassTypeValidator.CanValidate%2A> Het object dat wordt gevalideerd wordt doorgegeven als een parameter van de <xref:System.Configuration.SubclassTypeValidator.Validate%2A>methode.</xref:System.Configuration.SubclassTypeValidator.Validate%2A> Deze methode wordt eerst gecontroleerd of het object valideren geen is `null`, en vervolgens wordt gecontroleerd of het object een afgeleide klasse van het verwachte type is."
  syntax:
    content: 'public sealed class SubclassTypeValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SubclassTypeValidator&quot;> </xref> klasse."
  remarks: "De criteria voor de validatie is gebaseerd op de `baseClass` parameter."
  syntax:
    content: public SubclassTypeValidator (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "De basisklasse voor de validatie."
  overload: System.Configuration.SubclassTypeValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>baseClass</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of een object kan worden gevalideerd op basis van het type."
  remarks: "De methode CanValidate bepaalt of het type van het object dat wordt gevalideerd in feite een <xref:System.Type>.</xref:System.Type>"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Het objecttype."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de <code> type </code> parameter overeenkomt met een type dat gevalideerd, anders wordt worden kan <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SubclassTypeValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of de waarde van een object geldig is."
  remarks: "Wanneer een exemplaar van de <xref:System.Configuration.SubclassTypeValidator>klasse is gemaakt, de basisklasse beschikbaar wordt gesteld en gebruikt als evaluatiecriteria.</xref:System.Configuration.SubclassTypeValidator> Het object te valideren wordt als een parameter van de methode Validate doorgegeven. Deze methode voert de validatiecontrole tussen de basisklasse en de parameter-object."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "De objectwaarde."
  overload: System.Configuration.SubclassTypeValidator.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>value</code>is niet van een <xref:System.Type> die kunnen worden afgeleid van <code>baseClass</code> zoals gedefinieerd in de constructor."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.SubclassTypeValidator.#ctor*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator.SubclassTypeValidator
- uid: System.Configuration.SubclassTypeValidator.CanValidate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate
  nameWithType: SubclassTypeValidator.CanValidate
- uid: System.Configuration.SubclassTypeValidator.Validate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate
  nameWithType: SubclassTypeValidator.Validate
