### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.RoleService
  id: RoleService
  children:
  - System.Web.ApplicationServices.RoleService.#ctor
  - System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser
  - System.Web.ApplicationServices.RoleService.IsCurrentUserInRole(System.String)
  - System.Web.ApplicationServices.RoleService.SelectingProvider
  langs:
  - csharp
  name: RoleService
  nameWithType: RoleService
  fullName: System.Web.ApplicationServices.RoleService
  type: Class
  summary: "Geeft toegang tot de ASP.NET-rolprovider als een WCF-webservice."
  remarks: "Het object RoleService kunt u lezen gebruikersrollen via een Windows Communication Foundation (WCF)-service. Voor het gebruik van de functieservice, moet u de functieservice op een webserver inschakelen en sluit vervolgens een WCF-compatibele client-toepassing met de webservice. Zie voor meer informatie over het configureren van de functieservice [hoe: inschakelen van de WCF-functieservice](~/add/includes/ajax-current-ext-md.md).       De gebruiker moet worden geverifieerd om te lezen van rollen van de gebruiker. De functieservice werkt met elk soort ASP.NET-verificatie. Zie voor meer informatie over het registreren van gebruikers in via een WCF-service [Windows Communication Foundation Authentication Service Overview](~/add/includes/ajax-current-ext-md.md).       De klasse RoleService beschrijft de twee methoden die u moeten alleen worden benaderd via een WCF-service: de <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>methode en de <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>methode.</xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> De <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>methode retourneert de rollen voor de aangemelde gebruiker.</xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> De <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>methode bepaalt of de gebruiker in een opgegeven rol.</xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>       Het object RoleService worden gegeven de <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>gebeurtenis.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> U maakt een gebeurtenis-handler voor de <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>gebeurtenis selecteren welke rolprovider moet worden gebruikt tijdens de uitvoering.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       Zie voor een voorbeeld van het gebruik van de WCF-functieservice van een consoletoepassing [Walkthrough: ASP.NET-toepassingsservices](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.ServiceModel.Activation.AspNetCompatibilityRequirements(RequirementsMode=System.ServiceModel.Activation.AspNetCompatibilityRequirementsMode.Required)]

      [System.ServiceModel.ServiceBehavior(ConcurrencyMode=System.ServiceModel.ConcurrencyMode.Multiple, InstanceContextMode=System.ServiceModel.InstanceContextMode.Single, Namespace="http://asp.net/ApplicationServices/v200")]

      [System.ServiceModel.ServiceContract(Namespace="http://asp.net/ApplicationServices/v200")]

      public class RoleService
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.RoleService.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.RoleService
  langs:
  - csharp
  name: RoleService()
  nameWithType: RoleService.RoleService()
  fullName: System.Web.ApplicationServices.RoleService.RoleService()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.ApplicationServices.RoleService&quot;> </xref> klasse."
  syntax:
    content: public RoleService ();
    parameters: []
  overload: System.Web.ApplicationServices.RoleService.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser
  id: GetRolesForCurrentUser
  parent: System.Web.ApplicationServices.RoleService
  langs:
  - csharp
  name: GetRolesForCurrentUser()
  nameWithType: RoleService.GetRolesForCurrentUser()
  fullName: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser()
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Retourneert de rollen voor de aangemelde gebruiker."
  remarks: "De methode GetRolesForCurrentUser retourneert alle functies voor de gebruiker. U kunt de GetRolesForCurrentUser-methode gebruiken wanneer u moet controleren of behouden van alle rollen van de gebruiker om te bepalen welke resources zijn beschikbaar voor de gebruiker. U kunt deze methode gebruiken om te voorkomen dat meerdere aanroepen naar de <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>methode.</xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>       Aanroepen van de methode GetRolesForCurrentUser verhoogt de <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>gebeurtenis.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>      > [!NOTE] > Roep de methode GetRolesForCurrentUser niet uit de code die wordt uitgevoerd op de webserver. U aanroepen de methode GetRolesForCurrentUser uitsluitend als onderdeel van een WCF-service. Zie voor meer informatie over het lezen van gebruikersrollen in code die wordt uitgevoerd op de webserver de <xref:System.Web.Security.Roles.GetRolesForUser%2A>methode.</xref:System.Web.Security.Roles.GetRolesForUser%2A>"
  syntax:
    content: public string[] GetRolesForCurrentUser ();
    parameters: []
    return:
      type: System.String[]
      description: "Een matrix met de namen van de functies die de gebruiker behoort."
  overload: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser*
  exceptions:
  - type: System.Configuration.Provider.ProviderException
    commentId: T:System.Configuration.Provider.ProviderException
    description: "Rollenbeheer is niet ingeschakeld."
  platform:
  - net462
- uid: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole(System.String)
  id: IsCurrentUserInRole(System.String)
  parent: System.Web.ApplicationServices.RoleService
  langs:
  - csharp
  name: IsCurrentUserInRole(String)
  nameWithType: RoleService.IsCurrentUserInRole(String)
  fullName: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole(String)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hiermee wordt bepaald of de aangemelde gebruiker tot de opgegeven rol behoort."
  remarks: "De methode IsCurrentUserInRole gecontroleerd of de aangemelde gebruiker tot de opgegeven rol behoort. De methode IsCurrentUserInRole genereert de <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>gebeurtenis.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>      > [!NOTE] > Roep de methode IsCurrentUserInRole niet uit de code die wordt uitgevoerd op de webserver. U aanroepen de methode IsCurrentUserInRole uitsluitend als onderdeel van een WCF-service. Zie voor meer informatie over het controleren of een gebruiker tot de opgegeven groep behoort van een code wordt uitgevoerd op de webserver de <xref:System.Web.Security.Roles.IsUserInRole%2A>methode.</xref:System.Web.Security.Roles.IsUserInRole%2A>"
  syntax:
    content: public bool IsCurrentUserInRole (string role);
    parameters:
    - id: role
      type: System.String
      description: "De naam van de rol om te controleren."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de gebruiker in de opgegeven rol; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>role</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> of de gebruiker niet aangemeld."
  - type: System.Configuration.Provider.ProviderException
    commentId: T:System.Configuration.Provider.ProviderException
    description: "Rollenbeheer is niet ingeschakeld."
  platform:
  - net462
- uid: System.Web.ApplicationServices.RoleService.SelectingProvider
  id: SelectingProvider
  parent: System.Web.ApplicationServices.RoleService
  langs:
  - csharp
  name: SelectingProvider
  nameWithType: RoleService.SelectingProvider
  fullName: System.Web.ApplicationServices.RoleService.SelectingProvider
  type: Event
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Deze gebeurtenis treedt op wanneer een <xref href=&quot;System.Web.ApplicationServices.RoleService&quot;> </xref> exemplaar bepaalt welke rolprovider moet worden gebruikt voor het controleren van de rollen van de gebruiker."
  remarks: "De <xref:System.Web.ApplicationServices.RoleService>klasse de SelectingProvider gebeurtenis bij het bepalen van welke rolprovider moet worden gebruikt om op te halen van de rollen van de gebruiker wordt gegeven.</xref:System.Web.ApplicationServices.RoleService> U kunt een gebeurtenis-handler voor de gebeurtenis SelectingProvider selecteren tijdens de uitvoering van welke rolprovider moet worden gebruikt."
  example:
  - "The following example shows how to bind an event handler to the SelectingProvider event in the Global.asax file. The event handler determines at run time which role provider to use, based on the user name.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/e-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/e-system.web.application_3_1.asax)]"
  syntax:
    content: public static event EventHandler<System.Web.ApplicationServices.SelectingProviderEventArgs> SelectingProvider;
    return:
      type: System.EventHandler{System.Web.ApplicationServices.SelectingProviderEventArgs}
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Provider.ProviderException
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderException
  nameWithType: ProviderException
  fullName: System.Configuration.Provider.ProviderException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Web.ApplicationServices.RoleService.#ctor
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: RoleService()
  nameWithType: RoleService.RoleService()
  fullName: System.Web.ApplicationServices.RoleService.RoleService()
- uid: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: GetRolesForCurrentUser()
  nameWithType: RoleService.GetRolesForCurrentUser()
  fullName: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser()
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole(System.String)
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: IsCurrentUserInRole(String)
  nameWithType: RoleService.IsCurrentUserInRole(String)
  fullName: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.RoleService.SelectingProvider
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: SelectingProvider
  nameWithType: RoleService.SelectingProvider
  fullName: System.Web.ApplicationServices.RoleService.SelectingProvider
- uid: System.EventHandler{System.Web.ApplicationServices.SelectingProviderEventArgs}
  parent: System
  isExternal: true
  name: EventHandler<SelectingProviderEventArgs>
  nameWithType: EventHandler<SelectingProviderEventArgs>
  fullName: System.EventHandler<System.Web.ApplicationServices.SelectingProviderEventArgs>
  spec.csharp:
  - uid: System.EventHandler`1
    name: EventHandler
    nameWithType: EventHandler
    fullName: EventHandler<System.Web.ApplicationServices.SelectingProviderEventArgs>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Web.ApplicationServices.SelectingProviderEventArgs
    name: SelectingProviderEventArgs
    nameWithType: SelectingProviderEventArgs
    fullName: SelectingProviderEventArgs
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ApplicationServices.RoleService.#ctor*
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: RoleService
  nameWithType: RoleService.RoleService
- uid: System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser*
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: GetRolesForCurrentUser
  nameWithType: RoleService.GetRolesForCurrentUser
- uid: System.Web.ApplicationServices.RoleService.IsCurrentUserInRole*
  parent: System.Web.ApplicationServices.RoleService
  isExternal: false
  name: IsCurrentUserInRole
  nameWithType: RoleService.IsCurrentUserInRole
