### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsMode
  id: CustomErrorsMode
  children:
  - System.Web.Configuration.CustomErrorsMode.Off
  - System.Web.Configuration.CustomErrorsMode.On
  - System.Web.Configuration.CustomErrorsMode.RemoteOnly
  langs:
  - csharp
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
  type: Enum
  summary: "Hiermee geeft u de waarden voor de aangepaste fouten modaliteit."
  remarks: "De CustomErrorsMode inventariseert de waarden die u gebruiken kunt bij het instellen van de <xref:System.Web.Configuration.CustomErrorsSection.Mode%2A>eigenschap.</xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> Deze waarden definiëren of aangepaste fouten zijn ingeschakeld, uitgeschakeld of alleen op externe clients weergegeven."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> property.  \n  \n [!code-vb[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/visualbasic/t-system.web.configurati_54_1.vb)]\n [!code-cs[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/csharp/t-system.web.configurati_54_1.cs)]"
  syntax:
    content: public enum CustomErrorsMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.Off
  id: Off
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee schakelt u aangepaste fouten, zodat de standard-fouten worden weergegeven."
  syntax:
    content: Off
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.On
  id: On
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Aangepaste fouten inschakelen Als er geen <xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>is opgegeven, wordt standaard fouten worden uitgegeven.</xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>"
  syntax:
    content: On
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  id: RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee kunt aangepaste fouten op externe clients alleen. Aangepaste fouten worden alleen weergegeven op externe clients en ASP.NET-fouten worden weergegeven op de lokale host."
  syntax:
    content: RemoteOnly
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsMode.Off
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
- uid: System.Web.Configuration.CustomErrorsMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
- uid: System.Web.Configuration.CustomErrorsMode.On
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
