### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  id: PeerCustomResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  langs:
  - csharp
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  type: Class
  summary: "Bevat de specifieke instellingen voor een exemplaar van een aangepaste peer-omzetter-service."
  remarks: "Dit type definieert de basisinstellingen voor een aangepaste peer-omzettingsservice, inclusief het adres van het eindpunt van de peer die als host fungeert voor de service en een specifieke binding-instellingen. Deze instellingen zijn meestal verzorgd door naar de <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>eigenschap.</xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>"
  syntax:
    content: public class PeerCustomResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;> </xref> klasse."
  syntax:
    content: public PeerCustomResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  id: Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Opgehaald of ingesteld van het adres van het eindpunt van de peer-knooppunt die als host fungeert voor de aangepaste peer-omzetter-service."
  syntax:
    content: public System.ServiceModel.EndpointAddress Address { get; set; }
    return:
      type: System.ServiceModel.EndpointAddress
      description: "<xref:System.ServiceModel.EndpointAddress>dat het adres van het eindpunt van de peer-knooppunt met de omzettingsservice aangepaste peer bevat.</xref:System.ServiceModel.EndpointAddress>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  id: Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Opgehaald of ingesteld van de kanaalbinding gebruikt door de aangepaste peer-omzetter-service."
  remarks: "Dit bindingselement biedt de specificatie voor het bouwen van een kanaal-factory op de client en een kanaal-listener op de service. Dit kanaal-factory wordt gebruikt voor het produceren van kanalen voor de aangepaste peer-omzetter-service."
  syntax:
    content: public System.ServiceModel.Channels.Binding Binding { get; set; }
    return:
      type: System.ServiceModel.Channels.Binding
      description: "<xref:System.ServiceModel.Channels.Binding>dat bevat de binding-instellingen voor deze service.</xref:System.ServiceModel.Channels.Binding>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  id: IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Opgehaald of de <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>eigenschap is ingesteld.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  syntax:
    content: public bool IsBindingSpecified { get; }
    return:
      type: System.Boolean
      description: "True als de <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>eigenschap is ingesteld; false als dit niet.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  id: Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Opgehaald of ingesteld van het exemplaar van de aangepaste peer-omzetter voor deze service."
  syntax:
    content: public System.ServiceModel.PeerResolver Resolver { get; set; }
    return:
      type: System.ServiceModel.PeerResolver
      description: "<xref href=&quot;System.ServiceModel.PeerResolver&quot;></xref>het exemplaar dat wordt gebruikt door de service."
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
- uid: System.ServiceModel.PeerResolver
  parent: System.ServiceModel
  isExternal: false
  name: PeerResolver
  nameWithType: PeerResolver
  fullName: System.ServiceModel.PeerResolver
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
