### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UserMapPath
  id: UserMapPath
  children:
  - System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  - System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  - System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  - System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  - System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  - System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  - System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  - System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: UserMapPath
  nameWithType: UserMapPath
  fullName: System.Web.Configuration.UserMapPath
  type: Class
  summary: "Configuratie van virtuele bestandspaden wordt toegewezen aan de fysieke paden."
  syntax:
    content: 'public class UserMapPath : System.Web.Configuration.IConfigMapPath'
  inheritance:
  - System.Object
  implements:
  - System.Web.Configuration.IConfigMapPath
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  id: '#ctor(System.Configuration.ConfigurationFileMap)'
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: UserMapPath(ConfigurationFileMap)
  nameWithType: UserMapPath.UserMapPath(ConfigurationFileMap)
  fullName: System.Web.Configuration.UserMapPath.UserMapPath(ConfigurationFileMap)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.UserMapPath&quot;> </xref> klasse."
  syntax:
    content: public UserMapPath (System.Configuration.ConfigurationFileMap fileMap);
    parameters:
    - id: fileMap
      type: System.Configuration.ConfigurationFileMap
      description: "De bestandstoewijzing configuratie voor het configuratiebestand van de machine."
  overload: System.Web.Configuration.UserMapPath.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  id: GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetAppPathForPath(String,String)
  nameWithType: UserMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetAppPathForPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Retourneert de naam van de virtuele map die is gekoppeld aan een specifieke site."
  syntax:
    content: public string GetAppPathForPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    return:
      type: System.String
      description: "De <code> siteID </code> waarde moet uniek zijn. De <code> siteID </code> waarde wordt onderscheiden van sites met dezelfde naam hebben."
  overload: System.Web.Configuration.UserMapPath.GetAppPathForPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  id: GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: UserMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de standaardnaam van de site en de site-ID."
  syntax:
    content: public void GetDefaultSiteNameAndID (out string siteName, out string siteID);
    parameters:
    - id: siteName
      type: System.String
      description: "De naam van de standaard-site."
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
  overload: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  id: GetMachineConfigFilename
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetMachineConfigFilename()
  nameWithType: UserMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetMachineConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Retourneert de naam van de machine-configuratiebestand."
  syntax:
    content: public string GetMachineConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "De configuratie van de machine-bestandsnaam."
  overload: System.Web.Configuration.UserMapPath.GetMachineConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  id: GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: UserMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.UserMapPath.GetPathConfigFilename(String,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de directory en de naam van het configuratiebestand op basis van de site-ID en het sitepad."
  syntax:
    content: public void GetPathConfigFilename (string siteID, string path, out string directory, out string baseName);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    - id: directory
      type: System.String
      description: "Het fysieke pad van het configuratiebestand."
    - id: baseName
      type: System.String
      description: "De naam van het configuratiebestand."
  overload: System.Web.Configuration.UserMapPath.GetPathConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  id: GetRootWebConfigFilename
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: GetRootWebConfigFilename()
  nameWithType: UserMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Retourneert het fysieke pad van het configuratiebestand dat zich op de hoofdmap van de Web-toepassing."
  syntax:
    content: public string GetRootWebConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "Het fysieke pad van het bestand Web.config in de hoofdmap van de toepassing Web."
  overload: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  id: MapPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: MapPath(String,String)
  nameWithType: UserMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.MapPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Retourneert het fysieke pad op basis van de site-ID en de URL die is gekoppeld aan de site."
  syntax:
    content: public string MapPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
    - id: path
      type: System.String
      description: "De URL die is gekoppeld aan de site."
    return:
      type: System.String
      description: "Het fysieke pad van de site."
  overload: System.Web.Configuration.UserMapPath.MapPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  id: ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  langs:
  - csharp
  name: ResolveSiteArgument(String,String,String)
  nameWithType: UserMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.UserMapPath.ResolveSiteArgument(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Vult de sitenaam en site-ID op basis van de waarde van een site-argument."
  remarks: "Als `siteArgument` is `null`, of gelijk is aan de standaardnaam van de site, of gelijk zijn aan de site-id van het standaard de `siteName` en `siteID` waarden zijn gevuld met de standaardwaarden van de site."
  syntax:
    content: public void ResolveSiteArgument (string siteArgument, out string siteName, out string siteID);
    parameters:
    - id: siteArgument
      type: System.String
      description: "De sitenaam of de site-id."
    - id: siteName
      type: System.String
      description: "De naam van de standaard-site."
    - id: siteID
      type: System.String
      description: "Een unieke id voor de site."
  overload: System.Web.Configuration.UserMapPath.ResolveSiteArgument*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.UserMapPath.#ctor(System.Configuration.ConfigurationFileMap)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: UserMapPath(ConfigurationFileMap)
  nameWithType: UserMapPath.UserMapPath(ConfigurationFileMap)
  fullName: System.Web.Configuration.UserMapPath.UserMapPath(ConfigurationFileMap)
- uid: System.Configuration.ConfigurationFileMap
  parent: System.Configuration
  isExternal: false
  name: ConfigurationFileMap
  nameWithType: ConfigurationFileMap
  fullName: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetAppPathForPath(String,String)
  nameWithType: UserMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetAppPathForPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: UserMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID(String,String)
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetMachineConfigFilename()
  nameWithType: UserMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetMachineConfigFilename()
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: UserMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.UserMapPath.GetPathConfigFilename(String,String,String,String)
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetRootWebConfigFilename()
  nameWithType: UserMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename()
- uid: System.Web.Configuration.UserMapPath.MapPath(System.String,System.String)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: MapPath(String,String)
  nameWithType: UserMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.UserMapPath.MapPath(String,String)
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: ResolveSiteArgument(String,String,String)
  nameWithType: UserMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.UserMapPath.ResolveSiteArgument(String,String,String)
- uid: System.Web.Configuration.UserMapPath.#ctor*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: UserMapPath
  nameWithType: UserMapPath.UserMapPath
- uid: System.Web.Configuration.UserMapPath.GetAppPathForPath*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetAppPathForPath
  nameWithType: UserMapPath.GetAppPathForPath
- uid: System.Web.Configuration.UserMapPath.GetDefaultSiteNameAndID*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID
  nameWithType: UserMapPath.GetDefaultSiteNameAndID
- uid: System.Web.Configuration.UserMapPath.GetMachineConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetMachineConfigFilename
  nameWithType: UserMapPath.GetMachineConfigFilename
- uid: System.Web.Configuration.UserMapPath.GetPathConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetPathConfigFilename
  nameWithType: UserMapPath.GetPathConfigFilename
- uid: System.Web.Configuration.UserMapPath.GetRootWebConfigFilename*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: GetRootWebConfigFilename
  nameWithType: UserMapPath.GetRootWebConfigFilename
- uid: System.Web.Configuration.UserMapPath.MapPath*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: MapPath
  nameWithType: UserMapPath.MapPath
- uid: System.Web.Configuration.UserMapPath.ResolveSiteArgument*
  parent: System.Web.Configuration.UserMapPath
  isExternal: false
  name: ResolveSiteArgument
  nameWithType: UserMapPath.ResolveSiteArgument
