### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementElement
  id: ConnectionManagementElement
  children:
  - System.Net.Configuration.ConnectionManagementElement.#ctor
  - System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  - System.Net.Configuration.ConnectionManagementElement.Address
  - System.Net.Configuration.ConnectionManagementElement.MaxConnection
  - System.Net.Configuration.ConnectionManagementElement.Properties
  langs:
  - csharp
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement
  type: Class
  summary: "Hiermee geeft u het maximum aantal verbindingen met een externe computer. Deze klasse kan niet worden overgenomen."
  remarks: "This class corresponds to the [\\&lt;add\\&gt; Element for connectionManagement (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20connectionManagement%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the maximum number of simultaneous connections to a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> klasse."
  syntax:
    content: public ConnectionManagementElement ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> klasse met het opgegeven adres en de limiet van verbindingsgegevens."
  remarks: "Hiermee stelt u deze constructor de <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>eigenschap `address` en de <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>eigenschap `maxConnection`.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> </xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>"
  syntax:
    content: public ConnectionManagementElement (string address, int maxConnection);
    parameters:
    - id: address
      type: System.String
      description: "Een tekenreeks waarmee het adres van een externe computer."
    - id: maxConnection
      type: System.Int32
      description: "Een geheel getal dat het maximum aantal verbindingen toegestaan naar identificeert `address` vanaf de lokale computer."
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  id: Address
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Opgehaald of ingesteld van het adres voor de externe computers."
  remarks: "U kunt deze eigenschap instellen met een sterretje (*) om in te stellen van het aantal verbindingen voor onbekende computers.       Deze eigenschap geeft u een of meer externe computers en de <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>eigenschap geeft aan hoeveel gelijktijdige verbindingen tussen de lokale computer en de externe computers zijn toegestaan.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>"
  syntax:
    content: public string Address { get; set; }
    return:
      type: System.String
      description: "Een tekenreeks die een reguliere expressie met een beschrijving van een IP-adres of de DNS-naam bevat."
  overload: System.Net.Configuration.ConnectionManagementElement.Address*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  id: MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Opgehaald of ingesteld van het maximum aantal verbindingen dat kan worden uitgevoerd met een externe computer."
  remarks: "Deze eigenschap geeft aan hoeveel gelijktijdige verbindingen zijn toegestaan tussen de lokale computer en de externe computer. De externe computer is opgegeven met de <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>eigenschap.</xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>       De eigenschap MaxConnection is per <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> Als een toepassing worden niet gewijzigd <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>van de standaardwaarde, klikt u vervolgens de eigenschap MaxConnection geldt voor de volledige toepassingsdomein.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> Als er slechts een enkele toepassingsdomein in uw toepassing wordt uitgevoerd, is de instelling van de eigenschap MaxConnection gehele toepassing."
  syntax:
    content: public int MaxConnection { get; set; }
    return:
      type: System.Int32
      description: "Een geheel getal dat het maximum aantal verbindingen."
  overload: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Net.Configuration.ConnectionManagementElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement.ConnectionManagementElement
- uid: System.Net.Configuration.ConnectionManagementElement.Address*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
