### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  id: FederationConfigurationCreatedEventArgs
  children:
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  type: Class
  summary: "Biedt gegevens voor de <xref href=&quot;System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated&quot;> </xref> gebeurtenis."
  remarks: "De <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>gebeurtenis wordt geactiveerd wanneer de eerste HTTP-module in de webtoepassing verwijst naar de <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName>eigenschap.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> De eerste keer opent van deze eigenschap oorzaken een <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>object dat moet worden gemaakt en geïnitialiseerd van configuratie.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> De <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>gebeurtenis wordt vervolgens geactiveerd.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> U toegang hebt tot het gemaakte <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>object via de <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName>eigenschap in een gebeurtenis-handler om te bekijken of wijzigen.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: 'public class FederationConfigurationCreatedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  id: '#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)'
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs&quot;> </xref> klasse met de opgegeven federatiebewerkings configuration-object."
  remarks: "Initialiseert de <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>aan de federation-configuratieobject opgegeven door de eigenschap `config`.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>"
  syntax:
    content: public FederationConfigurationCreatedEventArgs (System.IdentityModel.Services.Configuration.FederationConfiguration config);
    parameters:
    - id: config
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Het configuratieobject federation. Een <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfiguration&quot;> </xref> object bevat de configureerbare eigenschappen voor de WS-Federation-Module voor verificatie (<xref href=&quot;System.IdentityModel.Services.WSFederationAuthenticationModule&quot;></xref>) en de sessie verificatiemodule (<xref href=&quot;System.IdentityModel.Services.SessionAuthenticationModule&quot;></xref>) in een webtoepassing."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  id: FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Opgehaald of ingesteld van de federation-configuratie-object dat is geïnitialiseerd uit het configuratiebestand."
  remarks: "De <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>object bevat de configureerbare eigenschappen voor de WS-Federation-Module voor verificatie (<xref:System.IdentityModel.Services.WSFederationAuthenticationModule>) en de sessie verificatiemodule (<xref:System.IdentityModel.Services.SessionAuthenticationModule>) in een webtoepassing.</xref:System.IdentityModel.Services.SessionAuthenticationModule> </xref:System.IdentityModel.Services.WSFederationAuthenticationModule> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>       Voor het wijzigen van de configuratie-instellingen, kunt u eigenschappen instellen op de <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>object waarnaar wordt verwezen door deze eigenschap, of als u krijgt u een nieuwe <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>object.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfiguration FederationConfiguration { get; set; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Het configuratieobject federation die van de configuratie is geïnitialiseerd."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
- uid: System.IdentityModel.Services.Configuration.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
