### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyWrongTypeException
  id: SettingsPropertyWrongTypeException
  children:
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException
  fullName: System.Configuration.SettingsPropertyWrongTypeException
  type: Class
  summary: "Een uitzondering die wordt gegenereerd wanneer een ongeldig type wordt gebruikt met een <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> object."
  syntax:
    content: 'public class SettingsPropertyWrongTypeException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> klasse."
  syntax:
    content: public SettingsPropertyWrongTypeException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> klasse op basis van de opgegeven parameter."
  syntax:
    content: public SettingsPropertyWrongTypeException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Een tekenreeks met een uitzonderingsbericht."
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: protected SettingsPropertyWrongTypeException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "De <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> waarin zich de geserialiseerd objectgegevens over de uitzondering."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "De <xref:System.Runtime.Serialization.StreamingContext>bevat contextuele informatie over de bron of bestemming van de geserialiseerde stroom.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> klasse op basis van de opgegeven parameters."
  syntax:
    content: public SettingsPropertyWrongTypeException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Een tekenreeks met een uitzonderingsbericht."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering."
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException
