### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization
  id: WebPartsPersonalizationAuthorization
  children:
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization
  type: Class
  summary: "Programmatische toegang biedt tot de <xref uid=&quot;langword_csharp_authorization&quot; name=&quot;authorization&quot; href=&quot;&quot;> </xref> sectie opgenomen in de <xref uid=&quot;langword_csharp_webParts&quot; name=&quot;webParts&quot; href=&quot;&quot;> </xref> sectie van de configuratie. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse WebPartsPersonalizationAuthorization biedt ondersteuning voor personalisatie autorisaties voor webonderdelen. Deze klasse kan worden gebruikt wilt toestaan of weigeren van toegang tot bronnen van de webonderdelen."
  example:
  - "The following configuration-file example shows how to declaratively specify values for properties of the WebPartsPersonalizationAuthorization class.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"*\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n  </webParts>  \n</system.web>  \n```"
  syntax:
    content: 'public sealed class WebPartsPersonalizationAuthorization : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.WebPartsPersonalizationAuthorization&quot;> </xref> klasse."
  remarks: "Deze constructor is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Een exemplaar van deze klasse is beschikbaar via de <xref:System.Web.Configuration.WebPartsPersonalizationAuthorization>eigenschap.</xref:System.Web.Configuration.WebPartsPersonalizationAuthorization>"
  syntax:
    content: public WebPartsPersonalizationAuthorization ();
    parameters: []
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  id: Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee wordt een verzameling regels gebruikt voor autorisatie van persoonlijke instellingen gerelateerd aan de webonderdelen."
  remarks: "De <xref:System.Web.Configuration.AuthorizationRuleCollection>bestaat uit <xref:System.Web.Configuration.AuthorizationRule>objecten.</xref:System.Web.Configuration.AuthorizationRule> </xref:System.Web.Configuration.AuthorizationRuleCollection> Een <xref:System.Web.Configuration.AuthorizationRule>object bevat een <xref:System.Web.Configuration.AuthorizationRule.Action%2A>-eigenschap een <xref:System.Web.Configuration.AuthorizationRule.Users%2A>-eigenschap en een <xref:System.Web.Configuration.AuthorizationRule.Verbs%2A>eigenschap.</xref:System.Web.Configuration.AuthorizationRule.Verbs%2A> </xref:System.Web.Configuration.AuthorizationRule.Users%2A> </xref:System.Web.Configuration.AuthorizationRule.Action%2A> </xref:System.Web.Configuration.AuthorizationRule> Deze eigenschappen kunnen toestaan of weigeren van toegang tot een bron voor webonderdelen worden ingesteld."
  syntax:
    content: public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: "Een <xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;> </xref> object."
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
