### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement
  id: IdentityModelCachesElement
  children:
  - System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  - System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  - System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  - System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement
  type: Class
  summary: "Hiermee geeft u een <xref uid=&quot;langword_csharp_&lt;caches&gt;&quot; name=&quot;&lt;caches&gt;&quot; href=&quot;&quot;> </xref> element in een configuratiebestand. Deze klasse kan niet worden overgenomen."
  remarks: "De `<caches>` element configureert u de cache-services voor WIF. Hiermee markeert u het type token sessiecache beveiliging en het type tokenreplay cache te gebruiken. Het kan worden opgegeven op het niveau van de service onder de `<identityConfiguration>` element of op een verzameling security token handler onder de `<securityTokenHandlerConfiguration>` element. De `Caches` eigenschap van de <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>klasse en van de <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>klasse is een exemplaar van IdentityModelCachesElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement> Nadat u het configuratiebestand is gelezen, worden de geconfigureerde caches vertegenwoordigd door de <xref:System.IdentityModel.Configuration.IdentityModelCaches>klasse.</xref:System.IdentityModel.Configuration.IdentityModelCaches>"
  syntax:
    content: 'public sealed class IdentityModelCachesElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCachesElement&quot;> </xref> klasse."
  syntax:
    content: public IdentityModelCachesElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  id: IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Haalt een waarde die aangeeft of dit element is geconfigureerd."
  syntax:
    content: public bool IsConfigured { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het element is geconfigureerd. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Opgehaald of ingesteld de <xref:System.Type>van de sessie tokencache.</xref:System.Type>"
  remarks: "Deze eigenschap is optioneel. Komt overeen met een `<sessionSecurityTokenCache>` element dat is opgegeven onder het `<caches>`. Dit geeft het type van de cache moet worden gebruikt voor het opslaan van beveiligingstokens van de sessie. Alle sessie token caches moeten zijn afgeleid van<xref:System.IdentityModel.Tokens.SessionSecurityTokenCache></xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "Het type van de sessiecache van de token. Het type moet zijn afgeleid van [System.IdentityModel.Tokens.SessionSecurityTokenCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Opgehaald of ingesteld de <xref:System.Type>replay-cache van het token.</xref:System.Type>"
  remarks: "Deze eigenschap is optioneel. Komt overeen met een `<tokenReplayCache>` element dat is opgegeven onder de `<caches>` element. Dit geeft het type van de cache moet worden gebruikt voor het detecteren van herhaald tokens. Alle replay-caches moeten zijn afgeleid van <xref:System.IdentityModel.Tokens.TokenReplayCache>replaydetectie is geactiveerd met de `<tokenReplayDetection>` element.</xref:System.IdentityModel.Tokens.TokenReplayCache> Dit element wordt vertegenwoordigd door de <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>klasse.</xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "Het type van de cache tokenreplay. Het type moet zijn afgeleid van [System.IdentityModel.Tokens.TokenReplayCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
