### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationIDAttribute
  id: ApplicationIDAttribute
  children:
  - System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  - System.EnterpriseServices.ApplicationIDAttribute.Value
  langs:
  - csharp
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute
  fullName: System.EnterpriseServices.ApplicationIDAttribute
  type: Class
  summary: "Hiermee geeft u de toepassings-ID (als een GUID) voor deze assembly. Deze klasse kan niet worden overgenomen."
  remarks: "ApplicationIDAttribute duurt een GUID in de constructor. Wanneer de registratie optreedt, zijn de onderdelen in de assembly geïnstalleerd in een toepassing met de opgegeven ID."
  example:
  - "The following code example demonstrates the use of the ApplicationIDAttribute type.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/t-system.enterpriseservi_14_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/t-system.enterpriseservi_14_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIDAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.EnterpriseServices.ApplicationIDAttribute&quot;> </xref> klasse geven de GUID die de toepassings-ID voor de COM +-toepassing."
  remarks: ''
  example:
  - "The following code example demonstrates how to create a new <xref:System.EnterpriseServices.ApplicationIDAttribute>.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/csharp/m-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/visualbasic/m-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public ApplicationIDAttribute (string guid);
    parameters:
    - id: guid
      type: System.String
      description: "De GUID die is gekoppeld aan de COM +-toepassing."
  overload: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Hiermee haalt u de GUID van de COM +-toepassing."
  remarks: "Waarde is ingesteld door de constructor met de GUID doorgegeven als parameter."
  example:
  - "The following code example demonstrates how to get the value of an `ApplicationID` attribute's Value property.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/p-system.enterpriseservi_3_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/p-system.enterpriseservi_3_1.vb)]"
  syntax:
    content: public Guid Value { get; }
    return:
      type: System.Guid
      description: "De GUID die de COM +-toepassing vertegenwoordigt."
  overload: System.EnterpriseServices.ApplicationIDAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
