### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageabilityAttribute
  id: SettingsManageabilityAttribute
  children:
  - System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  - System.Configuration.SettingsManageabilityAttribute.Manageability
  langs:
  - csharp
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute
  fullName: System.Configuration.SettingsManageabilityAttribute
  type: Class
  summary: "Hiermee geeft u een speciale instellingen toepassingseigenschappen-services. Deze klasse kan niet worden overgenomen."
  remarks: "De SettingsManageabilityAttribute geeft aan dat speciale, vooraf gedefinieerde services moeten worden opgegeven eigenschappen voor afzonderlijke toepassingen en eigenschappengroepen. De meeste van deze services worden geleverd door de Windows-besturingssysteem.       Zie voor meer informatie over de toepassingseigenschappen en hun gebruik [toepassing-instellingen voor Windows Forms](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsManageabilityAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  id: '#ctor(System.Configuration.SettingsManageability)'
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsManageabilityAttribute&quot;> </xref> klasse."
  remarks: "Meerdere services kunnen worden aangevraagd door een combinatie van waarden die zijn gedefinieerd door de <xref:System.Configuration.SettingsManageability>opsomming met de logische `OR` operator.</xref:System.Configuration.SettingsManageability>"
  syntax:
    content: public SettingsManageabilityAttribute (System.Configuration.SettingsManageability manageability);
    parameters:
    - id: manageability
      type: System.Configuration.SettingsManageability
      description: "Een <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> waarde waarmee de aangevraagde services worden opgesomd."
  overload: System.Configuration.SettingsManageabilityAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  id: Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de set met speciale services die zijn aangevraagd."
  remarks: "Deze eigenschap is ingesteld de <xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>constructor.</xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsManageability Manageability { get; }
    return:
      type: System.Configuration.SettingsManageability
      description: "Een waarde die het resultaat van het gebruik van de logische <xref uid=&quot;langword_csharp_OR&quot; name=&quot;OR&quot; href=&quot;&quot;> </xref> operator alle combineren de <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> opsommingswaarden die overeenkomt met de aangevraagde services."
  overload: System.Configuration.SettingsManageabilityAttribute.Manageability*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
