### YamlMime:ManagedReference
items:
- uid: System.Data.Services.IDataServiceConfiguration
  id: IDataServiceConfiguration
  children:
  - System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  - System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: IDataServiceConfiguration
  nameWithType: IDataServiceConfiguration
  fullName: System.Data.Services.IDataServiceConfiguration
  type: Interface
  summary: "De IDataServiceConfiguration wordt gebruikt door [!INCLUDE[ssAstoria](~/add/includes/ssastoria-md.md)] voor het instellen van het gedrag van de service, inclusief rechten heeft op entiteitsets en servicebewerkingen, beperkt u op de toegestane aanvragen, niet kunnen worden gedetecteerd standaard en het uitbreidingsniveau standaard op foutafhandeling typen registreren."
  remarks: "Dit type wordt gebruikt door <xref:System.Data.Services.DataService%601>klassen voor het configureren van de service door het implementeren van een statische methode met de naam InitializeService, void retourneren en één argument van het type IDataServiceConfiguration duurt.</xref:System.Data.Services.DataService%601> Het configuratieobject kan alleen worden gebruikt tijdens het aanroepen van de initialisatie van de service."
  syntax:
    content: public interface IDataServiceConfiguration
  implements: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Hiermee haalt het maximale aantal aanvragen dat kan worden verwerkt in een batch."
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: "Geheel getal dat het maximum aantal aanvragen dat kan worden verwerkt in een batch aangeeft."
  overload: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Hiermee haalt het maximum aantal wijzigingssets die kunnen worden verwerkt in een batch."
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: "Geheel getal dat het maximum aantal wijzigingssets die kunnen worden verwerkt in een batch aangeeft."
  overload: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Query-optie voor alle aanvragen voor de gegevensservice opgehaald of ingesteld dat het maximum aantal segmenten die kunnen worden uitgebreid door de $uitbreiden."
  remarks: "Als de limiet wordt overschreden, wordt een 400 Ongeldige aanvraag statuscode geretourneerd. De opgegeven waarde moet tussen 0 en `int.MaxValue`; anders wordt een `ArgumentOutOfRangeException` gegenereerd.       Het volgende voorbeeld van de query-tekenreeks heeft twee segmenten:"
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: "Het maximum aantal segmenten uit te breiden."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Opgehaald of ingesteld van een maximum aantal segmenten die worden ondersteund in een enkel `$expand` pad voor alle aanvragen voor de data-service."
  remarks: "Als de limiet wordt overschreden, wordt een 400 Ongeldige aanvraag statuscode geretourneerd. De opgegeven waarde moet tussen 0 en `int.MaxValue`; anders wordt een `ArgumentOutOfRangeException` gegenereerd.       Het volgende voorbeeld van de query-tekenreeks heeft twee segmenten in de eerste `$expand` pad en één in de tweede `$expand` pad:"
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: "Geheel getal dat het maximum aantal segmenten in ondersteund `$expand` pad."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Opgehaald of ingesteld van het maximum aantal objecten die kunnen worden ingevoegd in een afzonderlijke aanvraag."
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: "De waarde van het type geheel getal dat het maximum aantal objecten die kunnen worden ingevoegd in één aanvraag bevat."
  overload: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Hiermee haalt u het maximum aantal resultaten per verzameling."
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: "De integerwaarde die aangeeft van het maximum aantal resultaten per verzameling."
  overload: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Registreert een resourcetype voor gebruik door de data service."
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Het resourcetype te registreren."
  overload: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Stelt de toegangsregels voor de opgegeven entiteit ingesteld."
  remarks: "De standaardconfiguratie wordt voor het weigeren van toegang tot bronnen. Wanneer een service wordt geïnitialiseerd moeten de toegangsrechten worden ingeschakeld."
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: "De naam van de entiteit ingesteld voor de geconfigureerde toegang."
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: "Machtigingen verlenen voor de entiteit ingesteld."
  overload: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Hiermee stelt u de regels voor toegang voor de opgegeven service-bewerking."
  remarks: "De standaardconfiguratie wordt voor het weigeren van toegang tot bronnen. Wanneer een service wordt geïnitialiseerd, moeten de toegangsrechten worden ingeschakeld."
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: "De naam van de bewerking van de service waarop toegangsrechten instellen."
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: "De rechten toegestaan volgens <xref href=&quot;System.Data.Services.ServiceOperationRights&quot;> </xref> opsomming."
  overload: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Opgehaald of ingesteld of uitgebreide fouten standaard voor alle antwoorden van de data-service gebruikt worden."
  remarks: "Het antwoord van een opgegeven aanvraag kan worden genegeerd door de ontwikkelaar van de service gegevens overschrijft de `HandleException` methode. Uitgebreide fouten mag alleen worden ingeschakeld tijdens de ontwikkeling, niet in een productieomgeving, uit veiligheidsoverwegingen."
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: "Een Boolean die aangeeft of de uitgebreide fouten worden weergegeven."
  overload: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType
  nameWithType: IDataServiceConfiguration.RegisterKnownType
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
