### YamlMime:ManagedReference
items:
- uid: System.Configuration.ISettingsProviderService
  id: ISettingsProviderService
  children:
  - System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  langs:
  - csharp
  name: ISettingsProviderService
  nameWithType: ISettingsProviderService
  fullName: System.Configuration.ISettingsProviderService
  type: Interface
  summary: "Biedt een interface voor het definiëren van een andere toepassing instellingen provider."
  remarks: "De <xref:System.Configuration.IPersistComponentSettings>interface kunnen besturingselementen en onderdelen die worden gehost in een toepassing om vast te leggen van de toepassingsinstellingen op een manier die grotendeels transparant voor de toepassing.</xref:System.Configuration.IPersistComponentSettings> Echter, in sommige gevallen kan de toepassing of de omgeving moet mogelijk overschrijven de instellingen voor provider systeemeigen gebruikt door een component met een van de eigen kiezen. De interface ISettingsProviderService wordt het maken van een lichtgewicht service die dergelijke een alternatieve instellingen voor provider communiceert, die meestal worden aangeboden via de eigenaar van <xref:System.ComponentModel.Container>.</xref:System.ComponentModel.Container>       ISettingsProviderService wordt meestal gebruikt door het moment van ontwerp hulpprogramma&quot;s en foutopsporing die speciale ondersteuning voor toepassingsinstellingen bieden. Om te laten dergelijke een rangschikking naadloos werken, de <xref:System.Configuration.ApplicationSettingsBase>klasse bevat een constructors die een verwijzing naar het onderdeel dat.</xref:System.Configuration.ApplicationSettingsBase> Deze constructors vragen automatisch voor providers van compatibele instellingen."
  syntax:
    content: public interface ISettingsProviderService
  implements: []
  platform:
  - net462
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  id: GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  langs:
  - csharp
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Retourneert de provider van instellingen compatibel zijn met de eigenschap opgegeven instellingen."
  remarks: "De methode GetSettingsProvider kan een <xref:System.Configuration.ISettingsProviderService>te bieden de serialisatie-services voor elk onderdeel vestigingsplaats.</xref:System.Configuration.ISettingsProviderService> Deze methode bepaalt als de bijbehorende instellingen provider het eigenschapstype van de opgegeven toepassing-instellingen kunt behouden. Als dat mogelijk is, retourneert deze methode een verwijzing naar die instellingen provider; anders wordt `null`."
  syntax:
    content: public System.Configuration.SettingsProvider GetSettingsProvider (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "De <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> waarvoor serialisatie is vereist."
    return:
      type: System.Configuration.SettingsProvider
      description: "Als gevonden, de <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> die de eigenschap opgegeven instellingen kunt behouden; anders <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider
  nameWithType: ISettingsProviderService.GetSettingsProvider
