### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeEncodingConformance
  id: UnicodeEncodingConformance
  children:
  - System.Net.Configuration.UnicodeEncodingConformance.Auto
  - System.Net.Configuration.UnicodeEncodingConformance.Compat
  - System.Net.Configuration.UnicodeEncodingConformance.Strict
  langs:
  - csharp
  name: UnicodeEncodingConformance
  nameWithType: UnicodeEncodingConformance
  fullName: System.Net.Configuration.UnicodeEncodingConformance
  type: Enum
  summary: "Hiermee wordt bepaald hoe Unicode-tekens worden uitgevoerd door de <xref:System.Net.WebUtility.HtmlEncode*>methoden.</xref:System.Net.WebUtility.HtmlEncode*>"
  remarks: "Voor meer informatie over hoe Unicode-tekens zijn moeten worden gecodeerd in HTML-code, Zie [teken verlaat in markup- en CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeEncodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeEncodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeEncodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeEncodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik automatische gedrag. Het gedrag van Unicode-codering wordt bepaald door de huidige toepassing doel-Framework. Voor [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] en later, de Unicode-codering van gedrag strikte is."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeEncodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeEncodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeEncodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeEncodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gebruik compatibel gedrag. Hiermee wordt aangegeven dat afzonderlijke vervangende UTF-16-codepunten uitvoer als-is wanneer een van de <> </> *> methoden wordt aangeroepen. Bijvoorbeeld, krijgt een tekenreeks &quot;\\uD84C\\uDFB4&quot; (of &quot;\\U000233B4&quot;), de uitvoer van <> </> *> is &quot;\\uD84C\\uDFB4&quot; (de invoer is niet gecodeerd)."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeEncodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeEncodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeEncodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeEncodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Use strict behavior. Specifies that individual UTF-16 surrogate code points are combined into a single code point when one of the <xref:System.Net.WebUtility.HtmlEncode*> methods is called. For example, given the input string \"\\uD84C\\uDFB4\" (or \"\\U000233B4\"), the output of the <xref:System.Net.WebUtility.HtmlEncode*> methods is \"&amp;#144308;\".  \n  \n If the input is a malformed UTF-16 string (it contains unpaired surrogates, for example), the bad code points will be replaced with U+FFFD (Unicode replacement char) before being HTML-encoded."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeEncodingConformance
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeEncodingConformance.Auto
  parent: System.Net.Configuration.UnicodeEncodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeEncodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Auto
- uid: System.Net.Configuration.UnicodeEncodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: UnicodeEncodingConformance
  fullName: System.Net.Configuration.UnicodeEncodingConformance
- uid: System.Net.Configuration.UnicodeEncodingConformance.Compat
  parent: System.Net.Configuration.UnicodeEncodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeEncodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Compat
- uid: System.Net.Configuration.UnicodeEncodingConformance.Strict
  parent: System.Net.Configuration.UnicodeEncodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeEncodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeEncodingConformance.Strict
