### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement
  id: IssuerNameRegistryElement
  children:
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  langs:
  - csharp
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement
  type: Class
  summary: "Hiermee geeft u een <xref uid=&quot;langword_csharp_&lt;issuerNameRegistry&gt;&quot; name=&quot;&lt;issuerNameRegistry&gt;&quot; href=&quot;&quot;> </xref> element in een configuratiebestand. Deze klasse kan niet worden overgenomen."
  remarks: "De `<issuerNameRegistry>` element configureert u het register van de naam van verlener. Het register van de naam van verlener maps verlener tokens op de tekenreeksnaam van een. De <xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A>eigenschap (waarop de `type` kenmerk van het element) kan worden ingesteld op het registreren van een aangepast type.</xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A> Standaard wordt een type <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>wordt verondersteld.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>       De `<issuerNameRegistry>` element kan worden opgegeven op het niveau van de service onder de `<identityConfiguration>` element of op een verzameling security token handler onder de `<securityTokenHandlerConfiguration>` element. De `IssuerNameRegistry` eigenschap van de <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>klasse en van de <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>klasse is een exemplaar van IssuerNameRegistryElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement>"
  syntax:
    content: 'public sealed class IssuerNameRegistryElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Configuration.IssuerNameRegistryElement&quot;> </xref> klasse."
  syntax:
    content: public IssuerNameRegistryElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Opgehaald of ingesteld van een tekenreeksrepresentatie van de <xref:System.Type>van het register van de naam van verlener.</xref:System.Type>"
  remarks: "Deze eigenschap is optioneel. Komt overeen met de `type` kenmerk van de `<issuerNameRegistry>` element. Als deze niet is opgegeven, is de eigenschap `null`, een type <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>wordt verondersteld.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "De tekenreeksrepresentatie van de <xref:System.Type>van het register van de naam van verlener.</xref:System.Type> Het type moet zijn afgeleid van de <xref href=&quot;System.IdentityModel.Tokens.IssuerNameRegistry&quot;> </xref> klasse."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
