### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: "Hiermee geeft u een naam voor de eigenschap van de toepassingsgroep-instellingen. Deze klasse kan niet worden overgenomen."
  remarks: "Een klasse-instellingen van toepassing is afgeleid van <xref:System.Configuration.ApplicationSettingsBase>, een of meer eigenschappen die deel uitmaken van dezelfde toepassing instellingen eigenschappengroep definieert.</xref:System.Configuration.ApplicationSettingsBase> Standaard is de groep de naam van de klasse instellingen toegewezen. SettingsGroupNameAttribute kan echter expliciet opgeven van een naam voor de eigenschappengroep worden gebruikt. Deze naam kan nuttig zijn bij het organiseren van grote sets van eigenschappen voor hulp bij het moment van ontwerp programming hulpprogramma&quot;s en runtime-beheerprogramma&quot;s, enzovoort. De gekoppelde instellingen provider kan zelfs gebruikt deze naam te organiseren instellingen in het gegevensarchief.       De SettingsGroupNameAttribute kan alleen worden toegepast op het klasseniveau van de."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsGroupNameAttribute&quot;> </xref> klasse."
  remarks: "Hoewel de theoretische maximale lengte van de `groupName` parameter wordt begrensd door de bovengrens van een <xref:System.Int32>, praktische grenzen, bepaald door de gebruiksvriendelijkheid en quotumbeperkingen die zijn opgelegd door de provider van instellingen, worden veel kleiner.</xref:System.Int32>      > [!NOTE] > De naam van instellingengroep hoeft niet uniek te zijn."
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: "Een <xref:System.String>met de naam van de groep van toepassingen instellingen eigenschap.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de naam van de groep van toepassingen instellingen eigenschap."
  remarks: "De waarde van de eigenschap GroupName is ingesteld door de <xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>constructor.</xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>"
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>met de naam van de groep van toepassingen instellingen eigenschap.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
