### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.OutputCacheSettingsSection
  id: OutputCacheSettingsSection
  children:
  - System.Web.Configuration.OutputCacheSettingsSection.#ctor
  - System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  - System.Web.Configuration.OutputCacheSettingsSection.Properties
  langs:
  - csharp
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
  type: Class
  summary: "Hiermee configureert u de instellingen voor uitvoercache voor pagina&quot;s van toepassing. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse OutputCacheSettingsSection kunt u programmatisch openen en te wijzigen de `outputCacheSettings` element van de `caching` sectie in een configuratiebestand. De instellingen voor de uitvoercache de afhankelijkheden definiëren (de relaties tussen items die zijn opgeslagen in de cache en bestanden, cache-sleutels, of <xref:System.Web.Caching.CacheDependency>objecten) die worden gebruikt in de uitvoercache, bijvoorbeeld door de [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) richtlijn of door de <xref:System.Web.Configuration.OutputCacheProfile>.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Caching.CacheDependency>      > [!NOTE] > De OutputCacheSettingsSection kunt schrijven van gegevens naar de bijbehorende sectie van het configuratiebestand op basis van de beperkingen die zijn gedefinieerd door de sectie eigenschap <xref:System.Configuration.SectionInformation.AllowDefinition%2A>waarvan de waarde is <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> Elke poging om te schrijven in een configuratiebestand op een niveau niet toegestaan in de hiërarchie resulteert in een foutbericht dat wordt gegenereerd door de parser. U kunt deze klasse echter gebruiken om configuratie-informatie op elk niveau in de hiërarchie te lezen."
  example:
  - "The following code example shows how to obtain the OutputCacheSettingsSection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_9_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_9_1.vb)]"
  syntax:
    content: 'public sealed class OutputCacheSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> klasse."
  remarks: "De constructor OutputCacheSettingsSection is niet bedoeld voor rechtstreeks gebruik vanuit uw code. Deze wordt aangeroepen door de ASP.NET-configuratiesysteem. Verkrijgen van een exemplaar van de <xref:System.Web.Configuration.OutputCacheSettingsSection>klasse met behulp van de <xref:System.Configuration.Configuration.GetSection%2A>methode.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  syntax:
    content: public OutputCacheSettingsSection ();
    parameters: []
  overload: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  id: OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref>."
  remarks: "De eigenschap OutputCacheProfiles kunt u programmatisch toegang tot de `outputCacheProfiles` element in een configuratiebestand. U kunt de eigenschap OutputCacheProfiles wijzigen de `outputCacheProfiles` element programmatisch.       De `outputCacheProfiles` sectie bevat <xref:System.Web.Configuration.OutputCacheProfile>objecten die uitvoer vertegenwoordigen cache-instellingen die kunnen worden gebruikt door pagina&quot;s in de toepassing.</xref:System.Web.Configuration.OutputCacheProfile>  Deze instellingen kunnen worden toegepast op een pagina door in te stellen de `CacheProfile` kenmerk van de [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) richtlijn. Het profiel van toepassing op kenmerken, zoals afhankelijkheden, cachelocatie en verlooptijd van de cache opslaan in cache besturingselement.       De [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) richtlijn kunt overschrijven de instellingen die zijn opgenomen in een <xref:System.Web.Configuration.OutputCacheProfile>, behalve de <xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A>eigenschap.</xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A> </xref:System.Web.Configuration.OutputCacheProfile> Dit is om te controleren of u kunt inschakelen of uitschakelen de <xref:System.Web.Configuration.OutputCacheProfile>zonder te wijzigen van de richtlijnen in alle pagina&quot;s die hebben deze genegeerd</xref:System.Web.Configuration.OutputCacheProfile>"
  example:
  - "The following code example shows how to use the OutputCacheProfiles property.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_105_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_105_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheProfileCollection OutputCacheProfiles { get; }
    return:
      type: System.Web.Configuration.OutputCacheProfileCollection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.OutputCacheProfile&quot;></xref> objects"
  overload: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheProfileCollection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheProfileCollection
  nameWithType: OutputCacheProfileCollection
  fullName: System.Web.Configuration.OutputCacheProfileCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
