### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidator
  id: CallbackValidator
  children:
  - System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  - System.Configuration.CallbackValidator.CanValidate(System.Type)
  - System.Configuration.CallbackValidator.Validate(System.Object)
  langs:
  - csharp
  name: CallbackValidator
  nameWithType: CallbackValidator
  fullName: System.Configuration.CallbackValidator
  type: Class
  summary: "Biedt dynamische validatie van een object."
  remarks: "Deze klasse, hebt u nodig voor het implementeren van een <xref:System.Configuration.ValidatorCallback>delegeren voor het type object die u wilt valideren.</xref:System.Configuration.ValidatorCallback> Als u deze klasse instantiëren, geeft u in het objecttype en een verwijzing naar de gemachtigde. Vervolgens kunt u aanroepen <xref:System.Configuration.CallbackValidator.CanValidate%2A>om te bepalen of een object het juiste type is of <xref:System.Configuration.CallbackValidator.Validate%2A>voor het uitvoeren van de gemachtigde op het object.</xref:System.Configuration.CallbackValidator.Validate%2A> </xref:System.Configuration.CallbackValidator.CanValidate%2A>"
  syntax:
    content: 'public sealed class CallbackValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  id: '#ctor(System.Type,System.Configuration.ValidatorCallback)'
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref> klasse."
  syntax:
    content: public CallbackValidator (Type type, System.Configuration.ValidatorCallback callback);
    parameters:
    - id: type
      type: System.Type
      description: "Het type object dat wordt gevalideerd."
    - id: callback
      type: System.Configuration.ValidatorCallback
      description: "De <xref href=&quot;System.Configuration.ValidatorCallback&quot;> </xref> gebruikt als de gemachtigde."
  overload: System.Configuration.CallbackValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>type </code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of het type van het object kan worden gevalideerd."
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Het type object."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref> parameter komt overeen met het type als de eerste parameter wordt gebruikt bij het maken van een exemplaar van <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref>; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.CallbackValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of de waarde van een object geldig is."
  remarks: "De <xref:System.Configuration.CallbackValidator>klasse bevat het type en de gemachtigde die nodig zijn voor het valideren van een object.</xref:System.Configuration.CallbackValidator> Het type en de gemachtigde worden tot stand gebracht wanneer een exemplaar van de <xref:System.Configuration.CallbackValidator>klasse wordt gemaakt.</xref:System.Configuration.CallbackValidator> Het object te valideren wordt als een parameter van de methode Validate doorgegeven."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "De waarde van een object."
  overload: System.Configuration.CallbackValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ValidatorCallback
  parent: System.Configuration
  isExternal: false
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.CallbackValidator.#ctor*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator
  nameWithType: CallbackValidator.CallbackValidator
- uid: System.Configuration.CallbackValidator.CanValidate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate
  nameWithType: CallbackValidator.CanValidate
- uid: System.Configuration.CallbackValidator.Validate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate
  nameWithType: CallbackValidator.Validate
