### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  id: PeerApplicationLaunchInfo
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  langs:
  - csharp
  name: PeerApplicationLaunchInfo
  nameWithType: PeerApplicationLaunchInfo
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  type: Class
  summary: "Hiermee geeft u de start-informatie die vereist zijn voor een <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> die is gestart als reactie op een uitnodiging voor een peer-samenwerking."
  remarks: "Een toepassing kunt inspecteren de <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>en <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A>Eigenschappen van deze klasse voor het ophalen van de informatie die specifiek zijn voor de uitnodiging die het opstarten van de App wordt gestart.</xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A> </xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>       Toegang tot deze klasse moet een <xref:System.Security.Permissions.PermissionState>van de <xref:System.Security.Permissions.PermissionState>.</xref:System.Security.Permissions.PermissionState> </xref:System.Security.Permissions.PermissionState> Deze status wordt gemaakt wanneer de <xref:System.Net.PeerToPeer.Collaboration.Peer>samenwerkingssessie begint.</xref:System.Net.PeerToPeer.Collaboration.Peer>"
  syntax:
    content: public class PeerApplicationLaunchInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  id: Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Opgehaald of ingesteld van toepassingsspecifieke binaire gegevens die zijn gekoppeld aan de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> uitnodiging."
  remarks: "Deze gegevens blob vrije vorm en wordt aangeboden door de aanroeper.  De maximale hoeveelheid gegevens die kunnen worden verstrekt is 4096 bytes.       De gegevens kan niet worden `null`."
  syntax:
    content: public byte[] Data { get; }
    return:
      type: System.Byte[]
      description: "Een matrix met bytes dat met de gegevens die zijn gekoppeld aan de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> uitnodiging."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  id: Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Ophalen of instellen van een bericht dat is gekoppeld aan het antwoord op de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> uitnodiging."
  remarks: "De maximale lengte voor het bericht is 255 Unicode-tekens. Tenzij expliciet wordt vermeld, de standaardwaarde voor alle eigenschappen is `null` voor verwijzingstypen."
  syntax:
    content: public string Message { get; }
    return:
      type: System.String
      description: "Een SMS-bericht die zijn gekoppeld aan de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerInvitationResponse&quot;> </xref> naar de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> uitnodiging."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> voor de uitnodiging is verzonden."
  remarks: "Tenzij expliciet wordt vermeld, de standaardwaarde voor alle eigenschappen is `null` voor verwijzingstypen."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "De <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> waarvoor de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> uitnodiging is verzonden."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> die de uitnodiging verzonden."
  remarks: "Tenzij expliciet wordt vermeld, de standaardwaarde voor alle eigenschappen is `null` voor verwijzingstypen."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "De <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> die de uitnodiging verzonden."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Opgehaald of ingesteld de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> van waaruit de <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> uitnodiging is verzonden."
  remarks: "Tenzij expliciet wordt vermeld, de standaardwaarde voor alle eigenschappen is `null` voor verwijzingstypen."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "De <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> waaruit de uitnodiging is verzonden."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
