### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationVersionMatch
  id: ApplicationVersionMatch
  children:
  - System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  - System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  langs:
  - csharp
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
  type: Enum
  summary: "Geeft aan hoe versies komt overeen wanneer toepassing zoeken vertrouwensrelaties in een verzameling."
  remarks: "De <xref:System.Security.Policy.ApplicationTrustCollection.Remove%2A>en <xref:System.Security.Policy.ApplicationTrustCollection.Find%2A>methoden van een <xref:System.Security.Policy.ApplicationTrustCollection>kunnen reageren op alle versies van een toepassing of op de exacte versie.</xref:System.Security.Policy.ApplicationTrustCollection> </xref:System.Security.Policy.ApplicationTrustCollection.Find%2A> </xref:System.Security.Policy.ApplicationTrustCollection.Remove%2A> De opsomming ApplicationVersionMatch kan de aanroeper het gewenste gedrag opgeven."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum ApplicationVersionMatch
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  id: MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Overeenkomen met alle versies."
  syntax:
    content: MatchAllVersions
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  id: MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Overeenkomen met de exacte versie."
  syntax:
    content: MatchExactVersion
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
- uid: System.Security.Policy.ApplicationVersionMatch
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
