### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidator
  id: LongValidator
  children:
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  - System.Configuration.LongValidator.CanValidate(System.Type)
  - System.Configuration.LongValidator.Validate(System.Object)
  langs:
  - csharp
  name: LongValidator
  nameWithType: LongValidator
  fullName: System.Configuration.LongValidator
  type: Class
  summary: "Validatie van biedt een <xref:System.Int64>waarde.</xref:System.Int64>"
  remarks: "De LongValidator wordt gebruikt om te controleren of een `long` (een 64-bits geheel getal met teken) aan bepaalde criteria voldoet. De criteria voor validatie wordt ingesteld wanneer een exemplaar van de klasse LongValidator is gemaakt. De <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%29>constructor zorgt ervoor dat de `long` waarde die wordt gevalideerd overeenstemming is met zowel een minimum- en een maximale lengte.</xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%29> De <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%29>constructor controleert de minimum- en de maximum <xref:System.Int64>waarden, evenals of het bereik van de validatie exclusieve is.</xref:System.Int64> </xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%29> De <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%2CSystem.Int64%29>constructor controleert u de vorige drie parameters en ook controleert of de <xref:System.Int64>waarde gelijk is aan de waarde van een specifieke oplossingsstatus.</xref:System.Int64> </xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%2CSystem.Int64%29>       De <xref:System.Configuration.LongValidator.CanValidate%2A>methode bepaalt of het objecttype wordt gevalideerd overeenkomt met het verwachte type.</xref:System.Configuration.LongValidator.CanValidate%2A> Het object dat wordt gevalideerd wordt doorgegeven als een parameter van de <xref:System.Configuration.LongValidator.Validate%2A>methode.</xref:System.Configuration.LongValidator.Validate%2A>"
  example:
  - "The following code example demonstrates how to use the LongValidator type.  \n  \n [!code-vb[System.Configuration.LongValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.LongValidator#1](~/add/codesnippet/csharp/t-system.configuration.l_1_1.cs)]"
  syntax:
    content: 'public class LongValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  id: '#ctor(System.Int64,System.Int64)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> klasse."
  remarks: "De constructor LongValidator zorgt ervoor dat de lange waarde wordt geverifieerd in overeenstemming is met zowel een minimum- en een maximale lengte."
  syntax:
    content: public LongValidator (long minValue, long maxValue);
    parameters:
    - id: minValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de minimale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de maximale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  id: '#ctor(System.Int64,System.Int64,System.Boolean)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64,Boolean)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> klasse."
  remarks: "Als de constructor LongValidator wordt gebruikt, controleert deze de minimum- en de maximum <xref:System.Int64>waarden, evenals of het bereik van de validatie exclusieve is.</xref:System.Int64> Wanneer de `rangeIsExclusive` parameter is ingesteld op `true`, wordt de <xref:System.Int64>moet een waarde tussen `minValue` en `maxValue`.</xref:System.Int64>"
  example:
  - "The following code example demonstrates how to use the LongValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#2](~/add/codesnippet/visualbasic/2847484f-ec91-486e-9c9a-_1.vb)]\n [!code-cs[System.Configuration.LongValidator#2](~/add/codesnippet/csharp/2847484f-ec91-486e-9c9a-_1.cs)]"
  syntax:
    content: public LongValidator (long minValue, long maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de minimale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de maximale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "Een <xref:System.Boolean>waarde die aangeeft of het bereik van de validatie van exclusieve.</xref:System.Boolean>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  id: '#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64,Boolean,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> klasse."
  remarks: "Wanneer u opgeeft de `resolution`, wordt de <xref:System.Int64>waarde wordt gevalideerd moet gelijk zijn aan die waarde om te worden gevalideerd.</xref:System.Int64>"
  syntax:
    content: public LongValidator (long minValue, long maxValue, bool rangeIsExclusive, long resolution);
    parameters:
    - id: minValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de minimale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee de maximale lengte van de <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> waarde.</xref:System.Int64>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "Een <xref:System.Boolean>waarde die aangeeft of het bereik van de validatie van exclusieve.</xref:System.Boolean>"
    - id: resolution
      type: System.Int64
      description: "Een <xref:System.Int64>waarde waarmee een specifieke waarde die moet overeenkomen.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code>resolution</code> is equal to or less than <xref uid=\"langword_csharp_0\" name=\"0\" href=\"\"></xref>.  \n  \n \\- or -  \n  \n <code>maxValue</code> is less than <code>minValue</code>."
  platform:
  - net462
- uid: System.Configuration.LongValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: LongValidator.CanValidate(Type)
  fullName: System.Configuration.LongValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of het type van het object kan worden gevalideerd."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.LongValidator#3](~/add/codesnippet/csharp/m-system.configuration.l_0_1.cs)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Het type object."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de <code> type </code> parameter overeenkomt met een <xref:System.Int64>waarde; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: LongValidator.Validate(Object)
  fullName: System.Configuration.LongValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hiermee wordt bepaald of de waarde van een object geldig is."
  remarks: "De <xref:System.Configuration.LongValidator>klasse bevat de regels die moet worden gevalideerd een <xref:System.Int64>object.</xref:System.Int64> </xref:System.Configuration.LongValidator> De regels worden tot stand gebracht wanneer een exemplaar van de <xref:System.Configuration.LongValidator>klasse wordt gemaakt.</xref:System.Configuration.LongValidator> Het object te valideren wordt als een parameter van de methode Validate doorgegeven."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.LongValidator#4](~/add/codesnippet/csharp/m-system.configuration.l_1_1.cs)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "De waarde van een object."
  overload: System.Configuration.LongValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64,Boolean)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64,Boolean,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
- uid: System.Configuration.LongValidator.CanValidate(System.Type)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: LongValidator.CanValidate(Type)
  fullName: System.Configuration.LongValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.LongValidator.Validate(System.Object)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: LongValidator.Validate(Object)
  fullName: System.Configuration.LongValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.LongValidator.#ctor*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator
  nameWithType: LongValidator.LongValidator
- uid: System.Configuration.LongValidator.CanValidate*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: CanValidate
  nameWithType: LongValidator.CanValidate
- uid: System.Configuration.LongValidator.Validate*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: Validate
  nameWithType: LongValidator.Validate
