### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "Hiermee geeft u op welke versleutelingsmethoden kunnen worden gebruikt."
  remarks: "U de waarden MachineKeyCompatibilityMode gebruiken bij het instellen van de <xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>eigenschap.</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "De methoden voor versleuteling gebruikt die zijn geïmplementeerd in versies van .NET Framework versie 2.0 Service Pack 2. Initialisatie van vectoren (IV&quot;s) worden gebruikt voor alle versleutelingsbewerkingen, met uitzondering van gecodeerde wachtwoorden opslaan in de ASP.NET-lidmaatschapsdatabase."
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gebruik de sterkere versleutelingsmethoden die beschikbaar in .NET Framework versie 2.0 SP2 en latere versies zijn. Initialisatie van vectoren (IV&quot;s) worden gebruikt voor alle versleutelingsbewerkingen van."
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gebruik versleutelingsmethoden die beschikbaar in .NET Framework versie 4.5 en latere versies zijn. Vergeleken met de coderingsmethoden die worden gebruikt voor Framework20SP1 en Framework20SP2, de gecodeerde tekst die wordt gegenereerd door de standaard cryptografische routines is iets kleiner en is toleranter op basis van bepaalde klassen van theoretische aanvallen. Ze ook worden geïntegreerd met [!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)] Directorybeheer om vereiste cryptografische sleutels. Met deze optie kunt u aangepaste cryptografische routines opgeven door het schrijven van een klasse die is afgeleid van <xref href=&quot;System.Security.Cryptography.DataProtector&quot;> </xref> en geven de naam van de klasse in de &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; eigenschap.       De volgende configuratievereisten van toepassing op deze optie: 1. Als de &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; eigenschap een waarde heeft het &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt; eigenschap moet ook een waarde hebben.       2. De &lt;xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt; kenmerk moet een door het systeem gedefinieerde validatiealgoritme (zoals MD5, SHA1, HMACSHA256, HMACSHA384 of HMACSHA512) of een aangepaste validatiealgoritme opgeven in een klasse die is afgeleid van de <xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;> </xref> klasse. De waarden AES en 3DES zijn geen validatie-algoritmen.       Wanneer u deze optie opgeeft, formulierverificatietickets zijn altijd zowel versleuteld en ondertekend, ongeacht de opgegeven waarde voor de &lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt; eigenschap. De weergave status wordt ook zowel versleuteld en ondertekend als een pagina <> </> *> eigenschap is <code> true </code> of de <> </> *> eigenschap <xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always> is"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
