### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata
  id: ProfilePropertyMetadata
  children:
  - System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  - System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  - System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  - System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  - System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  - System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  - System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  - System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  langs:
  - csharp
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata
  type: Class
  summary: "Biedt een verzameling waarden die een profieleigenschap beschrijven."
  remarks: "Gebruik van de klasse ProfilePropertyMetadata informatie ophalen over een profieleigenschap wanneer u profielen voor toegang tot en met de <xref:System.Web.ApplicationServices.ProfileService>klasse.</xref:System.Web.ApplicationServices.ProfileService> U kunt de naam en type van de eigenschap ophalen of het is alleen-lezen, of deze toegankelijk is voor gebruikers die niet is geverifieerd en de standaardwaarde. Een toepassing kan duren voordat de nodige acties op basis van deze waarden, zoals het niet probeert in te stellen van een alleen-lezen eigenschap.       Voor toegang tot het object ProfilePropertyMetadata uit een toepassing die compatibel is met het Framework WCF (Windows Communication), gebruikt u de <xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A>methode van de <xref:System.Web.ApplicationServices.ProfileService>klasse.</xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A> De gebruiker hoeft niet te worden aangemeld bij het ophalen van het object ProfilePropertyMetadata omdat de metagegevens voor profieleigenschappen niet specifiek voor de waarden voor profieleigenschappen van een gebruiker is.       De waarden in de klasse ProfilePropertyMetadata worden ingesteld in het bestand Web.config in het element van de sectie als de eigenschap is gedefinieerd."
  syntax:
    content: >-
      [System.Runtime.Serialization.DataContract]

      public class ProfilePropertyMetadata : System.Runtime.Serialization.IExtensibleDataObject
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.IExtensibleDataObject
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.ApplicationServices.ProfilePropertyMetadata&quot;> </xref> klasse."
  syntax:
    content: public ProfilePropertyMetadata ();
    parameters: []
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  id: AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de eigenschap beschikbaar voor niet-geverifieerde gebruikers is."
  remarks: "Wanneer u anonieme identificatie met instellingen in het element inschakelt, kunt u instellen welke profieleigenschappen zijn beschikbaar voor anonieme gebruikers. U kunt de eigenschap AllowAnonymousAccess in het element van het gedeelte van het bestand Web.config instellen als de eigenschap is gedefinieerd. Gebruik de eigenschap AllowAnonymousAccess om te bepalen of een profieleigenschap kan worden ingesteld voor een anonieme gebruiker van de clienttoepassing."
  syntax:
    content: public bool AllowAnonymousAccess { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de eigenschap beschikbaar voor de niet-geverifieerde gebruikers is. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  id: DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van de standaardwaarde van de eigenschap."
  remarks: "De serialisatie-indeling van de eigenschap DefaultValue wordt bepaald door de <xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>eigenschap van de <xref:System.Web.ApplicationServices.ProfilePropertyMetadata>klasse.</xref:System.Web.ApplicationServices.ProfilePropertyMetadata> </xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>"
  syntax:
    content: public string DefaultValue { get; set; }
    return:
      type: System.String
      description: "Een geserialiseerde weergave van de standaardwaarde voor de eigenschap als een standaardwaarde is gedefinieerd in het bestand Web.config. anders is de tekenreeks &quot;(null)&quot;."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  id: ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van een verwijzing naar een <xref href=&quot;System.Runtime.Serialization.ExtensionDataObject&quot;> </xref> exemplaar."
  syntax:
    content: public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
    return:
      type: System.Runtime.Serialization.ExtensionDataObject
      description: "Een verwijzing naar een object dat uitgebreide gegevens tijdens de deserialisatie-bewerkingen worden opgeslagen."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  id: IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of een profieleigenschap alleen-lezen is."
  remarks: "U kunt de eigenschap IsReadOnly in het element van het gedeelte van het bestand Web.config instellen als de eigenschap is gedefinieerd."
  syntax:
    content: public bool IsReadOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de profieleigenschap alleen-lezen is. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  id: PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van de naam van de profieleigenschap."
  remarks: "U kunt de eigenschap PropertyName in het element van het gedeelte van het bestand Web.config instellen als de eigenschap is gedefinieerd."
  syntax:
    content: public string PropertyName { get; set; }
    return:
      type: System.String
      description: "De naam van de profieleigenschap zoals gedefinieerd in het bestand Web.config."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  id: SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van een waarde die hoe aangeeft voor het serialiseren van de waarde van eigenschap."
  remarks: "U kunt de eigenschap SerializeAs in het element van het gedeelte van het bestand Web.config instellen als de eigenschap is gedefinieerd."
  syntax:
    content: public int SerializeAs { get; set; }
    return:
      type: System.Int32
      description: "De opsommingswaarde."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  id: TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Opgehaald of ingesteld van de assembly gekwalificeerde naam van het type van de eigenschap profiel."
  remarks: "U kunt de eigenschap TypeName in het element van het gedeelte van het bestand Web.config instellen als de eigenschap is gedefinieerd."
  syntax:
    content: public string TypeName { get; set; }
    return:
      type: System.String
      description: "De assembly gekwalificeerde naam van het type van de eigenschap profiel."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
- uid: System.Runtime.Serialization.ExtensionDataObject
  parent: System.Runtime.Serialization
  isExternal: false
  name: ExtensionDataObject
  nameWithType: ExtensionDataObject
  fullName: System.Runtime.Serialization.ExtensionDataObject
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
