### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Helpt bij het lezen in de <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> gedeelte van een configuratiebestand en het maken van een exemplaar van de <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klasse met de informatie over de mogelijkheden voor de clientbrowser."
  remarks: "De klasse HttpCapabilitiesSectionHandler en de bijbehorende `<browserCaps>` configuratiesectie zijn afgeschaft in versie 2.0 van .NET Framework. De voorkeursmethode voor het beheren van browsermogelijkheden is via de browser definitiebestanden die worden gecompileerd voor gebruik door de <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klasse.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Het doel van beide methoden configuratie is voor het genereren van een exemplaar van de <xref:System.Web.HttpBrowserCapabilities>klasse die toegankelijk is vanaf de <xref:System.Web.HttpRequest.Browser%2A>eigenschap van de <xref:System.Web.HttpRequest>klasse.</xref:System.Web.HttpRequest> </xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities>       De browser definitiebestanden gebruiken voor het opslaan van browsermogelijkheden kan voordelen ten opzichte van het alternatief is. Biedt betere prestaties omdat de informatie van de browser wordt geparseerd uit het XML-configuratiebestand en gecompileerd naar een klasse tevoren. De browser definitiebestanden zijn ook gemakkelijker te onderhouden:-de definities zijn hiërarchisch en dus minder op reguliere expressies om te bepalen van de browsermogelijkheden te vertrouwen.      -De definities kunnen worden ingedeeld in meerdere bestanden, waardoor ze gemakkelijker te beheren.      -De definities kunnen worden gedefinieerd op elk niveau op het niveau van Machine.config of een specifieke toepassing. Hierdoor is nodig voor het kopiëren van de volledige set van definities omwille van de mogelijkheden voor een bepaalde browser te overschrijven."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> klasse."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Maakt een exemplaar van de <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klasse met de informatie over de mogelijkheden voor de clientbrowser."
  remarks: "Deze klasse is afgeleid van de gegevens van de browser definitie van de `<browserCaps>` configuratiesectie. Deze sectie is afgeschaft in versie 2.0 van .NET Framework."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Het bovenliggende configuratie-knooppunt."
    - id: configurationContext
      type: System.Object
      description: "De configuratiecontext van het huidige configuratiebestand."
    - id: section
      type: System.Xml.XmlNode
      description: "De sectie van het configuratiebestand dat de gegevens bevat."
    return:
      type: System.Object
      description: "Een exemplaar van <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> die bevat de informatie over de mogelijkheden voor de clientbrowser."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
