### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventHandler
  id: SettingChangingEventHandler
  langs:
  - csharp
  name: SettingChangingEventHandler
  nameWithType: SettingChangingEventHandler
  fullName: System.Configuration.SettingChangingEventHandler
  type: Delegate
  summary: "Hiermee geeft u de methode die wordt afgehandeld tijdens de <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> gebeurtenis."
  remarks: "De <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>gebeurtenis treedt op voordat de waarde van een eigenschap van de instellingen van toepassing is gewijzigd, doorgaans via een aanroep van de <xref:System.Configuration.ApplicationSettingsBase.Item%2A>methode.</xref:System.Configuration.ApplicationSettingsBase.Item%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingChanging> <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>kan worden geannuleerd door de <xref:System.Configuration.SettingChangingEventArgs>gebeurtenis gegevens klasse.</xref:System.Configuration.SettingChangingEventArgs></xref:System.Configuration.ApplicationSettingsBase.SettingChanging>"
  syntax:
    content: public delegate void SettingChangingEventHandler(object sender, SettingChangingEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
