### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  id: ConfigurationBasedIssuerNameRegistry
  children:
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ConfigurationBasedIssuerNameRegistry
  nameWithType: ConfigurationBasedIssuerNameRegistry
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  type: Class
  summary: "Hiermee geeft u een register certificaatverlener die wordt onderhouden door een lijst met vertrouwde verleners geladen van elementen in het configuratiebestand van de toepassing die de naam van elke uitgever aan het X.509-certificaat dat nodig is om te controleren of de handtekening van tokens die wordt geproduceerd door de uitgever koppelen."
  remarks: "The ConfigurationBasedIssuerNameRegistry class maintains a dictionary of trusted issuers by mapping the certificate of each trusted issuer to a name that refers to that issuer. The certificates are specified using the ASN.1 encoded form of the thumbprint. The issuer name can be any string, as long as it is unique within the scope of the application. This dictionary can be accessed through the <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> property. The class can only resolve X.509 certificates.  \n  \n The map of trusted issuers is specified in a configuration file by adding entries under the [\\&lt;trustedIssuers\\&gt;](../Topic/%3CtrustedIssuers%3E.md) element. The `<trustedIssuers>` element is a child element of the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element and it is valid when the ConfigurationBasedIssuerNameRegistry class is specified in the `type` attribute of that element. For more information, see the documentation for each of these elements in the [WIF Configuration Schema](~/add/includes/ajax-current-ext-md.md). For more information about issuer name registries, see the <xref:System.IdentityModel.Tokens.IssuerNameRegistry> class.  \n  \n You can derive from ConfigurationBasedIssuerNameRegistry to implement your own configuration based issuer name registry. Which methods you override will depend upon your implementation. For example, you can override the <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A> method to load configuration from a custom configuration schema."
  example:
  - "The following XML shows configuration for a ConfigurationBasedIssuerNameRegistry added for a collection of security token handlers. The `<trustedIssuers>` element behaves like a classic .NET configuration collection, allowing the `<add>`, `<delete>` and `<clear>` elements as child elements.  \n  \n```  \n<system.identityModel>  \n  <identityConfiguration>  \n    <securityTokenHandlersCollection>  \n      <securityTokenHandlerConfiguration>  \n        <issuerNameRegistry type=\"System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel\">  \n          <trustedIssuers>  \n             <add thumbprint=\"97249e … 158de\" name=\"contoso.com\" />  \n         </trustedIssuers>  \n        </issuerNameRegistry>  \n      </securityTokenHandlerConfiguration>  \n  </identityConfiguration>  \n</system.identityModel>  \n```"
  syntax:
    content: 'public class ConfigurationBasedIssuerNameRegistry : System.IdentityModel.Tokens.IssuerNameRegistry'
  inheritance:
  - System.Object
  - System.IdentityModel.Tokens.IssuerNameRegistry
  implements: []
  inheritedMembers:
  - System.IdentityModel.Tokens.IssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken,System.String)
  - System.IdentityModel.Tokens.IssuerNameRegistry.GetWindowsIssuerName
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: ConfigurationBasedIssuerNameRegistry()
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry&quot;> </xref> klasse."
  syntax:
    content: public ConfigurationBasedIssuerNameRegistry ();
    parameters: []
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  id: AddTrustedIssuer(System.String,System.String)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: AddTrustedIssuer(String,String)
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Hiermee voegt u een verlener toe aan de woordenlijst van vertrouwde verleners."
  remarks: "U kunt deze methode om toe te voegen, te certificaatverleners aanroepen de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A>woordenlijst.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> U kunt deze methode van aanroepen in afgeleide klassen de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A>methode uitgevers van certificaten toevoegen aan de woordenlijst.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A>"
  syntax:
    content: public void AddTrustedIssuer (string certificateThumbprint, string name);
    parameters:
    - id: certificateThumbprint
      type: System.String
      description: "ASN.1 gecodeerde vorm van de vingerafdruk van het certificaat van de verlener."
    - id: name
      type: System.String
      description: "De naam van de verlener."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>certificateThumbprint</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> of leeg.       -or-       <code>name</code> is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> or empty."
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "De opgegeven door uitgever <code> certificateThumbprint </code> is al geconfigureerd. (De uitgever bestaat al in de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>woordenlijst.)</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>"
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  id: ConfiguredTrustedIssuers
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Hiermee wordt de woordenlijst van vertrouwde uitgevers van certificaten die zijn geconfigureerd voor dit exemplaar."
  remarks: "De sleutel aan de woordenlijst is de ASN.1 gecodeerde vorm van de vingerafdruk van certificaat van de vertrouwde verlener en de waarde is de naam van de verlener. Het woordenboek bevat de certificaatverleners die zijn opgegeven in configuratie en uitgevers die zijn toegevoegd met de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer%2A>methode.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer%2A>"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,string> ConfiguredTrustedIssuers { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
      description: "Een woordenlijst met de vertrouwde uitgevers."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  id: GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: GetIssuerName(SecurityToken)
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Retourneert de naam van de certificaatverlener gekoppeld aan de opgegeven <xref href=&quot;System.IdentityModel.Tokens.X509SecurityToken&quot;> </xref> door de vingerafdruk van het certificaat toewijzen aan een naam in de woordenlijst van vertrouwde uitgevers."
  remarks: "De implementatie standaard zoekopdrachten de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A>woordenlijst voor de vingerafdruk van het X.509-certificaat dat is opgegeven in `securityToken`.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> Als een vermelding wordt gevonden, de naam van de certificaatverlener geretourneerd. anders `null` geretourneerd. Als `securityToken` is niet toewijsbaar vanuit <xref:System.IdentityModel.Tokens.X509SecurityToken>, `null` geretourneerd.</xref:System.IdentityModel.Tokens.X509SecurityToken>"
  syntax:
    content: public override string GetIssuerName (System.IdentityModel.Tokens.SecurityToken securityToken);
    parameters:
    - id: securityToken
      type: System.IdentityModel.Tokens.SecurityToken
      description: "Het beveiligingstoken waarvan de naam van de certificaatverlener is aangevraagd. Moet kunnen worden toegewezen als <xref href=&quot;System.IdentityModel.Tokens.X509SecurityToken&quot;> </xref>."
    return:
      type: System.String
      description: "De naam van de certificaatverlener als een vermelding voor de vingerafdruk van het token bestaat in de <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>woordenlijst; anders <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>"
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>securityToken</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "De vertrouwde uitgevers laadt van configuratie."
  remarks: "The LoadCustomConfiguration method is called by the configuration infrastructure. When this method is called, the `nodelist` will contain the top-level child elements of the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element from the configuration file. Each of these may, in turn, contain attributes or child elements depending on the configuration schema you define for your derived class.  \n  \n This method is called by the configuration infrastructure. The default implementation loads configuration from a [\\&lt;trustedIssuers\\&gt;](../Topic/%3CtrustedIssuers%3E.md) element (configured under the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element). You can override this method to provide support for your own custom configuration elements in derived classes."
  syntax:
    content: public override void LoadCustomConfiguration (System.Xml.XmlNodeList customConfiguration);
    parameters:
    - id: customConfiguration
      type: System.Xml.XmlNodeList
      description: "De XML die staat voor de toewijzing van vertrouwde uitgevers van certificaten die is opgegeven in het configuratiebestand."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>customConfiguration</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "De configuratie bevat een of meer elementen die niet worden herkend."
  platform:
  - net462
references:
- uid: System.IdentityModel.Tokens.IssuerNameRegistry
  isExternal: false
  name: System.IdentityModel.Tokens.IssuerNameRegistry
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfigurationBasedIssuerNameRegistry()
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: AddTrustedIssuer(String,String)
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,String>
  nameWithType: IDictionary<String,String>
  fullName: System.Collections.Generic.IDictionary<System.String,System.String>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: GetIssuerName(SecurityToken)
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
- uid: System.IdentityModel.Tokens.SecurityToken
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SecurityToken
  nameWithType: SecurityToken
  fullName: System.IdentityModel.Tokens.SecurityToken
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfigurationBasedIssuerNameRegistry
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: AddTrustedIssuer
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: GetIssuerName
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration
