### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  id: SoapEnvelopeProcessingElement
  children:
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  type: Class
  summary: "Hiermee configureert u een time-out die het risico van aanvallen helpt door beëindigt een aanvraag die langer dan duurt de <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>eigenschapswaarde.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>"
  remarks: "De time-outwaarde is ingeschakeld op elke aanroep <xref:System.Xml.XmlReader.Read%2A>en <xref:System.Xml.XmlReader.MoveToContent%2A>.</xref:System.Xml.XmlReader.MoveToContent%2A> </xref:System.Xml.XmlReader.Read%2A>"
  syntax:
    content: 'public sealed class SoapEnvelopeProcessingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> klasse."
  syntax:
    content: public SoapEnvelopeProcessingElement ();
    parameters: []
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> met behulp van de opgegeven klasse <xref:System.Int32>waarde.</xref:System.Int32>"
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "De waarde van de time-outperiode."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  id: '#ctor(System.Int32,System.Boolean)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van de time-outperiode die is gebruikt om te bepalen of de aanvragen om het risico op denial of service-aanvallen te beëindigen."
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout, bool strict);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "De tijd moet worden gewacht voordat het wordt beëindigd aanvragen naar <> </> *> en <> </> *>."
    - id: strict
      type: System.Boolean
      description: "Of u wilt een uitzondering te genereren als de serialisatiefunctie elementen aantreft of die kenmerken zijn niet in het oorspronkelijke schema. Zie voor meer informatie de <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>eigenschap.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  id: IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van een waarde die of een uitzondering te genereren aangeeft als de serialisatiefunctie onverwachte elementen of kenmerken aantreft."
  remarks: "Stel de eigenschap IsStrict op `true` om u te helpen bij foutopsporing van interoperaties tussen scenario&quot;s. In het algemeen, wanneer de <xref:System.Xml.Serialization.XmlSerializer>klasse voldoet aan een element of kenmerk dat het hoofdverwerkingsknooppunt verwacht niet dat er wordt een gegeven een <xref:System.Xml.Serialization.XmlSerializer.UnknownNode>gebeurtenis en wordt de verwerking vervolgd.</xref:System.Xml.Serialization.XmlSerializer.UnknownNode> </xref:System.Xml.Serialization.XmlSerializer> (Geldt ook wanneer de <xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A>, <xref:System.Xml.Serialization.XmlElementAttribute.Order%2A>, of <xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A>Eigenschappen worden gebruikt, maar gegevens volgorde worden verzonden.)</xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A> De eigenschap IsStrict `true` Hiermee geeft u de webservices uitvoeringstijd voor die gebeurtenis te verwerken en genereert een <xref:System.InvalidOperationException>die een lijst van de verwachte elementen en kenmerken bevat.</xref:System.InvalidOperationException>      > [!NOTE] > Omdat uitzonderingen niet voor alle onverwachte elementen en kenmerken worden veroorzaakt, de eigenschap IsStrict moet niet wordt vertrouwd, behalve als hulp dienen bij foutopsporing. Bijvoorbeeld: onverwachte `xml:lang` en `xml:space` kenmerken kunnen een uitzondering veroorzaakt."
  syntax:
    content: public bool IsStrict { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de serializer van de Web-services wordt gezocht naar onverwachte elementen of kenmerken zijn. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. De standaardwaarde is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  id: ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Opgehaald of ingesteld van de time-outperiode die is gebruikt om te bepalen of de aanvragen om het risico op denial of service-aanvallen te beëindigen."
  syntax:
    content: public int ReadTimeout { get; set; }
    return:
      type: System.Int32
      description: "De tijd moet worden gewacht voordat het wordt beëindigd aanvragen naar <> </> *> en <> </> *>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
