### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  id: ProfileElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  langs:
  - csharp
  name: ProfileElement
  nameWithType: ProfileElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  type: Class
  summary: "Een configuratie-element vertegenwoordigt een <xref href=&quot;System.Activities.Tracking.TrackingProfile&quot;> </xref> en wordt gebruikt voor het toevoegen van een profiel door middel van het element gedrag."
  syntax:
    content: 'public class ProfileElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;> </xref> klasse."
  syntax:
    content: public ProfileElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Hiermee haalt u een sleutel die een unieke identificatie van het profiel."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "De elementsleutel."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  id: ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Opgehaald of ingesteld van de zichtbaarheidsmodus van het profiel bijhouden."
  remarks: "Bijhouden van records uit activiteiten die de uitvoering van activiteiten formulier kan worden gefilterd met de zichtbaarheid modi beschreven door <xref:System.Activities.Tracking.ImplementationVisibility>.</xref:System.Activities.Tracking.ImplementationVisibility> Deze markering wordt gebruikt om u te abonneren voor het bijhouden van de records voor alle activiteiten of alleen voor de activiteiten die zichtbaar zijn in de hoofdmap van de werkstroom.       Wanneer de vlag is ingesteld op <xref:System.Activities.Tracking.ImplementationVisibility>, alleen de hoofdactiviteit en de uitvoering ervan worden bijgehouden.</xref:System.Activities.Tracking.ImplementationVisibility> Als de implementatie van de activiteiten die samengesteld activiteiten zijn bevat, wordt de samengestelde activiteit bijgehouden maar niet de implementatie.       Zie voor meer informatie <xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>.</xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>"
  syntax:
    content: public System.Activities.Tracking.ImplementationVisibility ImplementationVisibility { get; set; }
    return:
      type: System.Activities.Tracking.ImplementationVisibility
      description: "De zichtbaarheidsmodus van het profiel bijhouden"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Opgehaald of ingesteld van de naam van het profiel bijhouden."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "De naam van het profiel bijhouden."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Haalt een <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> die de eigenschappen die zijn gekoppeld aan dit element bevat."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "De verzameling eigenschappen."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  id: Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Hiermee wordt de verzameling <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement&quot;> </xref> elementen die zijn gekoppeld aan dit <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;> </xref>."
  remarks: "Er is een <xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>voor elke werkstroom in het profiel.</xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>"
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection Workflows { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
      description: "Een verzameling van elementen van een profiel voor workflow-query."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
- uid: System.Activities.Tracking.ImplementationVisibility
  parent: System.Activities.Tracking
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ImplementationVisibility
  fullName: System.Activities.Tracking.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileWorkflowElementCollection
  nameWithType: ProfileWorkflowElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement
  nameWithType: ProfileElement.ProfileElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
