### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.DiagnosticsConfigurationHandler
  id: DiagnosticsConfigurationHandler
  children:
  - System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  - System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler
  type: Class
  summary: "De sectie diagnostische gegevens van de configuratiebestanden verwerkt."
  remarks: "De methode DiagnosticsConfigurationHandler is een sectie-handler die deel uitmaakt van de resolutie van configuratie-instellingen in de [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) gedeelte van de configuratiebestanden."
  syntax:
    content: >-
      [System.Obsolete("This class has been deprecated.  http://go.microsoft.com/fwlink/?linkid=14202")]

      public class DiagnosticsConfigurationHandler : System.Configuration.IConfigurationSectionHandler
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Diagnostics.DiagnosticsConfigurationHandler&quot;> </xref> klasse."
  syntax:
    content: public DiagnosticsConfigurationHandler ();
    parameters: []
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "De configuratie-instellingen voor parseert de [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) sectie van de configuratiebestanden."
  remarks: "De methode Create gevuld een <xref:System.Collections.Hashtable>met de waarden die zijn verkregen via de [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) gedeelte van een configuratiebestand en retourneert de hashtable.</xref:System.Collections.Hashtable>"
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Het object is overgenomen van het bovenliggend pad"
    - id: configContext
      type: System.Object
      description: "Gereserveerd. In ASP.NET gebruikt om het virtuele pad van de configuratie die wordt geëvalueerd over te brengen."
    - id: section
      type: System.Xml.XmlNode
      description: "Het XML-hoofdknooppunt in de sectie om af te handelen."
    return:
      type: System.Object
      description: "Een nieuwe configuration-object in de vorm van een <xref href=&quot;System.Collections.Hashtable&quot;> </xref>."
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Switches kunnen niet worden gevonden.       - of - Assert is niet gevonden.       - of - tracering kan niet worden gevonden.       - of - prestatiemeteritems is niet gevonden."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DiagnosticsConfigurationHandler.Create
