### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsContext
  id: SettingsContext
  children:
  - System.Configuration.SettingsContext.#ctor
  langs:
  - csharp
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
  type: Class
  summary: "Biedt contextuele informatie die de provider gebruiken kunt wanneer u instellingen behouden blijven."
  remarks: "De klasse SettingsContext is de basisklasse gebruikt door toepassingen om de provider van instellingen contextuele informatie te geven. De klasse is niet abstract, maar een toepassing kunt maken van een gespecialiseerde klasse die eigenschappen overneemt van de klasse SettingsContext en aanvullende informatie biedt aan specifieke typen providers. De provider Bekijk contextuele instellingen vervolgens bij het schrijven van eigenschappen.       Het primaire doel van de klasse SettingsContext is voor functies die gebruikmaken van de <xref:System.Configuration.SettingsBase>klasse en de bijbehorende infrastructuur.</xref:System.Configuration.SettingsBase> De klasse SettingsContext biedt aanvullende onderdeelspecifieke contextuele informatie over de eigenschapsgegevens worden opgeslagen door de <xref:System.Configuration.SettingsBase>exemplaar.</xref:System.Configuration.SettingsBase> Daarom is het zeer eenvoudig aanvullende informatie opslaan in een klasse SettingsContext zonder die zijn afgeleid van deze (of van andere klassen instellingen *) ter ondersteuning van aanvullende context voor specifieke informatie.       ASP.NET gebruikt bijvoorbeeld de klasse SettingsContext doorgeven langs de gebruikersnaam die is gekoppeld aan de gegevens die worden beheerd door een <xref:System.Configuration.SettingsBase>exemplaar, evenals een eigenschap die aangeeft of de gebruiker wordt beschouwd als geverifieerd.</xref:System.Configuration.SettingsBase> Op deze manier ASP.NET gebruikt de SettingsContext-klasse om te identificeren versus anonieme profielgegevens worden geverifieerd."
  syntax:
    content: 'public class SettingsContext : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net462
- uid: System.Configuration.SettingsContext.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsContext
  langs:
  - csharp
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> klasse."
  syntax:
    content: public SettingsContext ();
    parameters: []
  overload: System.Configuration.SettingsContext.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsContext.#ctor
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
- uid: System.Configuration.SettingsContext.#ctor*
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext.SettingsContext
