### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Hiermee wordt aangegeven of een eigenschap van de instellingen van toepassing een speciale betekenis is. Deze klasse kan niet worden overgenomen."
  remarks: "Eigenschappen voor bepaalde toepassing hebben een speciale betekenis die wijzigt de manier waarop de bijbehorende instellingen mailprovider moet verwerken. De SpecialSettingAttribute wordt gebruikt om te identificeren die eigenschappen. Maakt gebruik van deze klasse de <xref:System.Configuration.SpecialSetting?displayProperty=fullName>om aan te geven welke speciale categorie de eigenschap hoort bij de opsomming.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute kan alleen worden toegepast op de klasse instellingen of aan de eigenschap van de afzonderlijke instellingen.       Zie voor een voorbeeld van hoe een provider van instellingen met de SpecialSettingAttribute omgaat, de <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>methode van de <xref:System.Configuration.LocalFileSettingsProvider>klasse.</xref:System.Configuration.LocalFileSettingsProvider> </xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> klasse."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "Een <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> opsommingswaarde definiëren van de categorie van de eigenschap voor instellingen van toepassing."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee wordt de waarde met een beschrijving van de categorie speciale instelling van de eigenschap voor instellingen van toepassing."
  remarks: "De eigenschap SpecialSetting is ingesteld in de <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>constructor van deze klasse.</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "Een <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> opsommingswaarde definiëren van de categorie van de eigenschap voor instellingen van toepassing."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
