### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.GeometryValueSerializer
  id: GeometryValueSerializer
  children:
  - System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  - System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: GeometryValueSerializer
  nameWithType: GeometryValueSerializer
  fullName: System.Windows.Media.Converters.GeometryValueSerializer
  type: Class
  summary: "Exemplaren van converteert <xref:System.String>naar en van exemplaren van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>.</xref:System.String>"
  remarks: "Deze klasse wordt doorgaans alleen gebruikt door de <xref:System.Windows.Markup.Primitives.MarkupWriter>voor serialisatie doeleinden.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class GeometryValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: GeometryValueSerializer()
  nameWithType: GeometryValueSerializer.GeometryValueSerializer()
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.GeometryValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Windows.Media.Converters.GeometryValueSerializer&quot;> </xref> klasse."
  syntax:
    content: public GeometryValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.GeometryValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Hiermee wordt bepaald of conversie van een bepaalde <xref:System.String>naar een exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> is mogelijk.</xref:System.String>"
  remarks: "Deze methode retourneert altijd `true`."
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "De tekenreeks die moet worden geëvalueerd voor conversie."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie wordt gebruikt voor conversie."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de waarde kan worden geconverteerd. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Hiermee wordt bepaald of een exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> kunnen worden geconverteerd naar een <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> moet worden geëvalueerd voor conversie."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie wordt gebruikt voor conversie."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als <code> value </code> kan worden geconverteerd naar een <xref:System.String>; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.Geometry&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Converteert een <xref:System.String>in een <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>de waarde te converteren naar een <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie wordt gebruikt voor conversie."
    return:
      type: System.Object
      description: "Een nieuw exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> op basis van de opgegeven <code> value </code>."
  overload: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "Converteert een exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> naar een <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Exemplaar van <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> moet worden geëvalueerd voor conversie."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Contextinformatie wordt gebruikt voor conversie."
    return:
      type: System.String
      description: "Een <xref:System.String>weergave van de opgegeven <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> object.</xref:System.String>"
  overload: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: GeometryValueSerializer()
  nameWithType: GeometryValueSerializer.GeometryValueSerializer()
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.GeometryValueSerializer()
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: GeometryValueSerializer
  nameWithType: GeometryValueSerializer.GeometryValueSerializer
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: GeometryValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: GeometryValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: GeometryValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: GeometryValueSerializer.ConvertToString
