### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlWriterSettings
  id: XamlWriterSettings
  children:
  - System.Xaml.XamlWriterSettings.#ctor
  - System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  langs:
  - csharp
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
  type: Class
  summary: "Biedt initialisatie-instellingen voor een <xref href=&quot;System.Xaml.XamlWriter&quot;> </xref> implementatie."
  remarks: "XamlWriterSettings is een klasse voor instellingen die worden gebruikt door een <xref:System.Xaml.XamlWriter>, maar XamlWriterSettings specifieke instellingen niet bijhoudt.</xref:System.Xaml.XamlWriter> De <xref:System.Xaml.XamlWriter>constructor maakt geen gebruik van deze klasse als een argument noch biedt een andere <xref:System.Xaml.XamlWriter>lid gebruikmaken.</xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlWriter> In plaats daarvan de <xref:System.Xaml.XamlXmlWriter>en <xref:System.Xaml.XamlObjectWriter>klassen bevatten hun eigen instellingsklassen als argumenten bouw; beide klassen werkelijke instellingen toevoegen en zijn gebaseerd op XamlWriterSettings.</xref:System.Xaml.XamlObjectWriter> </xref:System.Xaml.XamlXmlWriter>"
  syntax:
    content: public class XamlWriterSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  id: '#ctor(System.Xaml.XamlWriterSettings)'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> klasse met behulp van een ander exemplaar van bestaande instellingen."
  remarks: "Deze constructor ondersteunt het samenvoegen van instellingen, waar extra instellingen afkomstig zijn kunnen uit andere deelnemers aan het schrijfproces of instellingsklassen voor gespecialiseerde schrijvers die <xref:System.Xaml.XamlWriterSettings>.</xref:System.Xaml.XamlWriterSettings> overschrijven"
  syntax:
    content: public XamlWriterSettings (System.Xaml.XamlWriterSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlWriterSettings
      description: "Een bestaande <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> object."
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlWriterSettings.#ctor
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
- uid: System.Xaml.XamlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlWriterSettings.#ctor*
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings.XamlWriterSettings
