### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  id: ProcessModelComAuthenticationLevel
  children:
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  langs:
  - csharp
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
  type: Enum
  summary: "Hiermee geeft u het verificatieniveau voor DCOM-beveiliging."
  remarks: "De ProcessModelComAuthenticationLevel inventariseert de waarden voor gebruik bij het instellen van de <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>eigenschap.</xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>       De standaardwaarde is verbinding maken.      > [!NOTE] > De ProcessModelComAuthenticationLevel instellingen zijn alleen relevant wanneer u de ASP.NET-procesmodel (Internet Information Services [IIS] 5.n of alleen compatibele modus op IIS 6)."
  example:
  - "The following code example shows how to get the current <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property value and then set the <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property to a new value of Call.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/csharp/t-system.web.configurati_40_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/visualbasic/t-system.web.configurati_40_1.vb)]"
  syntax:
    content: public enum ProcessModelComAuthenticationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  id: Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat de referenties van de client worden geverifieerd door DCOM. Dit veld is constante."
  remarks: "DCOM verifieert de referenties van de client wanneer de server de aanvraag aan het begin van elke externe procedureaanroep ontvangt."
  syntax:
    content: Call
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  id: Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat de referenties van de client worden geverifieerd door DCOM. Dit veld is constante."
  remarks: "DCOM verifieert de referenties van de client alleen wanneer de client tot stand een relatie met de server brengt.       Dit is de standaardwaarde."
  syntax:
    content: Connect
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat het verificatieniveau wordt bepaald door DCOM. Dit veld is constante."
  remarks: "DCOM bepaalt het verificatieniveau normale beveiligingsonderhandeling wordt gebruikt."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u geen verificatie. Dit veld is constante."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  id: Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat DCOM verifieert of alle gegevens ontvangen van de verwachte client. Dit veld is constante."
  remarks: "De transporten datagram altijd Pkt-verificatie gebruiken."
  syntax:
    content: Pkt
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  id: PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hiermee geeft u op dat DCOM verifieert en controleert of de gegevens overgedragen. Dit veld is constante."
  remarks: "DCOM verifieert dat geen van de gegevensoverdracht tussen de client en de server is gewijzigd."
  syntax:
    content: PktIntegrity
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  id: PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specificeert dat DCOM verifieert alle vorige niveaus en versleuteling biedt. Dit veld is constante."
  remarks: "DCOM verifieert alle eerdere niveaus en de waarde van het argument van de externe procedureaanroep worden versleuteld."
  syntax:
    content: PktPrivacy
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Moet worden toegevoegd."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
