### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Biedt gegevens voor de <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> gebeurtenis."
  remarks: "De klasse SettingChangingEventArgs biedt gegevens voor de <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>gebeurtenis geeft aan dat de waarde van een eigenschap van de instellingen van toepassing is gewijzigd.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging> De meest voorkomende bron voor deze gebeurtenis is de `get` accessor van de <xref:System.Configuration.ApplicationSettingsBase.Item%2A>methode in de <xref:System.Configuration.ApplicationSettingsBase>klasse.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Item%2A>       Omdat SettingChangingEventArgs is afgeleid van <xref:System.ComponentModel.CancelEventArgs>, de handler heeft de mogelijkheid om de schrijfbewerking wordt geannuleerd.</xref:System.ComponentModel.CancelEventArgs>"
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiseert een exemplaar van de <xref href=&quot;System.Configuration.SettingChangingEventArgs&quot;> </xref> klasse."
  remarks: "De waarden van de parameters in de constructor SettingChangingEventArgs NET worden toegewezen aan de bijbehorende eigenschappen in de <xref:System.Configuration.SettingChangingEventArgs>klasse.</xref:System.Configuration.SettingChangingEventArgs>"
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "Een <xref:System.String>met de naam van de toepassingsinstelling.</xref:System.String>"
    - id: settingClass
      type: System.String
      description: "Een <xref:System.String>met een categoriebeschrijving van de instelling.</xref:System.String> Deze parameter is vaak ingesteld op de naam van de toepassingsgroep instellingen."
    - id: settingKey
      type: System.String
      description: "Een <xref:System.String>met de sleutel van de instellingen van toepassing.</xref:System.String>"
    - id: newValue
      type: System.Object
      description: "Een <xref:System.Object>die de nieuwe waarde moet worden toegewezen aan de eigenschap voor instellingen van toepassing bevat.</xref:System.Object>"
    - id: cancel
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>annuleren van de gebeurtenis plaatsvindt. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de nieuwe waarde wordt toegewezen aan de eigenschap voor instellingen van toepassing."
  remarks: "Het werkelijke type van de eigenschap NewValue moet compatibel zijn met de eigenschap voor instellingen wordt ingesteld. De laatste is beschikbaar via de <xref:System.Configuration.SettingsProperty.PropertyType%2A>eigenschap van de <xref:System.Configuration.SettingsProperty>klasse.</xref:System.Configuration.SettingsProperty> </xref:System.Configuration.SettingsProperty.PropertyType%2A>"
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "Een <xref:System.Object>die de nieuwe waarde moet worden toegewezen aan de eigenschap voor instellingen van toepassing bevat.</xref:System.Object>"
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de toepassing instellingen eigenschapscategorie."
  remarks: "Alle toepassingsinstellingen behoren tot een groep van toepassingen instellingen. Naam van de groep kan expliciet worden geleverd door het versieren van de klasse met een <xref:System.Configuration.SettingsGroupNameAttribute>anders wordt een gegenereerd met de naam van de instellingen wrapper-klasse.</xref:System.Configuration.SettingsGroupNameAttribute>"
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>met een categoriebeschrijving van de instelling.</xref:System.String> Normaal gesproken is deze parameter ingesteld op de naam van de toepassing-instellingen."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de toepassing instellingensleutel gekoppeld aan de eigenschap."
  remarks: "Elke wrapperklasse instellingen die zijn afgeleid van <xref:System.Configuration.ApplicationSettingsBase>, heeft een bijbehorende instellingen-sleutel is een tekenreeks die helpt de verschillende exemplaren van de dezelfde wrapper in één toepassing dubbelzinnigheid.</xref:System.Configuration.ApplicationSettingsBase> Omdat elke wrapperklasse een set eigenschappen die toepassingsinstellingen vertegenwoordigen definieert, kunt de instellingensleutel op dezelfde manier dubbelzinnigheid van het gebruik ervan."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>met de sleutel van de instellingen van toepassing.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hiermee haalt u de naam van de toepassingsinstelling die is gekoppeld aan de eigenschap voor instellingen van toepassing."
  remarks: "Doorgaans de instellingen wrapper-klasse wordt afgeleid van <xref:System.Configuration.ApplicationSettingsBase>, zodat de naam van de eigenschap voor instellingen van toepassing hetzelfde als de instelling van de bijbehorende toepassing is wordt neergezet.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "Een <xref:System.String>met de naam van de toepassingsinstelling.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
