### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  id: BaseAddressPrefixFilterElement
  children:
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  type: Class
  summary: "Hiermee geeft u een configuratie-element waarmee een pass via filter, een mechanisme voor het kiezen van de juiste IIS-bindingen bij het hosten van een [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] toepassing in IIS. Deze klasse kan niet worden overgenomen."
  remarks: "Een voorvoegsel filterprovider een mechanisme voor een service te binden aan een specifieke URI. Hiermee kunt u voor het hosten van meerdere toepassingen met verschillende basisadressen voor hetzelfde schema op dezelfde site.       IIS-websites zijn containers voor virtuele toepassingen die virtuele mappen bevatten. De toepassing in een site kan worden geopend via een of meer IIS-binding. IIS-bindingen bieden twee soorten informatie: bindingsprotocol en informatie over de binding. Het schema gedurende welke de communicatie plaatsvindt binding protocol (bijv, HTTP) definieert en bindingsgegevens (bijvoorbeeld IP-adres, poort, Hostheader) bevat gegevens die worden gebruikt voor toegang tot de site.       IIS ondersteunt meerdere IIS-bindingen per site instellen, wat tot meerdere basisadressen per schema leidt opgeven. Omdat een [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] service die wordt gehost op een site kan slechts één basisadres per schema binding, kunt u de functie voorvoegsel filter kiest u de vereiste basisadres van de gehoste service.  De binnenkomende basisadressen opgegeven door IIS worden gefilterd op basis van het filter voor de optioneel voorvoegsel-lijst.       Bijvoorbeeld, uw site mag de volgende basisadressen ```   http://testl.fabrikam.com/Service.svc   http://test2.fabrikam.com/Service.svc   ``` kunt u het volgende configuratiebestand om op te geven van een voorvoegsel-filter op het niveau van het appdomain.      ```   <system.serviceModel>     <serviceHostingEnvironment>        <baseAddressPrefixFilters>           <add prefix=”net.tcp://test1.fabrikam.com:8000”/>           <add prefix=”http://test2.fabrikam.com:9000”/>       </baseAddressPrefixFilters>     </serviceHostingEnvironment>   </system.serviceModel>   ```In dit voorbeeld `net.tcp://test1.fabrikam.com:8000` en `http://test2.fabrikam.com:9000` zijn alleen basisadressen voor hun respectieve schema&quot;s die kunnen worden doorgegeven.       Standaard als voorvoegsel niet is opgegeven, alle adressen doorgegeven. Alleen de overeenkomende basisadres voor dit schema moet worden doorgegeven via leidt het voorvoegsel geven.      > [!NOTE] > Jokertekens biedt geen ondersteuning voor het filter. Bovendien de baseAddresses geleverd door IIS mogelijk adressen die zijn gebonden aan andere schema&quot;s die niet aanwezig in de `baseAddressPrefixFilters` lijst. Deze adressen worden niet gefilterd."
  syntax:
    content: 'public sealed class BaseAddressPrefixFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klasse."
  syntax:
    content: public BaseAddressPrefixFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  id: '#ctor(System.Uri)'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klasse met een specifieke URI."
  syntax:
    content: public BaseAddressPrefixFilterElement (Uri prefix);
    parameters:
    - id: prefix
      type: System.Uri
      description: "Een filter dat ervoor zorgt dat de service om te luisteren op alle URI&quot;s die beginnen met dit specifieke voorvoegsel."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Opgehaald of ingesteld van een voorvoegsel dat wordt gebruikt voor een deel van een basisadres."
  syntax:
    content: public Uri Prefix { get; set; }
    return:
      type: System.Uri
      description: "Een URI die wordt gebruikt voor een deel van een basisadres."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Moet worden toegevoegd."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
