### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DependentPlatformMissingException
  id: DependentPlatformMissingException
  children:
  - System.Deployment.Application.DependentPlatformMissingException.#ctor
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  - System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  langs:
  - csharp
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException
  fullName: System.Deployment.Application.DependentPlatformMissingException
  type: Class
  summary: "De uitzondering die wordt gegenereerd wanneer de platformafhankelijkheid niet tijdens de activering van de ClickOnce-implementatie en de implementatie gevonden is wordt niet uitgevoerd."
  remarks: "Deze uitzondering wordt gegenereerd wanneer er een discrepantie tussen het platform dat in het implementatiemanifest is aangevraagd en het platform dat ClickOnce probeert uit te voeren van de toepassing op. In deze context kunt &quot;platform&quot; verwijzen naar het besturingssysteem, de geïnstalleerde versies van de common language runtime of een eerder geïnstalleerde assembly. Bijvoorbeeld, de ClickOnce-toepassing asserts die Windows XP is vereist als de gebruiker probeert uit te voeren van de toepassing op Windows 2000, deze uitzondering wordt uitgevoerd."
  syntax:
    content: 'public class DependentPlatformMissingException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> klasse."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A>eigenschap van het nieuwe exemplaar voor een systeem geleverd bericht met een beschrijving van de fout, zoals &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot;.</xref:System.Exception.Message%2A> Dit bericht wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException ();
    parameters: []
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout."
  remarks: "De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.DependentPlatformMissingException>.</xref:System.Deployment.Application.DependentPlatformMissingException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> klasse."
  remarks: "Deze constructor is aangeroepen tijdens de deserialisatie op het object exception verzonden via een stroom opnieuw samenstellen."
  syntax:
    content: protected DependentPlatformMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "De contextuele informatie over de bron- of doelserver."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException%2A>eigenschap.</xref:System.Exception.InnerException%2A> De <xref:System.Exception.InnerException%2A>eigenschap dezelfde waarde die is doorgegeven aan de constructor of `null` als de <xref:System.Exception.InnerException%2A>eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Deployment.Application.DependentPlatformMissingException>.</xref:System.Deployment.Application.DependentPlatformMissingException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering. Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  id: '#ctor(System.String,System.Uri)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> klasse."
  syntax:
    content: public DependentPlatformMissingException (string message, Uri supportUrl);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht van uitzondering."
    - id: supportUrl
      type: System.Uri
      description: "De URL voor informatie over productondersteuning bezoeken."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u de objectgegevens."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "De contextuele informatie over de bron- of doelserver."
  overload: System.Deployment.Application.DependentPlatformMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Hiermee haalt u een URI die aangeeft waar ondersteuning kan worden gevonden voor het probleem is opgetreden."
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: "Een URI die aangeeft waar ondersteuning kan worden gevonden voor het probleem is opgetreden."
  overload: System.Deployment.Application.DependentPlatformMissingException.SupportUrl*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: DependentPlatformMissingException.GetObjectData
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
