### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "Definieert de methoden waarmee u een klasse aangepaste configuratie laden."
  remarks: "Klassen die de interface ICustomIdentityConfiguration implementeren kunnen aangepaste configuratie laden van XML.       Diverse klassen Windows Identity Foundation (WIF) implementeert de interface ICustomIdentityConfiguration om aan te bieden de mogelijkheid om te definiëren van aangepaste configuratie van afgeleide klassen uit een configuratiebestand. Veel van de klassen WIF bieden een basisimplementatie van deze methode om de standaardconfiguratie voor de objecten die ze vertegenwoordigen."
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Aangepaste configuratie laden van XML. Negeer deze methode voor aangepaste verwerking van configuratie-elementen."
  remarks: "De methode LoadCustomConfiguration wordt aangeroepen door de infrastructuur van de configuratie. Als deze methode wordt aangeroepen, de `nodelist` parameter bevat de op het hoogste niveau van onderliggende elementen van het bovenliggende element dat Hiermee configureert u de object-klasse in het configuratiebestand. Bijvoorbeeld: een klasse wordt afgeleid van <xref:System.IdentityModel.Tokens.IssuerNameRegistry>, heeft de onderliggende elementen van de [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) -element doorgegeven de `nodelist` parameter.</xref:System.IdentityModel.Tokens.IssuerNameRegistry> De `nodelist` bestaat geheel uit <xref:System.Xml.XmlElement>objecten.</xref:System.Xml.XmlElement> Elk van deze mogelijk kenmerken en onderliggende elementen, afhankelijk van het configuratieschema gedefinieerd voor de klasse die wordt geconfigureerd."
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "De XML-knooppunten die de aangepaste configuratie bevatten. Elk knooppunt in de lijst is van het type <xref href=&quot;System.Xml.XmlElement&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
