### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingSectionGroup
  id: ScriptingSectionGroup
  children:
  - System.Web.Configuration.ScriptingSectionGroup.#ctor
  - System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  - System.Web.Configuration.ScriptingSectionGroup.WebServices
  langs:
  - csharp
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup
  fullName: System.Web.Configuration.ScriptingSectionGroup
  type: Class
  summary: "De configuratiesectie voor scriptinstellingen vertegenwoordigt. Deze klasse kan niet worden overgenomen."
  remarks: "De klasse ScriptingSectionGroup gebruiken via een programma instellen en ophalen van de waarden van de `scripting` gedeelte van het configuratiebestand."
  syntax:
    content: 'public sealed class ScriptingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.Configuration.ScriptingSectionGroup&quot;> </xref> klasse."
  syntax:
    content: public ScriptingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  id: ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Haalt een <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;> </xref> -object dat is afgeleid van de huidige systeemconfiguratie."
  remarks: "Gebruik de `ScriptingScriptResourceHandler` configuratiesectie om in te stellen of script die bestanden zijn ingesloten resources zijn gecomprimeerd en opgeslagen in de cache. U kunt inschakelen of uitschakelen van compressie en opslaan in cache met behulp van de <xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>en <xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A>Eigenschappen.</xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A> </xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>"
  syntax:
    content: public System.Web.Configuration.ScriptingScriptResourceHandlerSection ScriptResourceHandler { get; }
    return:
      type: System.Web.Configuration.ScriptingScriptResourceHandlerSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  id: WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Haalt een <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;> </xref> -object dat is afgeleid van de huidige systeemconfiguratie."
  syntax:
    content: public System.Web.Configuration.ScriptingWebServicesSectionGroup WebServices { get; }
    return:
      type: System.Web.Configuration.ScriptingWebServicesSectionGroup
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
