### YamlMime:ManagedReference
items:
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  id: SettingsSavedEventArgs
  children:
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  langs:
  - csharp
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  type: Class
  summary: "Biedt gegevens voor de <xref href=&quot;System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved&quot;> </xref> gebeurtenis."
  remarks: "De <xref:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved?displayProperty=fullName>gebeurtenis treedt op nadat de provider van instellingen toegang heeft tot de service instellingen, zelfs als de instellingen zijn niet opgeslagen.</xref:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved?displayProperty=fullName> Een reden dat de provider mislukken kan als u de instellingen opslaan is als de huidige gebruiker is afgemeld. U kunt de <xref:System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList%2A>eigenschap om te bepalen of alle instellingen zijn niet opgeslagen.</xref:System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList%2A>       Deze gebeurtenis treedt niet op als de instellingen voor provider heeft geen toegang de service instellingen, waardoor in plaats daarvan de provider tot om een <xref:System.Net.WebException>.</xref:System.Net.WebException>       Zie voor meer informatie over het verwerken van gebeurtenissen [KROONTJESPEN: gebeurtenissen verbruikt](http://msdn.microsoft.com/en-us/01e4f1bc-e55e-413f-98c7-6588493e5f67)."
  example:
  - "The following example code demonstrates how to use this class to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/visualbasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/csharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: 'public class SettingsSavedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  id: '#ctor(System.Collections.Generic.IEnumerable{System.String})'
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.ClientServices.Providers.SettingsSavedEventArgs&quot;> </xref> klasse."
  syntax:
    content: public SettingsSavedEventArgs (System.Collections.Generic.IEnumerable<string> failedSettingsList);
    parameters:
    - id: failedSettingsList
      type: System.Collections.Generic.IEnumerable{System.String}
      description: "De instellingen die niet kon de provider van instellingen op te slaan."
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  id: FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "De instellingen opgehaald die de <xref href=&quot;System.Web.ClientServices.Providers.ClientSettingsProvider&quot;> </xref> kan niet worden opgeslagen met de server."
  remarks: "Een reden dat de provider mislukken kan als u de instellingen opslaan is als de huidige gebruiker is afgemeld. U kunt de eigenschap FailedSettingsList gebruiken om te bepalen of alle instellingen zijn niet opgeslagen."
  example:
  - "The following example code demonstrates how to use this property to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/visualbasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/csharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> FailedSettingsList { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "De instellingen die zijn niet opgeslagen."
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
- uid: System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<String>
  nameWithType: IEnumerable<String>
  fullName: System.Collections.Generic.IEnumerable<System.String>
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
