### YamlMime:ManagedReference
items:
- uid: System.Activities.Validation.ValidationSettings
  id: ValidationSettings
  children:
  - System.Activities.Validation.ValidationSettings.#ctor
  - System.Activities.Validation.ValidationSettings.AdditionalConstraints
  - System.Activities.Validation.ValidationSettings.CancellationToken
  - System.Activities.Validation.ValidationSettings.Environment
  - System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  - System.Activities.Validation.ValidationSettings.PrepareForRuntime
  - System.Activities.Validation.ValidationSettings.SingleLevel
  - System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Activities.Validation.ValidationSettings
  type: Class
  summary: "Vertegenwoordigt een verzameling instellingen die het gedrag aanpassen die <xref:System.Activities.Validation.ActivityValidationServices.Validate*>zou vertonen.</xref:System.Activities.Validation.ActivityValidationServices.Validate*> Ook kunt de gebruiker activiteit beleidsbeperkingen toepassen op een werkstroom."
  syntax:
    content: public class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.#ctor
  id: '#ctor'
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Maakt een nieuw exemplaar van de <xref href=&quot;System.Activities.Validation.ValidationSettings&quot;> </xref> klasse."
  syntax:
    content: public ValidationSettings ();
    parameters: []
  overload: System.Activities.Validation.ValidationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  id: AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Hiermee haalt u een dictionary van typebeperking paren. Elke aanvullende beperking toegevoegd aan de woordenlijst wordt toegepast op elke activiteit van het type opgeven in de werkstroom te valideren."
  syntax:
    content: public System.Collections.Generic.IDictionary<Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>> AdditionalConstraints { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
      description: "Een woordenlijst Geef een lijst met beperkingen en typen."
  overload: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  id: CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van de annulering token gebruikt voor de aanmelding moet de activiteit worden geannuleerd."
  syntax:
    content: public System.Threading.CancellationToken CancellationToken { get; set; }
    return:
      type: System.Threading.CancellationToken
      description: "De annulering token gebruikt voor de aanmelding moet de activiteit worden geannuleerd."
  overload: System.Activities.Validation.ValidationSettings.CancellationToken*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.Environment
  id: Environment
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van de omgeving van variabelen en argumenten voor de instellingen van deze validatie."
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Environment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: "De omgeving van variabelen en argumenten voor de instellingen van deze validatie."
  overload: System.Activities.Validation.ValidationSettings.Environment*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  id: OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de aanvullende validatie-beperkingen zijn uitsluitend voor het valideren van de werkstroom worden gebruikt. Indien ingesteld op <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, alle validatietests die zich in de activiteit zelf worden genegeerd."
  remarks: "<xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>wordt aangeroepen wanneer een werkstroom wordt uitgevoerd, en eventuele fouten, waardoor een <xref:System.Activities.InvalidWorkflowException>gegenereerd.</xref:System.Activities.InvalidWorkflowException></xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>"
  syntax:
    content: public bool OnlyUseAdditionalConstraints { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de aanvullende beperkingen zijn exclusief; worden gebruikt anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  id: PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of dit exemplaar is voorbereid voor runtime."
  syntax:
    content: public bool PrepareForRuntime { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Als dit exemplaar is voorbereid voor runtime; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  id: SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de opgegeven activiteit en alle onderliggende elementen en onderliggende onderliggende elementen van de opgegeven activiteit worden gevalideerd of als de validatiefunctie moet valideren alleen voor de activiteit opgegeven."
  syntax:
    content: public bool SingleLevel { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als een element wordt gevalideerd zonder te valideren van de onderliggende elementen; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> als het element en de onderliggende elementen en onderliggende onderliggende elementen zijn gevalideerd."
  overload: System.Activities.Validation.ValidationSettings.SingleLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  id: SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Opgehaald of ingesteld van een waarde die aangeeft of de configuratie van de hoofdmap geen onderwerp voor validatie is."
  syntax:
    content: public bool SkipValidatingRootConfiguration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als de configuratie van de hoofdmap niet onderworpen voor validatie; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Validation.ValidationSettings.#ctor
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
- uid: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<Type,IList<Constraint>>
  nameWithType: IDictionary<Type,IList<Constraint>>
  fullName: System.Collections.Generic.IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: Type
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Activities.Validation.Constraint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Validation.Constraint
    name: Constraint
    nameWithType: Constraint
    fullName: Constraint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
- uid: System.Activities.Validation.ValidationSettings.#ctor*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings
  nameWithType: ValidationSettings.ValidationSettings
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.CancellationToken*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
